// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config23_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
output  [14:0] ap_return;

reg ap_idle;
reg[14:0] ap_return;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln42_fu_692_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] w23_address0;
wire   [5:0] w23_q0;
wire   [3:0] w23_address1;
wire   [5:0] w23_q1;
reg   [0:0] do_init_reg_209;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] phi_ln55_reg_224;
reg   [7:0] p_read16_phi_reg_462;
reg   [7:0] p_read117_phi_reg_474;
reg   [7:0] p_read218_phi_reg_486;
reg   [7:0] p_read319_phi_reg_498;
reg   [7:0] p_read420_phi_reg_510;
reg   [7:0] p_read521_phi_reg_522;
reg   [7:0] p_read622_phi_reg_534;
reg   [7:0] p_read723_phi_reg_546;
reg   [7:0] p_read824_phi_reg_558;
reg   [7:0] p_read925_phi_reg_570;
reg   [7:0] p_read1026_phi_reg_582;
reg   [7:0] p_read1127_phi_reg_594;
reg   [7:0] p_read1228_phi_reg_606;
reg   [7:0] p_read1329_phi_reg_618;
reg   [7:0] p_read1430_phi_reg_630;
reg   [7:0] p_read1531_phi_reg_642;
reg   [14:0] res_010_reg_654;
wire   [2:0] in_index_fu_686_p2;
reg   [2:0] in_index_reg_938;
reg   [0:0] icmp_ln42_reg_943;
reg   [0:0] icmp_ln42_reg_943_pp0_iter1_reg;
reg   [0:0] icmp_ln42_reg_943_pp0_iter2_reg;
wire   [7:0] a_fu_698_p19;
reg   [7:0] a_reg_947;
reg  signed [5:0] w_reg_952;
wire   [7:0] a_1_fu_738_p19;
reg   [7:0] a_1_reg_957;
reg  signed [5:0] w_1_reg_962;
reg   [10:0] trunc_ln1_reg_967;
reg   [10:0] trunc_ln53_1_reg_972;
wire   [14:0] add_ln53_1_fu_838_p2;
reg   [0:0] ap_phi_mux_do_init_phi_fu_212_p6;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_phi_ln55_phi_fu_227_p6;
reg   [7:0] ap_phi_mux_p_read16_phi_phi_fu_466_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read16_phi_reg_462;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read16_phi_reg_462;
reg   [7:0] ap_phi_mux_p_read117_phi_phi_fu_478_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read117_phi_reg_474;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read117_phi_reg_474;
reg   [7:0] ap_phi_mux_p_read218_phi_phi_fu_490_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read218_phi_reg_486;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read218_phi_reg_486;
reg   [7:0] ap_phi_mux_p_read319_phi_phi_fu_502_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read319_phi_reg_498;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read319_phi_reg_498;
reg   [7:0] ap_phi_mux_p_read420_phi_phi_fu_514_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read420_phi_reg_510;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read420_phi_reg_510;
reg   [7:0] ap_phi_mux_p_read521_phi_phi_fu_526_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read521_phi_reg_522;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read521_phi_reg_522;
reg   [7:0] ap_phi_mux_p_read622_phi_phi_fu_538_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read622_phi_reg_534;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read622_phi_reg_534;
reg   [7:0] ap_phi_mux_p_read723_phi_phi_fu_550_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read723_phi_reg_546;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read723_phi_reg_546;
reg   [7:0] ap_phi_mux_p_read824_phi_phi_fu_562_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read824_phi_reg_558;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read824_phi_reg_558;
reg   [7:0] ap_phi_mux_p_read925_phi_phi_fu_574_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read925_phi_reg_570;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read925_phi_reg_570;
reg   [7:0] ap_phi_mux_p_read1026_phi_phi_fu_586_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1026_phi_reg_582;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1026_phi_reg_582;
reg   [7:0] ap_phi_mux_p_read1127_phi_phi_fu_598_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1127_phi_reg_594;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1127_phi_reg_594;
reg   [7:0] ap_phi_mux_p_read1228_phi_phi_fu_610_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1228_phi_reg_606;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1228_phi_reg_606;
reg   [7:0] ap_phi_mux_p_read1329_phi_phi_fu_622_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1329_phi_reg_618;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1329_phi_reg_618;
reg   [7:0] ap_phi_mux_p_read1430_phi_phi_fu_634_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1430_phi_reg_630;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1430_phi_reg_630;
reg   [7:0] ap_phi_mux_p_read1531_phi_phi_fu_646_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read1531_phi_reg_642;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read1531_phi_reg_642;
reg   [14:0] ap_phi_mux_res_010_phi_fu_658_p6;
reg    ap_loop_init_pp0_iter1_reg;
reg    ap_loop_init_pp0_iter2_reg;
reg    ap_loop_init_pp0_iter3_reg;
wire   [63:0] zext_ln42_fu_668_p1;
wire   [63:0] add_ln55_cast_cast_cast_fu_681_p1;
reg    w23_ce1_local;
reg    w23_ce0_local;
wire   [3:0] add_ln55_cast_cast_fu_673_p3;
wire   [7:0] a_fu_698_p17;
wire   [7:0] a_1_fu_738_p17;
wire   [7:0] mul_ln73_fu_784_p0;
wire   [13:0] mul_ln73_fu_784_p2;
wire   [7:0] mul_ln73_1_fu_806_p0;
wire   [13:0] mul_ln73_1_fu_806_p2;
wire  signed [11:0] sext_ln53_fu_825_p1;
wire  signed [11:0] trunc_ln53_cast_fu_822_p1;
wire   [11:0] add_ln53_fu_828_p2;
wire  signed [14:0] sext_ln53_1_fu_834_p1;
reg   [14:0] ap_return_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [13:0] mul_ln73_1_fu_806_p00;
wire   [13:0] mul_ln73_fu_784_p00;
reg    ap_condition_199;
reg    ap_condition_210;
wire   [2:0] a_fu_698_p1;
wire   [2:0] a_fu_698_p3;
wire   [2:0] a_fu_698_p5;
wire   [2:0] a_fu_698_p7;
wire  signed [2:0] a_fu_698_p9;
wire  signed [2:0] a_fu_698_p11;
wire  signed [2:0] a_fu_698_p13;
wire  signed [2:0] a_fu_698_p15;
wire   [2:0] a_1_fu_738_p1;
wire   [2:0] a_1_fu_738_p3;
wire   [2:0] a_1_fu_738_p5;
wire   [2:0] a_1_fu_738_p7;
wire  signed [2:0] a_1_fu_738_p9;
wire  signed [2:0] a_1_fu_738_p11;
wire  signed [2:0] a_1_fu_738_p13;
wire  signed [2:0] a_1_fu_738_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_return_preg = 15'd0;
end

myproject_dense_resource_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config23_s_w23_ROM_AUTfYi #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
w23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w23_address0),
    .ce0(w23_ce0_local),
    .q0(w23_q0),
    .address1(w23_address1),
    .ce1(w23_ce1_local),
    .q1(w23_q1)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U3153(
    .din0(ap_phi_mux_p_read16_phi_phi_fu_466_p4),
    .din1(ap_phi_mux_p_read117_phi_phi_fu_478_p4),
    .din2(ap_phi_mux_p_read218_phi_phi_fu_490_p4),
    .din3(ap_phi_mux_p_read319_phi_phi_fu_502_p4),
    .din4(ap_phi_mux_p_read420_phi_phi_fu_514_p4),
    .din5(ap_phi_mux_p_read521_phi_phi_fu_526_p4),
    .din6(ap_phi_mux_p_read622_phi_phi_fu_538_p4),
    .din7(ap_phi_mux_p_read723_phi_phi_fu_550_p4),
    .def(a_fu_698_p17),
    .sel(phi_ln55_reg_224),
    .dout(a_fu_698_p19)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U3154(
    .din0(ap_phi_mux_p_read824_phi_phi_fu_562_p4),
    .din1(ap_phi_mux_p_read925_phi_phi_fu_574_p4),
    .din2(ap_phi_mux_p_read1026_phi_phi_fu_586_p4),
    .din3(ap_phi_mux_p_read1127_phi_phi_fu_598_p4),
    .din4(ap_phi_mux_p_read1228_phi_phi_fu_610_p4),
    .din5(ap_phi_mux_p_read1329_phi_phi_fu_622_p4),
    .din6(ap_phi_mux_p_read1430_phi_phi_fu_634_p4),
    .din7(ap_phi_mux_p_read1531_phi_phi_fu_646_p4),
    .def(a_1_fu_738_p17),
    .sel(phi_ln55_reg_224),
    .dout(a_1_fu_738_p19)
);

myproject_mul_8ns_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8ns_6s_14_1_1_U3155(
    .din0(mul_ln73_fu_784_p0),
    .din1(w_reg_952),
    .dout(mul_ln73_fu_784_p2)
);

myproject_mul_8ns_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8ns_6s_14_1_1_U3156(
    .din0(mul_ln73_1_fu_806_p0),
    .din1(w_1_reg_962),
    .dout(mul_ln73_1_fu_806_p2)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 15'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_reg_943_pp0_iter2_reg == 1'd1))) begin
            ap_return_preg <= add_ln53_1_fu_838_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1026_phi_reg_582 <= p_read10;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1026_phi_reg_582 <= ap_phi_reg_pp0_iter0_p_read1026_phi_reg_582;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1127_phi_reg_594 <= p_read11;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1127_phi_reg_594 <= ap_phi_reg_pp0_iter0_p_read1127_phi_reg_594;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read117_phi_reg_474 <= p_read1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read117_phi_reg_474 <= ap_phi_reg_pp0_iter0_p_read117_phi_reg_474;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1228_phi_reg_606 <= p_read12;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1228_phi_reg_606 <= ap_phi_reg_pp0_iter0_p_read1228_phi_reg_606;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1329_phi_reg_618 <= p_read13;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1329_phi_reg_618 <= ap_phi_reg_pp0_iter0_p_read1329_phi_reg_618;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1430_phi_reg_630 <= p_read14;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1430_phi_reg_630 <= ap_phi_reg_pp0_iter0_p_read1430_phi_reg_630;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read1531_phi_reg_642 <= p_read15;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read1531_phi_reg_642 <= ap_phi_reg_pp0_iter0_p_read1531_phi_reg_642;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read16_phi_reg_462 <= p_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read16_phi_reg_462 <= ap_phi_reg_pp0_iter0_p_read16_phi_reg_462;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read218_phi_reg_486 <= p_read2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read218_phi_reg_486 <= ap_phi_reg_pp0_iter0_p_read218_phi_reg_486;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read319_phi_reg_498 <= p_read3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read319_phi_reg_498 <= ap_phi_reg_pp0_iter0_p_read319_phi_reg_498;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read420_phi_reg_510 <= p_read4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read420_phi_reg_510 <= ap_phi_reg_pp0_iter0_p_read420_phi_reg_510;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read521_phi_reg_522 <= p_read5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read521_phi_reg_522 <= ap_phi_reg_pp0_iter0_p_read521_phi_reg_522;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read622_phi_reg_534 <= p_read6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read622_phi_reg_534 <= ap_phi_reg_pp0_iter0_p_read622_phi_reg_534;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read723_phi_reg_546 <= p_read7;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read723_phi_reg_546 <= ap_phi_reg_pp0_iter0_p_read723_phi_reg_546;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read824_phi_reg_558 <= p_read8;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read824_phi_reg_558 <= ap_phi_reg_pp0_iter0_p_read824_phi_reg_558;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((ap_phi_mux_do_init_phi_fu_212_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read925_phi_reg_570 <= p_read9;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read925_phi_reg_570 <= ap_phi_reg_pp0_iter0_p_read925_phi_reg_570;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_209 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        do_init_reg_209 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read1026_phi_reg_582 <= p_read1026_phi_reg_582;
        end else if ((1'b1 == 1'b1)) begin
            p_read1026_phi_reg_582 <= ap_phi_reg_pp0_iter1_p_read1026_phi_reg_582;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read1127_phi_reg_594 <= p_read1127_phi_reg_594;
        end else if ((1'b1 == 1'b1)) begin
            p_read1127_phi_reg_594 <= ap_phi_reg_pp0_iter1_p_read1127_phi_reg_594;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read117_phi_reg_474 <= p_read117_phi_reg_474;
        end else if ((1'b1 == 1'b1)) begin
            p_read117_phi_reg_474 <= ap_phi_reg_pp0_iter1_p_read117_phi_reg_474;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read1228_phi_reg_606 <= p_read1228_phi_reg_606;
        end else if ((1'b1 == 1'b1)) begin
            p_read1228_phi_reg_606 <= ap_phi_reg_pp0_iter1_p_read1228_phi_reg_606;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read1329_phi_reg_618 <= p_read1329_phi_reg_618;
        end else if ((1'b1 == 1'b1)) begin
            p_read1329_phi_reg_618 <= ap_phi_reg_pp0_iter1_p_read1329_phi_reg_618;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read1430_phi_reg_630 <= p_read1430_phi_reg_630;
        end else if ((1'b1 == 1'b1)) begin
            p_read1430_phi_reg_630 <= ap_phi_reg_pp0_iter1_p_read1430_phi_reg_630;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read1531_phi_reg_642 <= p_read1531_phi_reg_642;
        end else if ((1'b1 == 1'b1)) begin
            p_read1531_phi_reg_642 <= ap_phi_reg_pp0_iter1_p_read1531_phi_reg_642;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read16_phi_reg_462 <= p_read16_phi_reg_462;
        end else if ((1'b1 == 1'b1)) begin
            p_read16_phi_reg_462 <= ap_phi_reg_pp0_iter1_p_read16_phi_reg_462;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read218_phi_reg_486 <= p_read218_phi_reg_486;
        end else if ((1'b1 == 1'b1)) begin
            p_read218_phi_reg_486 <= ap_phi_reg_pp0_iter1_p_read218_phi_reg_486;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read319_phi_reg_498 <= p_read319_phi_reg_498;
        end else if ((1'b1 == 1'b1)) begin
            p_read319_phi_reg_498 <= ap_phi_reg_pp0_iter1_p_read319_phi_reg_498;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read420_phi_reg_510 <= p_read420_phi_reg_510;
        end else if ((1'b1 == 1'b1)) begin
            p_read420_phi_reg_510 <= ap_phi_reg_pp0_iter1_p_read420_phi_reg_510;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read521_phi_reg_522 <= p_read521_phi_reg_522;
        end else if ((1'b1 == 1'b1)) begin
            p_read521_phi_reg_522 <= ap_phi_reg_pp0_iter1_p_read521_phi_reg_522;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read622_phi_reg_534 <= p_read622_phi_reg_534;
        end else if ((1'b1 == 1'b1)) begin
            p_read622_phi_reg_534 <= ap_phi_reg_pp0_iter1_p_read622_phi_reg_534;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read723_phi_reg_546 <= p_read723_phi_reg_546;
        end else if ((1'b1 == 1'b1)) begin
            p_read723_phi_reg_546 <= ap_phi_reg_pp0_iter1_p_read723_phi_reg_546;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read824_phi_reg_558 <= p_read824_phi_reg_558;
        end else if ((1'b1 == 1'b1)) begin
            p_read824_phi_reg_558 <= ap_phi_reg_pp0_iter1_p_read824_phi_reg_558;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_210)) begin
        if ((do_init_reg_209 == 1'd0)) begin
            p_read925_phi_reg_570 <= p_read925_phi_reg_570;
        end else if ((1'b1 == 1'b1)) begin
            p_read925_phi_reg_570 <= ap_phi_reg_pp0_iter1_p_read925_phi_reg_570;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_ln55_reg_224 <= in_index_reg_938;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        phi_ln55_reg_224 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((icmp_ln42_reg_943_pp0_iter2_reg == 1'd1)) begin
            res_010_reg_654 <= 15'd0;
        end else if ((icmp_ln42_reg_943_pp0_iter2_reg == 1'd0)) begin
            res_010_reg_654 <= add_ln53_1_fu_838_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_reg_957 <= a_1_fu_738_p19;
        a_reg_947 <= a_fu_698_p19;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        icmp_ln42_reg_943 <= icmp_ln42_fu_692_p2;
        icmp_ln42_reg_943_pp0_iter1_reg <= icmp_ln42_reg_943;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_init_pp0_iter3_reg <= ap_loop_init_pp0_iter2_reg;
        icmp_ln42_reg_943_pp0_iter2_reg <= icmp_ln42_reg_943_pp0_iter1_reg;
        trunc_ln1_reg_967 <= {{mul_ln73_fu_784_p2[13:3]}};
        trunc_ln53_1_reg_972 <= {{mul_ln73_1_fu_806_p2[13:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_reg_938 <= in_index_fu_686_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_1_reg_962 <= w23_q0;
        w_reg_952 <= w23_q1;
    end
end

always @ (*) begin
    if (((icmp_ln42_fu_692_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_do_init_phi_fu_212_p6 = 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_do_init_phi_fu_212_p6 = 1'd1;
    end else begin
        ap_phi_mux_do_init_phi_fu_212_p6 = do_init_reg_209;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read1026_phi_phi_fu_586_p4 = p_read1026_phi_reg_582;
    end else begin
        ap_phi_mux_p_read1026_phi_phi_fu_586_p4 = ap_phi_reg_pp0_iter1_p_read1026_phi_reg_582;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read1127_phi_phi_fu_598_p4 = p_read1127_phi_reg_594;
    end else begin
        ap_phi_mux_p_read1127_phi_phi_fu_598_p4 = ap_phi_reg_pp0_iter1_p_read1127_phi_reg_594;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read117_phi_phi_fu_478_p4 = p_read117_phi_reg_474;
    end else begin
        ap_phi_mux_p_read117_phi_phi_fu_478_p4 = ap_phi_reg_pp0_iter1_p_read117_phi_reg_474;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read1228_phi_phi_fu_610_p4 = p_read1228_phi_reg_606;
    end else begin
        ap_phi_mux_p_read1228_phi_phi_fu_610_p4 = ap_phi_reg_pp0_iter1_p_read1228_phi_reg_606;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read1329_phi_phi_fu_622_p4 = p_read1329_phi_reg_618;
    end else begin
        ap_phi_mux_p_read1329_phi_phi_fu_622_p4 = ap_phi_reg_pp0_iter1_p_read1329_phi_reg_618;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read1430_phi_phi_fu_634_p4 = p_read1430_phi_reg_630;
    end else begin
        ap_phi_mux_p_read1430_phi_phi_fu_634_p4 = ap_phi_reg_pp0_iter1_p_read1430_phi_reg_630;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read1531_phi_phi_fu_646_p4 = p_read1531_phi_reg_642;
    end else begin
        ap_phi_mux_p_read1531_phi_phi_fu_646_p4 = ap_phi_reg_pp0_iter1_p_read1531_phi_reg_642;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read16_phi_phi_fu_466_p4 = p_read16_phi_reg_462;
    end else begin
        ap_phi_mux_p_read16_phi_phi_fu_466_p4 = ap_phi_reg_pp0_iter1_p_read16_phi_reg_462;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read218_phi_phi_fu_490_p4 = p_read218_phi_reg_486;
    end else begin
        ap_phi_mux_p_read218_phi_phi_fu_490_p4 = ap_phi_reg_pp0_iter1_p_read218_phi_reg_486;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read319_phi_phi_fu_502_p4 = p_read319_phi_reg_498;
    end else begin
        ap_phi_mux_p_read319_phi_phi_fu_502_p4 = ap_phi_reg_pp0_iter1_p_read319_phi_reg_498;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read420_phi_phi_fu_514_p4 = p_read420_phi_reg_510;
    end else begin
        ap_phi_mux_p_read420_phi_phi_fu_514_p4 = ap_phi_reg_pp0_iter1_p_read420_phi_reg_510;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read521_phi_phi_fu_526_p4 = p_read521_phi_reg_522;
    end else begin
        ap_phi_mux_p_read521_phi_phi_fu_526_p4 = ap_phi_reg_pp0_iter1_p_read521_phi_reg_522;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read622_phi_phi_fu_538_p4 = p_read622_phi_reg_534;
    end else begin
        ap_phi_mux_p_read622_phi_phi_fu_538_p4 = ap_phi_reg_pp0_iter1_p_read622_phi_reg_534;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read723_phi_phi_fu_550_p4 = p_read723_phi_reg_546;
    end else begin
        ap_phi_mux_p_read723_phi_phi_fu_550_p4 = ap_phi_reg_pp0_iter1_p_read723_phi_reg_546;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read824_phi_phi_fu_562_p4 = p_read824_phi_reg_558;
    end else begin
        ap_phi_mux_p_read824_phi_phi_fu_562_p4 = ap_phi_reg_pp0_iter1_p_read824_phi_reg_558;
    end
end

always @ (*) begin
    if ((do_init_reg_209 == 1'd0)) begin
        ap_phi_mux_p_read925_phi_phi_fu_574_p4 = p_read925_phi_reg_570;
    end else begin
        ap_phi_mux_p_read925_phi_phi_fu_574_p4 = ap_phi_reg_pp0_iter1_p_read925_phi_reg_570;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_phi_ln55_phi_fu_227_p6 = in_index_reg_938;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_943 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_phi_ln55_phi_fu_227_p6 = 3'd0;
    end else begin
        ap_phi_mux_phi_ln55_phi_fu_227_p6 = phi_ln55_reg_224;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter3_reg == 1'b1)) begin
        ap_phi_mux_res_010_phi_fu_658_p6 = 15'd0;
    end else begin
        ap_phi_mux_res_010_phi_fu_658_p6 = res_010_reg_654;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_reg_943_pp0_iter2_reg == 1'd1))) begin
        ap_return = add_ln53_1_fu_838_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w23_ce0_local = 1'b1;
    end else begin
        w23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w23_ce1_local = 1'b1;
    end else begin
        w23_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_1_fu_738_p17 = 'bx;

assign a_fu_698_p17 = 'bx;

assign add_ln53_1_fu_838_p2 = ($signed(ap_phi_mux_res_010_phi_fu_658_p6) + $signed(sext_ln53_1_fu_834_p1));

assign add_ln53_fu_828_p2 = ($signed(sext_ln53_fu_825_p1) + $signed(trunc_ln53_cast_fu_822_p1));

assign add_ln55_cast_cast_cast_fu_681_p1 = add_ln55_cast_cast_fu_673_p3;

assign add_ln55_cast_cast_fu_673_p3 = {{1'd1}, {ap_phi_mux_phi_ln55_phi_fu_227_p6}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_199 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_210 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_p_read1026_phi_reg_582 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1127_phi_reg_594 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read117_phi_reg_474 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1228_phi_reg_606 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1329_phi_reg_618 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1430_phi_reg_630 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1531_phi_reg_642 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read16_phi_reg_462 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read218_phi_reg_486 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read319_phi_reg_498 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read420_phi_reg_510 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read521_phi_reg_522 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read622_phi_reg_534 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read723_phi_reg_546 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read824_phi_reg_558 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read925_phi_reg_570 = 'bx;

assign ap_ready = ap_ready_sig;

assign icmp_ln42_fu_692_p2 = ((ap_phi_mux_phi_ln55_phi_fu_227_p6 == 3'd7) ? 1'b1 : 1'b0);

assign in_index_fu_686_p2 = (ap_phi_mux_phi_ln55_phi_fu_227_p6 + 3'd1);

assign mul_ln73_1_fu_806_p0 = mul_ln73_1_fu_806_p00;

assign mul_ln73_1_fu_806_p00 = a_1_reg_957;

assign mul_ln73_fu_784_p0 = mul_ln73_fu_784_p00;

assign mul_ln73_fu_784_p00 = a_reg_947;

assign sext_ln53_1_fu_834_p1 = $signed(add_ln53_fu_828_p2);

assign sext_ln53_fu_825_p1 = $signed(trunc_ln53_1_reg_972);

assign trunc_ln53_cast_fu_822_p1 = $signed(trunc_ln1_reg_967);

assign w23_address0 = add_ln55_cast_cast_cast_fu_681_p1;

assign w23_address1 = zext_ln42_fu_668_p1;

assign zext_ln42_fu_668_p1 = ap_phi_mux_phi_ln55_phi_fu_227_p6;

endmodule //myproject_dense_resource_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config23_s
