// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;

reg   [15:0] data_5_val_read_reg_9302;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] data_4_val_read_reg_9307;
reg  signed [15:0] data_3_val_read_reg_9313;
reg  signed [15:0] data_3_val_read_reg_9313_pp0_iter1_reg;
reg  signed [15:0] data_3_val_read_reg_9313_pp0_iter2_reg;
reg  signed [15:0] data_2_val_read_reg_9322;
reg  signed [15:0] data_2_val_read_reg_9322_pp0_iter1_reg;
reg  signed [15:0] data_1_val_read_reg_9331;
reg  signed [15:0] data_0_val_read_reg_9337;
wire  signed [25:0] sext_ln70_14_fu_8337_p1;
wire  signed [25:0] sext_ln42_fu_8356_p1;
wire  signed [25:0] sext_ln42_12_fu_8365_p1;
wire  signed [25:0] sext_ln42_14_fu_8378_p1;
wire  signed [25:0] sext_ln42_19_fu_8389_p1;
wire  signed [25:0] sext_ln73_fu_8401_p1;
wire  signed [25:0] sext_ln70_13_fu_8410_p1;
reg   [15:0] trunc_ln42_72_reg_9436;
reg   [15:0] trunc_ln42_73_reg_9441;
reg   [13:0] trunc_ln42_74_reg_9446;
reg   [15:0] trunc_ln42_75_reg_9451;
reg   [15:0] trunc_ln42_76_reg_9456;
reg   [15:0] trunc_ln42_77_reg_9461;
reg   [15:0] trunc_ln42_78_reg_9466;
reg   [15:0] trunc_ln_reg_9471;
reg   [15:0] trunc_ln42_s_reg_9476;
reg   [15:0] trunc_ln42_32_reg_9481;
reg   [15:0] trunc_ln42_33_reg_9486;
reg   [14:0] trunc_ln42_34_reg_9491;
reg   [15:0] trunc_ln42_35_reg_9496;
reg   [15:0] trunc_ln42_36_reg_9501;
reg   [15:0] trunc_ln42_37_reg_9506;
reg   [15:0] trunc_ln42_38_reg_9511;
reg   [15:0] trunc_ln42_39_reg_9516;
reg   [15:0] trunc_ln42_40_reg_9521;
reg   [14:0] trunc_ln42_41_reg_9526;
reg   [15:0] trunc_ln42_42_reg_9531;
reg   [15:0] trunc_ln42_43_reg_9536;
reg   [15:0] trunc_ln42_44_reg_9541;
reg   [15:0] trunc_ln42_45_reg_9546;
reg   [13:0] trunc_ln42_46_reg_9551;
reg   [15:0] trunc_ln42_47_reg_9556;
reg   [15:0] trunc_ln42_48_reg_9561;
reg   [15:0] trunc_ln42_49_reg_9566;
reg   [15:0] trunc_ln42_50_reg_9571;
reg   [15:0] trunc_ln42_51_reg_9576;
reg   [15:0] trunc_ln42_52_reg_9581;
reg   [15:0] trunc_ln42_54_reg_9586;
reg   [15:0] trunc_ln42_56_reg_9591;
reg   [15:0] trunc_ln42_57_reg_9596;
reg   [15:0] trunc_ln42_58_reg_9601;
reg   [15:0] trunc_ln42_59_reg_9606;
reg   [15:0] trunc_ln42_60_reg_9611;
reg   [15:0] trunc_ln42_61_reg_9616;
reg   [13:0] trunc_ln42_62_reg_9621;
reg   [15:0] trunc_ln42_63_reg_9626;
reg   [15:0] trunc_ln42_64_reg_9631;
reg   [15:0] trunc_ln42_65_reg_9636;
reg   [15:0] trunc_ln42_66_reg_9641;
reg   [15:0] trunc_ln42_67_reg_9646;
reg   [15:0] trunc_ln42_68_reg_9651;
reg   [15:0] trunc_ln42_69_reg_9656;
reg   [15:0] trunc_ln42_70_reg_9661;
reg   [15:0] trunc_ln42_71_reg_9666;
wire   [15:0] add_ln58_37_fu_8944_p2;
reg   [15:0] add_ln58_37_reg_9671;
wire   [15:0] add_ln58_44_fu_8949_p2;
reg   [15:0] add_ln58_44_reg_9676;
wire   [14:0] add_ln58_51_fu_8954_p2;
reg   [14:0] add_ln58_51_reg_9681;
wire   [15:0] add_ln58_58_fu_8960_p2;
reg   [15:0] add_ln58_58_reg_9686;
wire   [15:0] add_ln58_65_fu_8965_p2;
reg   [15:0] add_ln58_65_reg_9691;
wire   [15:0] add_ln58_72_fu_8970_p2;
reg   [15:0] add_ln58_72_reg_9696;
wire   [15:0] add_ln58_79_fu_8975_p2;
reg   [15:0] add_ln58_79_reg_9701;
wire   [15:0] add_ln58_fu_9068_p2;
reg   [15:0] add_ln58_reg_9706;
wire   [15:0] add_ln58_34_fu_9072_p2;
reg   [15:0] add_ln58_34_reg_9711;
wire   [15:0] add_ln58_38_fu_9080_p2;
reg   [15:0] add_ln58_38_reg_9716;
wire   [15:0] add_ln58_40_fu_9085_p2;
reg   [15:0] add_ln58_40_reg_9721;
wire   [15:0] add_ln58_41_fu_9089_p2;
reg   [15:0] add_ln58_41_reg_9726;
wire   [15:0] add_ln58_45_fu_9097_p2;
reg   [15:0] add_ln58_45_reg_9731;
wire   [15:0] add_ln58_47_fu_9102_p2;
reg   [15:0] add_ln58_47_reg_9736;
wire   [15:0] add_ln58_48_fu_9106_p2;
reg   [15:0] add_ln58_48_reg_9741;
wire   [15:0] add_ln58_52_fu_9119_p2;
reg   [15:0] add_ln58_52_reg_9746;
wire   [15:0] add_ln58_54_fu_9125_p2;
reg   [15:0] add_ln58_54_reg_9751;
wire   [15:0] add_ln58_55_fu_9129_p2;
reg   [15:0] add_ln58_55_reg_9756;
wire   [15:0] add_ln58_59_fu_9137_p2;
reg   [15:0] add_ln58_59_reg_9761;
wire   [15:0] add_ln58_61_fu_9142_p2;
reg   [15:0] add_ln58_61_reg_9766;
wire   [15:0] add_ln58_62_fu_9148_p2;
reg   [15:0] add_ln58_62_reg_9771;
wire   [15:0] add_ln58_66_fu_9158_p2;
reg   [15:0] add_ln58_66_reg_9776;
wire   [15:0] add_ln58_68_fu_9163_p2;
reg   [15:0] add_ln58_68_reg_9781;
wire   [15:0] add_ln58_69_fu_9167_p2;
reg   [15:0] add_ln58_69_reg_9786;
wire   [15:0] add_ln58_73_fu_9175_p2;
reg   [15:0] add_ln58_73_reg_9791;
wire   [15:0] add_ln58_75_fu_9180_p2;
reg   [15:0] add_ln58_75_reg_9796;
wire   [15:0] add_ln58_76_fu_9184_p2;
reg   [15:0] add_ln58_76_reg_9801;
wire   [15:0] add_ln58_80_fu_9192_p2;
reg   [15:0] add_ln58_80_reg_9806;
wire  signed [15:0] grp_fu_216_p0;
wire   [10:0] grp_fu_216_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] grp_fu_217_p0;
wire   [13:0] grp_fu_217_p1;
wire  signed [15:0] grp_fu_218_p0;
wire   [12:0] grp_fu_218_p1;
wire   [7:0] grp_fu_219_p1;
wire   [7:0] grp_fu_220_p1;
wire  signed [15:0] grp_fu_221_p0;
wire  signed [11:0] grp_fu_221_p1;
wire  signed [15:0] grp_fu_222_p0;
wire   [11:0] grp_fu_222_p1;
wire  signed [15:0] grp_fu_223_p0;
wire   [11:0] grp_fu_223_p1;
wire  signed [15:0] grp_fu_224_p0;
wire  signed [11:0] grp_fu_224_p1;
wire  signed [8:0] grp_fu_225_p1;
wire  signed [15:0] grp_fu_226_p0;
wire  signed [11:0] grp_fu_226_p1;
wire  signed [15:0] grp_fu_227_p0;
wire  signed [11:0] grp_fu_227_p1;
wire  signed [15:0] grp_fu_228_p0;
wire   [12:0] grp_fu_228_p1;
wire  signed [15:0] grp_fu_229_p0;
wire  signed [9:0] grp_fu_229_p1;
wire  signed [15:0] grp_fu_230_p0;
wire  signed [12:0] grp_fu_230_p1;
wire  signed [15:0] grp_fu_232_p0;
wire   [10:0] grp_fu_232_p1;
wire  signed [15:0] grp_fu_233_p0;
wire   [12:0] grp_fu_233_p1;
wire  signed [15:0] grp_fu_234_p0;
wire   [10:0] grp_fu_234_p1;
wire  signed [15:0] grp_fu_235_p0;
wire  signed [10:0] grp_fu_235_p1;
wire  signed [15:0] grp_fu_236_p0;
wire   [10:0] grp_fu_236_p1;
wire  signed [15:0] grp_fu_237_p0;
wire  signed [12:0] grp_fu_237_p1;
wire  signed [15:0] grp_fu_238_p0;
wire   [11:0] grp_fu_238_p1;
wire  signed [15:0] grp_fu_239_p0;
wire  signed [9:0] grp_fu_239_p1;
wire  signed [8:0] grp_fu_240_p1;
wire  signed [15:0] grp_fu_241_p0;
wire  signed [11:0] grp_fu_241_p1;
wire  signed [15:0] grp_fu_242_p0;
wire  signed [12:0] grp_fu_242_p1;
wire  signed [15:0] grp_fu_243_p0;
wire  signed [9:0] grp_fu_243_p1;
wire  signed [15:0] grp_fu_244_p0;
wire   [13:0] grp_fu_244_p1;
wire  signed [15:0] grp_fu_245_p0;
wire  signed [10:0] grp_fu_245_p1;
wire  signed [15:0] grp_fu_246_p0;
wire  signed [12:0] grp_fu_246_p1;
wire  signed [15:0] grp_fu_247_p0;
wire   [11:0] grp_fu_247_p1;
wire  signed [15:0] grp_fu_248_p0;
wire   [11:0] grp_fu_248_p1;
wire  signed [15:0] grp_fu_250_p0;
wire   [11:0] grp_fu_250_p1;
wire  signed [15:0] grp_fu_251_p0;
wire  signed [10:0] grp_fu_251_p1;
wire  signed [15:0] grp_fu_252_p0;
wire  signed [12:0] grp_fu_252_p1;
wire  signed [15:0] grp_fu_253_p0;
wire  signed [11:0] grp_fu_253_p1;
wire   [7:0] grp_fu_256_p1;
wire  signed [15:0] grp_fu_257_p0;
wire  signed [9:0] grp_fu_257_p1;
wire  signed [15:0] grp_fu_258_p0;
wire  signed [12:0] grp_fu_258_p1;
wire  signed [15:0] grp_fu_259_p0;
wire   [11:0] grp_fu_259_p1;
wire  signed [15:0] grp_fu_260_p0;
wire   [11:0] grp_fu_260_p1;
wire  signed [15:0] grp_fu_261_p0;
wire   [13:0] grp_fu_261_p1;
wire  signed [15:0] grp_fu_262_p0;
wire  signed [11:0] grp_fu_262_p1;
wire  signed [15:0] grp_fu_263_p0;
wire  signed [12:0] grp_fu_263_p1;
wire  signed [15:0] grp_fu_264_p0;
wire   [12:0] grp_fu_264_p1;
wire  signed [15:0] sext_ln70_14_fu_8337_p0;
wire   [25:0] grp_fu_222_p2;
wire   [25:0] grp_fu_236_p2;
wire   [23:0] grp_fu_219_p2;
wire   [25:0] grp_fu_243_p2;
wire   [25:0] grp_fu_251_p2;
wire   [25:0] grp_fu_235_p2;
wire   [25:0] grp_fu_226_p2;
wire   [25:0] grp_fu_253_p2;
wire   [25:0] grp_fu_241_p2;
wire   [25:0] grp_fu_217_p2;
wire   [25:0] grp_fu_264_p2;
wire   [24:0] grp_fu_240_p2;
wire   [25:0] grp_fu_228_p2;
wire   [25:0] grp_fu_263_p2;
wire   [25:0] grp_fu_260_p2;
wire   [25:0] grp_fu_247_p2;
wire   [25:0] grp_fu_224_p2;
wire   [25:0] grp_fu_229_p2;
wire   [24:0] grp_fu_225_p2;
wire   [25:0] grp_fu_239_p2;
wire   [25:0] grp_fu_232_p2;
wire   [25:0] grp_fu_237_p2;
wire   [25:0] grp_fu_242_p2;
wire   [23:0] grp_fu_256_p2;
wire   [25:0] grp_fu_223_p2;
wire   [25:0] grp_fu_245_p2;
wire   [24:0] tmp_fu_8680_p3;
wire   [21:0] tmp_14_fu_8691_p3;
wire  signed [25:0] sext_ln42_16_fu_8687_p1;
wire  signed [25:0] sext_ln42_17_fu_8698_p1;
wire   [25:0] add_ln42_fu_8702_p2;
wire   [19:0] tmp_15_fu_8724_p3;
wire   [25:0] sub_ln42_fu_8718_p2;
wire  signed [25:0] sext_ln42_18_fu_8731_p1;
wire   [25:0] sub_ln42_1_fu_8735_p2;
wire   [25:0] grp_fu_252_p2;
wire   [25:0] grp_fu_221_p2;
wire   [25:0] grp_fu_216_p2;
wire   [25:0] grp_fu_234_p2;
wire   [25:0] grp_fu_246_p2;
wire   [25:0] grp_fu_227_p2;
wire   [25:0] grp_fu_262_p2;
wire   [25:0] grp_fu_259_p2;
wire   [25:0] grp_fu_250_p2;
wire   [23:0] grp_fu_220_p2;
wire   [25:0] grp_fu_248_p2;
wire   [25:0] grp_fu_238_p2;
wire   [25:0] grp_fu_230_p2;
wire   [25:0] grp_fu_258_p2;
wire   [25:0] grp_fu_261_p2;
wire   [25:0] grp_fu_233_p2;
wire   [25:0] grp_fu_257_p2;
wire   [25:0] grp_fu_218_p2;
wire   [25:0] grp_fu_244_p2;
wire  signed [14:0] sext_ln73_22_fu_8941_p1;
wire   [23:0] tmp_16_fu_8992_p3;
wire  signed [24:0] sext_ln70_11_fu_8989_p1;
wire  signed [24:0] sext_ln73_19_fu_8999_p1;
wire   [24:0] sub_ln73_fu_9003_p2;
wire   [14:0] trunc_ln42_53_fu_9009_p4;
wire   [22:0] tmp_17_fu_9023_p3;
wire   [16:0] tmp_18_fu_9034_p3;
wire  signed [23:0] sext_ln73_21_fu_9041_p1;
wire  signed [23:0] sext_ln73_20_fu_9030_p1;
wire   [23:0] sub_ln73_8_fu_9045_p2;
wire   [13:0] trunc_ln42_55_fu_9051_p4;
wire   [15:0] add_ln58_36_fu_9076_p2;
wire   [15:0] add_ln58_43_fu_9093_p2;
wire  signed [15:0] sext_ln42_15_fu_8986_p1;
wire  signed [15:0] sext_ln42_20_fu_9019_p1;
wire  signed [15:0] sext_ln58_fu_9116_p1;
wire   [15:0] add_ln58_50_fu_9112_p2;
wire   [15:0] add_ln58_57_fu_9133_p2;
wire  signed [15:0] sext_ln42_11_fu_8980_p1;
wire  signed [15:0] sext_ln42_13_fu_8983_p1;
wire  signed [15:0] sext_ln42_21_fu_9061_p1;
wire  signed [15:0] sext_ln42_22_fu_9065_p1;
wire   [15:0] add_ln58_64_fu_9153_p2;
wire   [15:0] add_ln58_71_fu_9171_p2;
wire   [15:0] add_ln58_78_fu_9188_p2;
wire   [15:0] add_ln58_35_fu_9197_p2;
wire   [15:0] add_ln58_42_fu_9206_p2;
wire   [15:0] add_ln58_49_fu_9215_p2;
wire   [15:0] add_ln58_56_fu_9224_p2;
wire   [15:0] add_ln58_63_fu_9233_p2;
wire   [15:0] add_ln58_70_fu_9242_p2;
wire   [15:0] add_ln58_77_fu_9251_p2;
wire   [15:0] add_ln58_39_fu_9201_p2;
wire   [15:0] add_ln58_46_fu_9210_p2;
wire   [15:0] add_ln58_53_fu_9219_p2;
wire   [15:0] add_ln58_60_fu_9228_p2;
wire   [15:0] add_ln58_67_fu_9237_p2;
wire   [15:0] add_ln58_74_fu_9246_p2;
wire   [15:0] add_ln58_81_fu_9255_p2;
reg    grp_fu_216_ce;
reg    grp_fu_217_ce;
reg    grp_fu_218_ce;
reg    grp_fu_219_ce;
reg    grp_fu_220_ce;
reg    grp_fu_221_ce;
reg    grp_fu_222_ce;
reg    grp_fu_223_ce;
reg    grp_fu_224_ce;
reg    grp_fu_225_ce;
reg    grp_fu_226_ce;
reg    grp_fu_227_ce;
reg    grp_fu_228_ce;
reg    grp_fu_229_ce;
reg    grp_fu_230_ce;
reg    grp_fu_232_ce;
reg    grp_fu_233_ce;
reg    grp_fu_234_ce;
reg    grp_fu_235_ce;
reg    grp_fu_236_ce;
reg    grp_fu_237_ce;
reg    grp_fu_238_ce;
reg    grp_fu_239_ce;
reg    grp_fu_240_ce;
reg    grp_fu_241_ce;
reg    grp_fu_242_ce;
reg    grp_fu_243_ce;
reg    grp_fu_244_ce;
reg    grp_fu_245_ce;
reg    grp_fu_246_ce;
reg    grp_fu_247_ce;
reg    grp_fu_248_ce;
reg    grp_fu_250_ce;
reg    grp_fu_251_ce;
reg    grp_fu_252_ce;
reg    grp_fu_253_ce;
reg    grp_fu_256_ce;
reg    grp_fu_257_ce;
reg    grp_fu_258_ce;
reg    grp_fu_259_ce;
reg    grp_fu_260_ce;
reg    grp_fu_261_ce;
reg    grp_fu_262_ce;
reg    grp_fu_263_ce;
reg    grp_fu_264_ce;
reg    ap_ce_reg;
reg   [15:0] data_0_val_int_reg;
reg   [15:0] data_1_val_int_reg;
reg   [15:0] data_2_val_int_reg;
reg   [15:0] data_3_val_int_reg;
reg   [15:0] data_4_val_int_reg;
reg   [15:0] data_5_val_int_reg;
reg  signed [15:0] data_6_val_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_216_p0),
    .din1(grp_fu_216_p1),
    .ce(grp_fu_216_ce),
    .dout(grp_fu_216_p2)
);

myproject_mul_16s_14ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 26 ))
mul_16s_14ns_26_2_0_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_217_p0),
    .din1(grp_fu_217_p1),
    .ce(grp_fu_217_ce),
    .dout(grp_fu_217_p2)
);

myproject_mul_16s_13ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13ns_26_2_0_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_218_p0),
    .din1(grp_fu_218_p1),
    .ce(grp_fu_218_ce),
    .dout(grp_fu_218_p2)
);

myproject_mul_16s_8ns_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_0_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_6_val_int_reg),
    .din1(grp_fu_219_p1),
    .ce(grp_fu_219_ce),
    .dout(grp_fu_219_p2)
);

myproject_mul_16s_8ns_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_0_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_4_val_read_reg_9307),
    .din1(grp_fu_220_p1),
    .ce(grp_fu_220_ce),
    .dout(grp_fu_220_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_221_p0),
    .din1(grp_fu_221_p1),
    .ce(grp_fu_221_ce),
    .dout(grp_fu_221_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_222_p0),
    .din1(grp_fu_222_p1),
    .ce(grp_fu_222_ce),
    .dout(grp_fu_222_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_223_p0),
    .din1(grp_fu_223_p1),
    .ce(grp_fu_223_ce),
    .dout(grp_fu_223_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .din1(grp_fu_224_p1),
    .ce(grp_fu_224_ce),
    .dout(grp_fu_224_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_1_val_read_reg_9331),
    .din1(grp_fu_225_p1),
    .ce(grp_fu_225_ce),
    .dout(grp_fu_225_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_226_p0),
    .din1(grp_fu_226_p1),
    .ce(grp_fu_226_ce),
    .dout(grp_fu_226_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_227_p0),
    .din1(grp_fu_227_p1),
    .ce(grp_fu_227_ce),
    .dout(grp_fu_227_p2)
);

myproject_mul_16s_13ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13ns_26_2_0_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_228_p0),
    .din1(grp_fu_228_p1),
    .ce(grp_fu_228_ce),
    .dout(grp_fu_228_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_229_p0),
    .din1(grp_fu_229_p1),
    .ce(grp_fu_229_ce),
    .dout(grp_fu_229_p2)
);

myproject_mul_16s_13s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_2_0_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_230_p0),
    .din1(grp_fu_230_p1),
    .ce(grp_fu_230_ce),
    .dout(grp_fu_230_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_232_p0),
    .din1(grp_fu_232_p1),
    .ce(grp_fu_232_ce),
    .dout(grp_fu_232_p2)
);

myproject_mul_16s_13ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13ns_26_2_0_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_233_p0),
    .din1(grp_fu_233_p1),
    .ce(grp_fu_233_ce),
    .dout(grp_fu_233_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_234_p0),
    .din1(grp_fu_234_p1),
    .ce(grp_fu_234_ce),
    .dout(grp_fu_234_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_235_p0),
    .din1(grp_fu_235_p1),
    .ce(grp_fu_235_ce),
    .dout(grp_fu_235_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_0_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_236_p0),
    .din1(grp_fu_236_p1),
    .ce(grp_fu_236_ce),
    .dout(grp_fu_236_p2)
);

myproject_mul_16s_13s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_2_0_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_237_p0),
    .din1(grp_fu_237_p1),
    .ce(grp_fu_237_ce),
    .dout(grp_fu_237_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_238_p0),
    .din1(grp_fu_238_p1),
    .ce(grp_fu_238_ce),
    .dout(grp_fu_238_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_239_p0),
    .din1(grp_fu_239_p1),
    .ce(grp_fu_239_ce),
    .dout(grp_fu_239_p2)
);

myproject_mul_16s_9s_25_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_0_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_0_val_read_reg_9337),
    .din1(grp_fu_240_p1),
    .ce(grp_fu_240_ce),
    .dout(grp_fu_240_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_241_p0),
    .din1(grp_fu_241_p1),
    .ce(grp_fu_241_ce),
    .dout(grp_fu_241_p2)
);

myproject_mul_16s_13s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_2_0_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_242_p0),
    .din1(grp_fu_242_p1),
    .ce(grp_fu_242_ce),
    .dout(grp_fu_242_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_243_p0),
    .din1(grp_fu_243_p1),
    .ce(grp_fu_243_ce),
    .dout(grp_fu_243_p2)
);

myproject_mul_16s_14ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 26 ))
mul_16s_14ns_26_2_0_U77(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_244_p0),
    .din1(grp_fu_244_p1),
    .ce(grp_fu_244_ce),
    .dout(grp_fu_244_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_245_p0),
    .din1(grp_fu_245_p1),
    .ce(grp_fu_245_ce),
    .dout(grp_fu_245_p2)
);

myproject_mul_16s_13s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_2_0_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_246_p0),
    .din1(grp_fu_246_p1),
    .ce(grp_fu_246_ce),
    .dout(grp_fu_246_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U80(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_247_p0),
    .din1(grp_fu_247_p1),
    .ce(grp_fu_247_ce),
    .dout(grp_fu_247_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_248_p0),
    .din1(grp_fu_248_p1),
    .ce(grp_fu_248_ce),
    .dout(grp_fu_248_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_250_p0),
    .din1(grp_fu_250_p1),
    .ce(grp_fu_250_ce),
    .dout(grp_fu_250_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_0_U83(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_251_p0),
    .din1(grp_fu_251_p1),
    .ce(grp_fu_251_ce),
    .dout(grp_fu_251_p2)
);

myproject_mul_16s_13s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_2_0_U84(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_252_p0),
    .din1(grp_fu_252_p1),
    .ce(grp_fu_252_ce),
    .dout(grp_fu_252_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U85(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_253_p0),
    .din1(grp_fu_253_p1),
    .ce(grp_fu_253_ce),
    .dout(grp_fu_253_p2)
);

myproject_mul_16s_8ns_24_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_0_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_2_val_read_reg_9322),
    .din1(grp_fu_256_p1),
    .ce(grp_fu_256_ce),
    .dout(grp_fu_256_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_0_U87(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_257_p0),
    .din1(grp_fu_257_p1),
    .ce(grp_fu_257_ce),
    .dout(grp_fu_257_p2)
);

myproject_mul_16s_13s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_2_0_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_258_p0),
    .din1(grp_fu_258_p1),
    .ce(grp_fu_258_ce),
    .dout(grp_fu_258_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_259_p0),
    .din1(grp_fu_259_p1),
    .ce(grp_fu_259_ce),
    .dout(grp_fu_259_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_0_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_260_p0),
    .din1(grp_fu_260_p1),
    .ce(grp_fu_260_ce),
    .dout(grp_fu_260_p2)
);

myproject_mul_16s_14ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 26 ))
mul_16s_14ns_26_2_0_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_261_p0),
    .din1(grp_fu_261_p1),
    .ce(grp_fu_261_ce),
    .dout(grp_fu_261_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_0_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_262_p0),
    .din1(grp_fu_262_p1),
    .ce(grp_fu_262_ce),
    .dout(grp_fu_262_p2)
);

myproject_mul_16s_13s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_2_0_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_263_p0),
    .din1(grp_fu_263_p1),
    .ce(grp_fu_263_ce),
    .dout(grp_fu_263_p2)
);

myproject_mul_16s_13ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13ns_26_2_0_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_264_p0),
    .din1(grp_fu_264_p1),
    .ce(grp_fu_264_ce),
    .dout(grp_fu_264_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln58_34_reg_9711 <= add_ln58_34_fu_9072_p2;
        add_ln58_37_reg_9671 <= add_ln58_37_fu_8944_p2;
        add_ln58_38_reg_9716 <= add_ln58_38_fu_9080_p2;
        add_ln58_40_reg_9721 <= add_ln58_40_fu_9085_p2;
        add_ln58_41_reg_9726 <= add_ln58_41_fu_9089_p2;
        add_ln58_44_reg_9676 <= add_ln58_44_fu_8949_p2;
        add_ln58_45_reg_9731 <= add_ln58_45_fu_9097_p2;
        add_ln58_47_reg_9736 <= add_ln58_47_fu_9102_p2;
        add_ln58_48_reg_9741 <= add_ln58_48_fu_9106_p2;
        add_ln58_51_reg_9681 <= add_ln58_51_fu_8954_p2;
        add_ln58_52_reg_9746 <= add_ln58_52_fu_9119_p2;
        add_ln58_54_reg_9751 <= add_ln58_54_fu_9125_p2;
        add_ln58_55_reg_9756 <= add_ln58_55_fu_9129_p2;
        add_ln58_58_reg_9686 <= add_ln58_58_fu_8960_p2;
        add_ln58_59_reg_9761 <= add_ln58_59_fu_9137_p2;
        add_ln58_61_reg_9766 <= add_ln58_61_fu_9142_p2;
        add_ln58_62_reg_9771 <= add_ln58_62_fu_9148_p2;
        add_ln58_65_reg_9691 <= add_ln58_65_fu_8965_p2;
        add_ln58_66_reg_9776 <= add_ln58_66_fu_9158_p2;
        add_ln58_68_reg_9781 <= add_ln58_68_fu_9163_p2;
        add_ln58_69_reg_9786 <= add_ln58_69_fu_9167_p2;
        add_ln58_72_reg_9696 <= add_ln58_72_fu_8970_p2;
        add_ln58_73_reg_9791 <= add_ln58_73_fu_9175_p2;
        add_ln58_75_reg_9796 <= add_ln58_75_fu_9180_p2;
        add_ln58_76_reg_9801 <= add_ln58_76_fu_9184_p2;
        add_ln58_79_reg_9701 <= add_ln58_79_fu_8975_p2;
        add_ln58_80_reg_9806 <= add_ln58_80_fu_9192_p2;
        add_ln58_reg_9706 <= add_ln58_fu_9068_p2;
        data_0_val_read_reg_9337 <= data_0_val_int_reg;
        data_1_val_read_reg_9331 <= data_1_val_int_reg;
        data_2_val_read_reg_9322 <= data_2_val_int_reg;
        data_2_val_read_reg_9322_pp0_iter1_reg <= data_2_val_read_reg_9322;
        data_3_val_read_reg_9313 <= data_3_val_int_reg;
        data_3_val_read_reg_9313_pp0_iter1_reg <= data_3_val_read_reg_9313;
        data_3_val_read_reg_9313_pp0_iter2_reg <= data_3_val_read_reg_9313_pp0_iter1_reg;
        data_4_val_read_reg_9307 <= data_4_val_int_reg;
        data_5_val_read_reg_9302 <= data_5_val_int_reg;
        trunc_ln42_32_reg_9481 <= {{grp_fu_217_p2[25:10]}};
        trunc_ln42_33_reg_9486 <= {{grp_fu_264_p2[25:10]}};
        trunc_ln42_34_reg_9491 <= {{grp_fu_240_p2[24:10]}};
        trunc_ln42_35_reg_9496 <= {{grp_fu_228_p2[25:10]}};
        trunc_ln42_36_reg_9501 <= {{grp_fu_263_p2[25:10]}};
        trunc_ln42_37_reg_9506 <= {{grp_fu_260_p2[25:10]}};
        trunc_ln42_38_reg_9511 <= {{grp_fu_247_p2[25:10]}};
        trunc_ln42_39_reg_9516 <= {{grp_fu_224_p2[25:10]}};
        trunc_ln42_40_reg_9521 <= {{grp_fu_229_p2[25:10]}};
        trunc_ln42_41_reg_9526 <= {{grp_fu_225_p2[24:10]}};
        trunc_ln42_42_reg_9531 <= {{grp_fu_239_p2[25:10]}};
        trunc_ln42_43_reg_9536 <= {{grp_fu_232_p2[25:10]}};
        trunc_ln42_44_reg_9541 <= {{grp_fu_237_p2[25:10]}};
        trunc_ln42_45_reg_9546 <= {{grp_fu_242_p2[25:10]}};
        trunc_ln42_46_reg_9551 <= {{grp_fu_256_p2[23:10]}};
        trunc_ln42_47_reg_9556 <= {{grp_fu_223_p2[25:10]}};
        trunc_ln42_48_reg_9561 <= {{grp_fu_245_p2[25:10]}};
        trunc_ln42_49_reg_9566 <= {{add_ln42_fu_8702_p2[25:10]}};
        trunc_ln42_50_reg_9571 <= {{sub_ln42_1_fu_8735_p2[25:10]}};
        trunc_ln42_51_reg_9576 <= {{grp_fu_252_p2[25:10]}};
        trunc_ln42_52_reg_9581 <= {{grp_fu_221_p2[25:10]}};
        trunc_ln42_54_reg_9586 <= {{grp_fu_216_p2[25:10]}};
        trunc_ln42_56_reg_9591 <= {{grp_fu_234_p2[25:10]}};
        trunc_ln42_57_reg_9596 <= {{grp_fu_246_p2[25:10]}};
        trunc_ln42_58_reg_9601 <= {{grp_fu_227_p2[25:10]}};
        trunc_ln42_59_reg_9606 <= {{grp_fu_262_p2[25:10]}};
        trunc_ln42_60_reg_9611 <= {{grp_fu_259_p2[25:10]}};
        trunc_ln42_61_reg_9616 <= {{grp_fu_250_p2[25:10]}};
        trunc_ln42_62_reg_9621 <= {{grp_fu_220_p2[23:10]}};
        trunc_ln42_63_reg_9626 <= {{grp_fu_248_p2[25:10]}};
        trunc_ln42_64_reg_9631 <= {{grp_fu_238_p2[25:10]}};
        trunc_ln42_65_reg_9636 <= {{grp_fu_230_p2[25:10]}};
        trunc_ln42_66_reg_9641 <= {{grp_fu_258_p2[25:10]}};
        trunc_ln42_67_reg_9646 <= {{grp_fu_261_p2[25:10]}};
        trunc_ln42_68_reg_9651 <= {{grp_fu_233_p2[25:10]}};
        trunc_ln42_69_reg_9656 <= {{grp_fu_257_p2[25:10]}};
        trunc_ln42_70_reg_9661 <= {{grp_fu_218_p2[25:10]}};
        trunc_ln42_71_reg_9666 <= {{grp_fu_244_p2[25:10]}};
        trunc_ln42_72_reg_9436 <= {{grp_fu_222_p2[25:10]}};
        trunc_ln42_73_reg_9441 <= {{grp_fu_236_p2[25:10]}};
        trunc_ln42_74_reg_9446 <= {{grp_fu_219_p2[23:10]}};
        trunc_ln42_75_reg_9451 <= {{grp_fu_243_p2[25:10]}};
        trunc_ln42_76_reg_9456 <= {{grp_fu_251_p2[25:10]}};
        trunc_ln42_77_reg_9461 <= {{grp_fu_235_p2[25:10]}};
        trunc_ln42_78_reg_9466 <= {{grp_fu_226_p2[25:10]}};
        trunc_ln42_s_reg_9476 <= {{grp_fu_241_p2[25:10]}};
        trunc_ln_reg_9471 <= {{grp_fu_253_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln58_39_fu_9201_p2;
        ap_return_1_int_reg <= add_ln58_46_fu_9210_p2;
        ap_return_2_int_reg <= add_ln58_53_fu_9219_p2;
        ap_return_3_int_reg <= add_ln58_60_fu_9228_p2;
        ap_return_4_int_reg <= add_ln58_67_fu_9237_p2;
        ap_return_5_int_reg <= add_ln58_74_fu_9246_p2;
        ap_return_6_int_reg <= add_ln58_81_fu_9255_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_val_int_reg <= data_0_val;
        data_1_val_int_reg <= data_1_val;
        data_2_val_int_reg <= data_2_val;
        data_3_val_int_reg <= data_3_val;
        data_4_val_int_reg <= data_4_val;
        data_5_val_int_reg <= data_5_val;
        data_6_val_int_reg <= data_6_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln58_39_fu_9201_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln58_46_fu_9210_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln58_53_fu_9219_p2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln58_60_fu_9228_p2;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = add_ln58_67_fu_9237_p2;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = add_ln58_74_fu_9246_p2;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = add_ln58_81_fu_9255_p2;
    end else begin
        ap_return_6 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_216_ce = 1'b1;
    end else begin
        grp_fu_216_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_217_ce = 1'b1;
    end else begin
        grp_fu_217_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_218_ce = 1'b1;
    end else begin
        grp_fu_218_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_219_ce = 1'b1;
    end else begin
        grp_fu_219_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_220_ce = 1'b1;
    end else begin
        grp_fu_220_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_221_ce = 1'b1;
    end else begin
        grp_fu_221_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_222_ce = 1'b1;
    end else begin
        grp_fu_222_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_223_ce = 1'b1;
    end else begin
        grp_fu_223_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_224_ce = 1'b1;
    end else begin
        grp_fu_224_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_225_ce = 1'b1;
    end else begin
        grp_fu_225_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_226_ce = 1'b1;
    end else begin
        grp_fu_226_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_227_ce = 1'b1;
    end else begin
        grp_fu_227_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_228_ce = 1'b1;
    end else begin
        grp_fu_228_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_229_ce = 1'b1;
    end else begin
        grp_fu_229_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_230_ce = 1'b1;
    end else begin
        grp_fu_230_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_232_ce = 1'b1;
    end else begin
        grp_fu_232_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_233_ce = 1'b1;
    end else begin
        grp_fu_233_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_234_ce = 1'b1;
    end else begin
        grp_fu_234_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_235_ce = 1'b1;
    end else begin
        grp_fu_235_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_236_ce = 1'b1;
    end else begin
        grp_fu_236_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_237_ce = 1'b1;
    end else begin
        grp_fu_237_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_238_ce = 1'b1;
    end else begin
        grp_fu_238_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_239_ce = 1'b1;
    end else begin
        grp_fu_239_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_240_ce = 1'b1;
    end else begin
        grp_fu_240_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_241_ce = 1'b1;
    end else begin
        grp_fu_241_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_242_ce = 1'b1;
    end else begin
        grp_fu_242_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_243_ce = 1'b1;
    end else begin
        grp_fu_243_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_244_ce = 1'b1;
    end else begin
        grp_fu_244_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_245_ce = 1'b1;
    end else begin
        grp_fu_245_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_246_ce = 1'b1;
    end else begin
        grp_fu_246_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_247_ce = 1'b1;
    end else begin
        grp_fu_247_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_248_ce = 1'b1;
    end else begin
        grp_fu_248_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_250_ce = 1'b1;
    end else begin
        grp_fu_250_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_251_ce = 1'b1;
    end else begin
        grp_fu_251_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_252_ce = 1'b1;
    end else begin
        grp_fu_252_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_253_ce = 1'b1;
    end else begin
        grp_fu_253_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_256_ce = 1'b1;
    end else begin
        grp_fu_256_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_257_ce = 1'b1;
    end else begin
        grp_fu_257_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_258_ce = 1'b1;
    end else begin
        grp_fu_258_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_259_ce = 1'b1;
    end else begin
        grp_fu_259_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_260_ce = 1'b1;
    end else begin
        grp_fu_260_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_261_ce = 1'b1;
    end else begin
        grp_fu_261_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_262_ce = 1'b1;
    end else begin
        grp_fu_262_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_263_ce = 1'b1;
    end else begin
        grp_fu_263_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_264_ce = 1'b1;
    end else begin
        grp_fu_264_ce = 1'b0;
    end
end

assign add_ln42_fu_8702_p2 = ($signed(sext_ln42_16_fu_8687_p1) + $signed(sext_ln42_17_fu_8698_p1));

assign add_ln58_34_fu_9072_p2 = (trunc_ln42_44_reg_9541 + trunc_ln42_51_reg_9576);

assign add_ln58_35_fu_9197_p2 = (add_ln58_34_reg_9711 + add_ln58_reg_9706);

assign add_ln58_36_fu_9076_p2 = (trunc_ln42_58_reg_9601 + trunc_ln42_65_reg_9636);

assign add_ln58_37_fu_8944_p2 = (trunc_ln42_72_reg_9436 + 16'd465);

assign add_ln58_38_fu_9080_p2 = (add_ln58_37_reg_9671 + add_ln58_36_fu_9076_p2);

assign add_ln58_39_fu_9201_p2 = (add_ln58_38_reg_9716 + add_ln58_35_fu_9197_p2);

assign add_ln58_40_fu_9085_p2 = (trunc_ln42_s_reg_9476 + trunc_ln42_38_reg_9511);

assign add_ln58_41_fu_9089_p2 = (trunc_ln42_45_reg_9546 + trunc_ln42_52_reg_9581);

assign add_ln58_42_fu_9206_p2 = (add_ln58_41_reg_9726 + add_ln58_40_reg_9721);

assign add_ln58_43_fu_9093_p2 = (trunc_ln42_59_reg_9606 + trunc_ln42_66_reg_9641);

assign add_ln58_44_fu_8949_p2 = (trunc_ln42_73_reg_9441 + 16'd294);

assign add_ln58_45_fu_9097_p2 = (add_ln58_44_reg_9676 + add_ln58_43_fu_9093_p2);

assign add_ln58_46_fu_9210_p2 = (add_ln58_45_reg_9731 + add_ln58_42_fu_9206_p2);

assign add_ln58_47_fu_9102_p2 = (trunc_ln42_32_reg_9481 + trunc_ln42_39_reg_9516);

assign add_ln58_48_fu_9106_p2 = ($signed(sext_ln42_15_fu_8986_p1) + $signed(sext_ln42_20_fu_9019_p1));

assign add_ln58_49_fu_9215_p2 = (add_ln58_48_reg_9741 + add_ln58_47_reg_9736);

assign add_ln58_50_fu_9112_p2 = (trunc_ln42_60_reg_9611 + trunc_ln42_67_reg_9646);

assign add_ln58_51_fu_8954_p2 = ($signed(sext_ln73_22_fu_8941_p1) + $signed(15'd102));

assign add_ln58_52_fu_9119_p2 = ($signed(sext_ln58_fu_9116_p1) + $signed(add_ln58_50_fu_9112_p2));

assign add_ln58_53_fu_9219_p2 = (add_ln58_52_reg_9746 + add_ln58_49_fu_9215_p2);

assign add_ln58_54_fu_9125_p2 = (trunc_ln42_33_reg_9486 + trunc_ln42_40_reg_9521);

assign add_ln58_55_fu_9129_p2 = (trunc_ln42_47_reg_9556 + trunc_ln42_54_reg_9586);

assign add_ln58_56_fu_9224_p2 = (add_ln58_55_reg_9756 + add_ln58_54_reg_9751);

assign add_ln58_57_fu_9133_p2 = (trunc_ln42_61_reg_9616 + trunc_ln42_68_reg_9651);

assign add_ln58_58_fu_8960_p2 = (trunc_ln42_75_reg_9451 + 16'd608);

assign add_ln58_59_fu_9137_p2 = (add_ln58_58_reg_9686 + add_ln58_57_fu_9133_p2);

assign add_ln58_60_fu_9228_p2 = (add_ln58_59_reg_9761 + add_ln58_56_fu_9224_p2);

assign add_ln58_61_fu_9142_p2 = ($signed(sext_ln42_11_fu_8980_p1) + $signed(sext_ln42_13_fu_8983_p1));

assign add_ln58_62_fu_9148_p2 = ($signed(trunc_ln42_48_reg_9561) + $signed(sext_ln42_21_fu_9061_p1));

assign add_ln58_63_fu_9233_p2 = (add_ln58_62_reg_9771 + add_ln58_61_reg_9766);

assign add_ln58_64_fu_9153_p2 = ($signed(sext_ln42_22_fu_9065_p1) + $signed(trunc_ln42_69_reg_9656));

assign add_ln58_65_fu_8965_p2 = ($signed(trunc_ln42_76_reg_9456) + $signed(16'd65479));

assign add_ln58_66_fu_9158_p2 = (add_ln58_65_reg_9691 + add_ln58_64_fu_9153_p2);

assign add_ln58_67_fu_9237_p2 = (add_ln58_66_reg_9776 + add_ln58_63_fu_9233_p2);

assign add_ln58_68_fu_9163_p2 = (trunc_ln42_35_reg_9496 + trunc_ln42_42_reg_9531);

assign add_ln58_69_fu_9167_p2 = (trunc_ln42_49_reg_9566 + trunc_ln42_56_reg_9591);

assign add_ln58_70_fu_9242_p2 = (add_ln58_69_reg_9786 + add_ln58_68_reg_9781);

assign add_ln58_71_fu_9171_p2 = (trunc_ln42_63_reg_9626 + trunc_ln42_70_reg_9661);

assign add_ln58_72_fu_8970_p2 = (trunc_ln42_77_reg_9461 + 16'd892);

assign add_ln58_73_fu_9175_p2 = (add_ln58_72_reg_9696 + add_ln58_71_fu_9171_p2);

assign add_ln58_74_fu_9246_p2 = (add_ln58_73_reg_9791 + add_ln58_70_fu_9242_p2);

assign add_ln58_75_fu_9180_p2 = (trunc_ln42_36_reg_9501 + trunc_ln42_43_reg_9536);

assign add_ln58_76_fu_9184_p2 = (trunc_ln42_50_reg_9571 + trunc_ln42_57_reg_9596);

assign add_ln58_77_fu_9251_p2 = (add_ln58_76_reg_9801 + add_ln58_75_reg_9796);

assign add_ln58_78_fu_9188_p2 = (trunc_ln42_64_reg_9631 + trunc_ln42_71_reg_9666);

assign add_ln58_79_fu_8975_p2 = (trunc_ln42_78_reg_9466 + 16'd587);

assign add_ln58_80_fu_9192_p2 = (add_ln58_79_reg_9701 + add_ln58_78_fu_9188_p2);

assign add_ln58_81_fu_9255_p2 = (add_ln58_80_reg_9806 + add_ln58_77_fu_9251_p2);

assign add_ln58_fu_9068_p2 = (trunc_ln_reg_9471 + trunc_ln42_37_reg_9506);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign grp_fu_216_p0 = sext_ln42_19_fu_8389_p1;

assign grp_fu_216_p1 = 26'd522;

assign grp_fu_217_p0 = sext_ln42_fu_8356_p1;

assign grp_fu_217_p1 = 26'd4517;

assign grp_fu_218_p0 = sext_ln70_13_fu_8410_p1;

assign grp_fu_218_p1 = 26'd3313;

assign grp_fu_219_p1 = 24'd101;

assign grp_fu_220_p1 = 24'd122;

assign grp_fu_221_p0 = sext_ln42_19_fu_8389_p1;

assign grp_fu_221_p1 = 26'd67107048;

assign grp_fu_222_p0 = sext_ln70_14_fu_8337_p1;

assign grp_fu_222_p1 = 26'd1193;

assign grp_fu_223_p0 = sext_ln42_14_fu_8378_p1;

assign grp_fu_223_p1 = 26'd1308;

assign grp_fu_224_p0 = sext_ln42_12_fu_8365_p1;

assign grp_fu_224_p1 = 26'd67107319;

assign grp_fu_225_p1 = 25'd33554251;

assign grp_fu_226_p0 = sext_ln70_14_fu_8337_p1;

assign grp_fu_226_p1 = 26'd67107789;

assign grp_fu_227_p0 = sext_ln73_fu_8401_p1;

assign grp_fu_227_p1 = 26'd67107646;

assign grp_fu_228_p0 = sext_ln42_fu_8356_p1;

assign grp_fu_228_p1 = 26'd2635;

assign grp_fu_229_p0 = sext_ln42_12_fu_8365_p1;

assign grp_fu_229_p1 = 26'd67108389;

assign grp_fu_230_p0 = sext_ln70_13_fu_8410_p1;

assign grp_fu_230_p1 = 26'd67106353;

assign grp_fu_232_p0 = sext_ln42_12_fu_8365_p1;

assign grp_fu_232_p1 = 26'd860;

assign grp_fu_233_p0 = sext_ln70_13_fu_8410_p1;

assign grp_fu_233_p1 = 26'd3679;

assign grp_fu_234_p0 = sext_ln42_19_fu_8389_p1;

assign grp_fu_234_p1 = 26'd539;

assign grp_fu_235_p0 = sext_ln70_14_fu_8337_p1;

assign grp_fu_235_p1 = 26'd67108170;

assign grp_fu_236_p0 = sext_ln70_14_fu_8337_p1;

assign grp_fu_236_p1 = 26'd968;

assign grp_fu_237_p0 = sext_ln42_14_fu_8378_p1;

assign grp_fu_237_p1 = 26'd67105109;

assign grp_fu_238_p0 = sext_ln73_fu_8401_p1;

assign grp_fu_238_p1 = 26'd1977;

assign grp_fu_239_p0 = sext_ln42_12_fu_8365_p1;

assign grp_fu_239_p1 = 26'd67108482;

assign grp_fu_240_p1 = 25'd33554183;

assign grp_fu_241_p0 = sext_ln42_fu_8356_p1;

assign grp_fu_241_p1 = 26'd67107434;

assign grp_fu_242_p0 = sext_ln42_14_fu_8378_p1;

assign grp_fu_242_p1 = 26'd67105402;

assign grp_fu_243_p0 = sext_ln70_14_fu_8337_p1;

assign grp_fu_243_p1 = 26'd67108364;

assign grp_fu_244_p0 = sext_ln70_13_fu_8410_p1;

assign grp_fu_244_p1 = 26'd4218;

assign grp_fu_245_p0 = sext_ln42_14_fu_8378_p1;

assign grp_fu_245_p1 = 26'd67108327;

assign grp_fu_246_p0 = sext_ln42_19_fu_8389_p1;

assign grp_fu_246_p1 = 26'd67105820;

assign grp_fu_247_p0 = sext_ln42_12_fu_8365_p1;

assign grp_fu_247_p1 = 26'd1382;

assign grp_fu_248_p0 = sext_ln73_fu_8401_p1;

assign grp_fu_248_p1 = 26'd1459;

assign grp_fu_250_p0 = sext_ln73_fu_8401_p1;

assign grp_fu_250_p1 = 26'd1378;

assign grp_fu_251_p0 = sext_ln70_14_fu_8337_p1;

assign grp_fu_251_p1 = 26'd67108205;

assign grp_fu_252_p0 = sext_ln42_19_fu_8389_p1;

assign grp_fu_252_p1 = 26'd67106660;

assign grp_fu_253_p0 = sext_ln42_fu_8356_p1;

assign grp_fu_253_p1 = 26'd67107227;

assign grp_fu_256_p1 = 24'd90;

assign grp_fu_257_p0 = sext_ln70_13_fu_8410_p1;

assign grp_fu_257_p1 = 26'd67108387;

assign grp_fu_258_p0 = sext_ln70_13_fu_8410_p1;

assign grp_fu_258_p1 = 26'd67106530;

assign grp_fu_259_p0 = sext_ln73_fu_8401_p1;

assign grp_fu_259_p1 = 26'd1112;

assign grp_fu_260_p0 = sext_ln42_12_fu_8365_p1;

assign grp_fu_260_p1 = 26'd1308;

assign grp_fu_261_p0 = sext_ln70_13_fu_8410_p1;

assign grp_fu_261_p1 = 26'd4379;

assign grp_fu_262_p0 = sext_ln73_fu_8401_p1;

assign grp_fu_262_p1 = 26'd67107770;

assign grp_fu_263_p0 = sext_ln42_fu_8356_p1;

assign grp_fu_263_p1 = 26'd67106590;

assign grp_fu_264_p0 = sext_ln42_fu_8356_p1;

assign grp_fu_264_p1 = 26'd2809;

assign sext_ln42_11_fu_8980_p1 = $signed(trunc_ln42_34_reg_9491);

assign sext_ln42_12_fu_8365_p1 = data_1_val_read_reg_9331;

assign sext_ln42_13_fu_8983_p1 = $signed(trunc_ln42_41_reg_9526);

assign sext_ln42_14_fu_8378_p1 = data_2_val_read_reg_9322;

assign sext_ln42_15_fu_8986_p1 = $signed(trunc_ln42_46_reg_9551);

assign sext_ln42_16_fu_8687_p1 = $signed(tmp_fu_8680_p3);

assign sext_ln42_17_fu_8698_p1 = $signed(tmp_14_fu_8691_p3);

assign sext_ln42_18_fu_8731_p1 = $signed(tmp_15_fu_8724_p3);

assign sext_ln42_19_fu_8389_p1 = data_3_val_read_reg_9313;

assign sext_ln42_20_fu_9019_p1 = $signed(trunc_ln42_53_fu_9009_p4);

assign sext_ln42_21_fu_9061_p1 = $signed(trunc_ln42_55_fu_9051_p4);

assign sext_ln42_22_fu_9065_p1 = $signed(trunc_ln42_62_reg_9621);

assign sext_ln42_fu_8356_p1 = data_0_val_read_reg_9337;

assign sext_ln58_fu_9116_p1 = $signed(add_ln58_51_reg_9681);

assign sext_ln70_11_fu_8989_p1 = data_3_val_read_reg_9313_pp0_iter2_reg;

assign sext_ln70_13_fu_8410_p1 = $signed(data_5_val_read_reg_9302);

assign sext_ln70_14_fu_8337_p0 = data_6_val_int_reg;

assign sext_ln70_14_fu_8337_p1 = sext_ln70_14_fu_8337_p0;

assign sext_ln73_19_fu_8999_p1 = $signed(tmp_16_fu_8992_p3);

assign sext_ln73_20_fu_9030_p1 = $signed(tmp_17_fu_9023_p3);

assign sext_ln73_21_fu_9041_p1 = $signed(tmp_18_fu_9034_p3);

assign sext_ln73_22_fu_8941_p1 = $signed(trunc_ln42_74_reg_9446);

assign sext_ln73_fu_8401_p1 = data_4_val_read_reg_9307;

assign sub_ln42_1_fu_8735_p2 = ($signed(sub_ln42_fu_8718_p2) - $signed(sext_ln42_18_fu_8731_p1));

assign sub_ln42_fu_8718_p2 = ($signed(26'd0) - $signed(sext_ln42_16_fu_8687_p1));

assign sub_ln73_8_fu_9045_p2 = ($signed(sext_ln73_21_fu_9041_p1) - $signed(sext_ln73_20_fu_9030_p1));

assign sub_ln73_fu_9003_p2 = ($signed(sext_ln70_11_fu_8989_p1) - $signed(sext_ln73_19_fu_8999_p1));

assign tmp_14_fu_8691_p3 = {{data_2_val_read_reg_9322_pp0_iter1_reg}, {6'd0}};

assign tmp_15_fu_8724_p3 = {{data_2_val_read_reg_9322_pp0_iter1_reg}, {4'd0}};

assign tmp_16_fu_8992_p3 = {{data_3_val_read_reg_9313_pp0_iter2_reg}, {8'd0}};

assign tmp_17_fu_9023_p3 = {{data_3_val_read_reg_9313_pp0_iter2_reg}, {7'd0}};

assign tmp_18_fu_9034_p3 = {{data_3_val_read_reg_9313_pp0_iter2_reg}, {1'd0}};

assign tmp_fu_8680_p3 = {{data_2_val_read_reg_9322_pp0_iter1_reg}, {9'd0}};

assign trunc_ln42_53_fu_9009_p4 = {{sub_ln73_fu_9003_p2[24:10]}};

assign trunc_ln42_55_fu_9051_p4 = {{sub_ln73_8_fu_9045_p2[23:10]}};

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s
