-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity myproject_conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config5_s_w5_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 6; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 36
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of myproject_conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config5_s_w5_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000100", 1 => "000101", 2 => "000111", 3 => "111110", 
    4 => "000110", 5 => "110110", 6 => "011010", 7 => "100011", 
    8 => "100000", 9 => "111110", 10 => "000101", 11 => "010000", 
    12 => "000100", 13 => "001001", 14 => "110011", 15 => "000011", 
    16 => "001001", 17 => "111010", 18 => "100000", 19 => "010010", 
    20 => "000001", 21 => "000011", 22 => "000010", 23 => "000100", 
    24 => "001011", 25 => "111101", 26 => "000000", 27 => "111111", 
    28 => "011111", 29 => "000000", 30 => "111111", 31 => "101111", 
    32 => "000011", 33 => "100001", 34 => "001011", 35 => "111101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

