// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_concatenate1d_ap_ufixed_ap_ufixed_ap_fixed_16_6_5_3_0_config15_s (
        ap_ready,
        data1_0_val,
        data1_1_val,
        data1_2_val,
        data1_3_val,
        data1_4_val,
        data1_5_val,
        data1_6_val,
        data1_7_val,
        data2_0_val,
        data2_1_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_rst
);


output   ap_ready;
input  [7:0] data1_0_val;
input  [7:0] data1_1_val;
input  [7:0] data1_2_val;
input  [7:0] data1_3_val;
input  [7:0] data1_4_val;
input  [7:0] data1_5_val;
input  [7:0] data1_6_val;
input  [7:0] data1_7_val;
input  [7:0] data2_0_val;
input  [7:0] data2_1_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
input   ap_rst;

wire   [9:0] shl_ln_fu_96_p3;
wire   [9:0] shl_ln120_1_fu_108_p3;
wire   [9:0] shl_ln120_2_fu_120_p3;
wire   [9:0] shl_ln120_3_fu_132_p3;
wire   [9:0] shl_ln120_4_fu_144_p3;
wire   [9:0] shl_ln120_5_fu_156_p3;
wire   [9:0] shl_ln120_6_fu_168_p3;
wire   [9:0] shl_ln120_7_fu_180_p3;
wire   [9:0] shl_ln2_fu_192_p3;
wire   [9:0] shl_ln123_1_fu_204_p3;
wire   [15:0] zext_ln120_fu_104_p1;
wire   [15:0] zext_ln120_1_fu_116_p1;
wire   [15:0] zext_ln120_2_fu_128_p1;
wire   [15:0] zext_ln120_3_fu_140_p1;
wire   [15:0] zext_ln120_4_fu_152_p1;
wire   [15:0] zext_ln120_5_fu_164_p1;
wire   [15:0] zext_ln120_6_fu_176_p1;
wire   [15:0] zext_ln123_fu_188_p1;
wire   [15:0] zext_ln123_1_fu_200_p1;
wire   [15:0] zext_ln125_fu_212_p1;

assign ap_ready = 1'b1;

assign shl_ln120_1_fu_108_p3 = {{data1_1_val}, {2'd0}};

assign shl_ln120_2_fu_120_p3 = {{data1_2_val}, {2'd0}};

assign shl_ln120_3_fu_132_p3 = {{data1_3_val}, {2'd0}};

assign shl_ln120_4_fu_144_p3 = {{data1_4_val}, {2'd0}};

assign shl_ln120_5_fu_156_p3 = {{data1_5_val}, {2'd0}};

assign shl_ln120_6_fu_168_p3 = {{data1_6_val}, {2'd0}};

assign shl_ln120_7_fu_180_p3 = {{data1_7_val}, {2'd0}};

assign shl_ln123_1_fu_204_p3 = {{data2_1_val}, {2'd0}};

assign shl_ln2_fu_192_p3 = {{data2_0_val}, {2'd0}};

assign shl_ln_fu_96_p3 = {{data1_0_val}, {2'd0}};

assign zext_ln120_1_fu_116_p1 = shl_ln120_1_fu_108_p3;

assign zext_ln120_2_fu_128_p1 = shl_ln120_2_fu_120_p3;

assign zext_ln120_3_fu_140_p1 = shl_ln120_3_fu_132_p3;

assign zext_ln120_4_fu_152_p1 = shl_ln120_4_fu_144_p3;

assign zext_ln120_5_fu_164_p1 = shl_ln120_5_fu_156_p3;

assign zext_ln120_6_fu_176_p1 = shl_ln120_6_fu_168_p3;

assign zext_ln120_fu_104_p1 = shl_ln_fu_96_p3;

assign zext_ln123_1_fu_200_p1 = shl_ln2_fu_192_p3;

assign zext_ln123_fu_188_p1 = shl_ln120_7_fu_180_p3;

assign zext_ln125_fu_212_p1 = shl_ln123_1_fu_204_p3;

assign ap_return_0 = zext_ln120_fu_104_p1;

assign ap_return_1 = zext_ln120_1_fu_116_p1;

assign ap_return_2 = zext_ln120_2_fu_128_p1;

assign ap_return_3 = zext_ln120_3_fu_140_p1;

assign ap_return_4 = zext_ln120_4_fu_152_p1;

assign ap_return_5 = zext_ln120_5_fu_164_p1;

assign ap_return_6 = zext_ln120_6_fu_176_p1;

assign ap_return_7 = zext_ln123_fu_188_p1;

assign ap_return_8 = zext_ln123_1_fu_200_p1;

assign ap_return_9 = zext_ln125_fu_212_p1;

endmodule //myproject_concatenate1d_ap_ufixed_ap_ufixed_ap_fixed_16_6_5_3_0_config15_s
