ASICFIFO: hls4ml_lib.mgc_pipe_mem
ASICLibs: saed32rvt_tt0p78v125c_beh
ASICRAM: ccs_sample_mem.ccs_ram_sync_1R1W
Backend: Catapult
BuildOptions:
  BUPWorkers: 0
  BuildBUP: 0
  LaunchDA: 0
  PowerEst: 0
  PowerOpt: 0
  RTLSynth: 0
  RandomTBFrames: 2
  SCVerify: 0
  Synth: 1
  csim: 0
  startup: ''
  verilog: 1
  vhdl: 1
CModelDefaultThreshold: 0.0
ClockPeriod: 10
ClockUncertainty: 12.5%
CopyAC: false
CopyNNET: false
FIFO: Xilinx_FIFO.FIFO_SYNC
GlobalDirectives:
  allocate: {}
  analyze:
    MEM_MAP_THRESHOLD: '[expr 2048 * 16 + 1]'
    REDUNDANT_RTL_ELIMINATION: 'false'
    RESET_CLEARS_ALL_REGS: 'no'
  architect: {}
  assembly:
    ADVANCED_DPOPT: 'false'
  compile: {}
  dpfsm: {}
  extract: {}
  libraries: {}
  schedule: {}
HLSConfig:
  LayerName:
    concatenate_24:
      LayerClassName: Concatenate
      Precision:
        result: auto
      Trace: false
    concatenate_25:
      LayerClassName: Concatenate
      Precision:
        result: auto
      Trace: false
    hidden_dense:
      LayerClassName: QDense
      Precision:
        bias: fixed<4,1,TRN,WRAP,0>
        result: auto
        weight: fixed<4,1,TRN,WRAP,0>
      Trace: false
    hidden_dense_linear:
      LayerClassName: linear
      Precision:
        result: auto
      Trace: false
    output_dense:
      LayerClassName: QDense
      Precision:
        bias: fixed<4,1,TRN,WRAP,0>
        result: auto
        weight: fixed<4,1,TRN,WRAP,0>
      Trace: false
    output_dense_linear:
      LayerClassName: linear
      Precision:
        result: auto
      Trace: false
    y_profile:
      LayerClassName: InputLayer
      Precision:
        result: auto
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: ac_fixed<16,6>
      maximum: ac_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
  implementation: hls4ml
IOType: io_stream
InputShapes:
  y_profile:
  - 13
KerasH5: ./hlsCatapultModel2_20260325_113231/model_22_weights.h5
KerasJson: ./hlsCatapultModel2_20260325_113231/model_22.json
MemType: null
OutputDir: ./hlsCatapultModel2_20260325_113231
OutputShapes:
  layer6_out:
  - 1
ParamStore: global
PortType: null
ProjectDir: Catapult
ProjectName: myproject
RAM: Xilinx_RAMS.BLOCK_1R1W_RBW
ROMLocation: Local
Stamp: 61e1f235
Technology: asic
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteTar: 0
  WriteWeightsTxt: 1
