// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg  signed [15:0] data_1_val_read_reg_443;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] data_0_val_read_reg_452;
wire  signed [20:0] sext_ln42_181_fu_143_p1;
reg  signed [20:0] sext_ln42_181_reg_460;
reg   [15:0] trunc_ln_reg_466;
reg   [15:0] trunc_ln42_54_reg_471;
reg   [15:0] trunc_ln42_55_reg_478;
reg   [15:0] trunc_ln42_56_reg_483;
reg   [15:0] trunc_ln42_57_reg_489;
reg   [14:0] trunc_ln42_s_reg_494;
reg   [15:0] trunc_ln42_58_reg_499;
reg   [15:0] trunc_ln42_59_reg_504;
wire   [5:0] grp_fu_90_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] sext_ln42_181_fu_143_p0;
wire   [19:0] tmp_fu_151_p3;
wire  signed [20:0] sext_ln73_285_fu_158_p1;
wire  signed [20:0] sext_ln42_fu_148_p1;
wire   [20:0] sub_ln73_fu_162_p2;
wire   [20:0] p_shl_fu_178_p3;
wire   [20:0] sub_ln42_fu_185_p2;
wire   [16:0] tmp_292_fu_201_p3;
wire  signed [20:0] sext_ln73_286_fu_208_p1;
wire   [20:0] sub_ln73_162_fu_212_p2;
wire   [20:0] grp_fu_90_p2;
wire   [19:0] tmp_293_fu_241_p3;
wire   [17:0] tmp_294_fu_252_p3;
wire  signed [20:0] sext_ln73_287_fu_248_p1;
wire  signed [20:0] sext_ln73_288_fu_259_p1;
wire   [20:0] sub_ln73_163_fu_263_p2;
wire   [18:0] tmp_295_fu_279_p3;
wire  signed [19:0] sext_ln73_289_fu_286_p1;
wire  signed [19:0] sext_ln73_fu_228_p1;
wire   [19:0] sub_ln73_164_fu_290_p2;
wire   [20:0] sub_ln73_165_fu_306_p2;
wire   [16:0] tmp_296_fu_321_p3;
wire  signed [20:0] sext_ln73_290_fu_328_p1;
wire   [20:0] sub_ln73_166_fu_332_p2;
wire   [15:0] add_ln58_fu_351_p2;
wire   [15:0] add_ln58_349_fu_361_p2;
wire  signed [15:0] sext_ln42_182_fu_348_p1;
wire   [15:0] add_ln58_351_fu_371_p2;
wire   [15:0] add_ln58_354_fu_387_p2;
wire   [15:0] add_ln58_356_fu_397_p2;
wire   [15:0] add_ln58_348_fu_356_p2;
wire   [15:0] add_ln58_350_fu_366_p2;
wire   [15:0] add_ln58_352_fu_377_p2;
wire   [15:0] add_ln58_353_fu_382_p2;
wire   [15:0] add_ln58_355_fu_392_p2;
wire   [15:0] add_ln58_357_fu_402_p2;
reg    grp_fu_90_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

myproject_mul_16s_6ns_21_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 21 ))
mul_16s_6ns_21_2_1_U184(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_1_val),
    .din1(grp_fu_90_p1),
    .ce(grp_fu_90_ce),
    .dout(grp_fu_90_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_0_val_read_reg_452 <= data_0_val;
        data_1_val_read_reg_443 <= data_1_val;
        sext_ln42_181_reg_460 <= sext_ln42_181_fu_143_p1;
        trunc_ln42_54_reg_471 <= {{sub_ln42_fu_185_p2[20:5]}};
        trunc_ln42_55_reg_478 <= {{sub_ln73_162_fu_212_p2[20:5]}};
        trunc_ln42_56_reg_483 <= {{grp_fu_90_p2[20:5]}};
        trunc_ln42_57_reg_489 <= {{sub_ln73_163_fu_263_p2[20:5]}};
        trunc_ln42_58_reg_499 <= {{sub_ln73_165_fu_306_p2[20:5]}};
        trunc_ln42_59_reg_504 <= {{sub_ln73_166_fu_332_p2[20:5]}};
        trunc_ln42_s_reg_494 <= {{sub_ln73_164_fu_290_p2[19:5]}};
        trunc_ln_reg_466 <= {{sub_ln73_fu_162_p2[20:5]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_90_ce = 1'b1;
    end else begin
        grp_fu_90_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_348_fu_356_p2 = (add_ln58_fu_351_p2 + trunc_ln_reg_466);

assign add_ln58_349_fu_361_p2 = (trunc_ln42_57_reg_489 + 16'd672);

assign add_ln58_350_fu_366_p2 = (add_ln58_349_fu_361_p2 + trunc_ln42_54_reg_471);

assign add_ln58_351_fu_371_p2 = ($signed(sext_ln42_182_fu_348_p1) + $signed(16'd768));

assign add_ln58_352_fu_377_p2 = (add_ln58_351_fu_371_p2 + trunc_ln42_54_reg_471);

assign add_ln58_353_fu_382_p2 = ($signed(trunc_ln42_58_reg_499) + $signed(16'd65504));

assign add_ln58_354_fu_387_p2 = (trunc_ln42_59_reg_504 + 16'd160);

assign add_ln58_355_fu_392_p2 = (add_ln58_354_fu_387_p2 + trunc_ln42_54_reg_471);

assign add_ln58_356_fu_397_p2 = (trunc_ln42_56_reg_483 + 16'd32);

assign add_ln58_357_fu_402_p2 = (add_ln58_356_fu_397_p2 + trunc_ln42_55_reg_478);

assign add_ln58_fu_351_p2 = (trunc_ln42_56_reg_483 + 16'd96);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = add_ln58_348_fu_356_p2;

assign ap_return_1 = add_ln58_350_fu_366_p2;

assign ap_return_2 = add_ln58_352_fu_377_p2;

assign ap_return_3 = add_ln58_353_fu_382_p2;

assign ap_return_4 = add_ln58_355_fu_392_p2;

assign ap_return_5 = add_ln58_357_fu_402_p2;

assign grp_fu_90_p1 = 21'd26;

assign p_shl_fu_178_p3 = {{data_0_val_read_reg_452}, {5'd0}};

assign sext_ln42_181_fu_143_p0 = data_1_val;

assign sext_ln42_181_fu_143_p1 = sext_ln42_181_fu_143_p0;

assign sext_ln42_182_fu_348_p1 = $signed(trunc_ln42_s_reg_494);

assign sext_ln42_fu_148_p1 = data_0_val_read_reg_452;

assign sext_ln73_285_fu_158_p1 = $signed(tmp_fu_151_p3);

assign sext_ln73_286_fu_208_p1 = $signed(tmp_292_fu_201_p3);

assign sext_ln73_287_fu_248_p1 = $signed(tmp_293_fu_241_p3);

assign sext_ln73_288_fu_259_p1 = $signed(tmp_294_fu_252_p3);

assign sext_ln73_289_fu_286_p1 = $signed(tmp_295_fu_279_p3);

assign sext_ln73_290_fu_328_p1 = $signed(tmp_296_fu_321_p3);

assign sext_ln73_fu_228_p1 = data_1_val_read_reg_443;

assign sub_ln42_fu_185_p2 = (21'd0 - p_shl_fu_178_p3);

assign sub_ln73_162_fu_212_p2 = ($signed(sext_ln73_285_fu_158_p1) - $signed(sext_ln73_286_fu_208_p1));

assign sub_ln73_163_fu_263_p2 = ($signed(sext_ln73_287_fu_248_p1) - $signed(sext_ln73_288_fu_259_p1));

assign sub_ln73_164_fu_290_p2 = ($signed(sext_ln73_289_fu_286_p1) - $signed(sext_ln73_fu_228_p1));

assign sub_ln73_165_fu_306_p2 = ($signed(sext_ln42_181_reg_460) - $signed(sext_ln73_287_fu_248_p1));

assign sub_ln73_166_fu_332_p2 = ($signed(sext_ln73_290_fu_328_p1) - $signed(sext_ln73_287_fu_248_p1));

assign sub_ln73_fu_162_p2 = ($signed(sext_ln73_285_fu_158_p1) - $signed(sext_ln42_fu_148_p1));

assign tmp_292_fu_201_p3 = {{data_0_val_read_reg_452}, {1'd0}};

assign tmp_293_fu_241_p3 = {{data_1_val_read_reg_443}, {4'd0}};

assign tmp_294_fu_252_p3 = {{data_1_val_read_reg_443}, {2'd0}};

assign tmp_295_fu_279_p3 = {{data_1_val_read_reg_443}, {3'd0}};

assign tmp_296_fu_321_p3 = {{data_1_val_read_reg_443}, {1'd0}};

assign tmp_fu_151_p3 = {{data_0_val_read_reg_452}, {4'd0}};

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config11_s
