-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln45_fu_58_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_386 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_391 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln46_fu_126_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln46_reg_398 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_404 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_7_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_7_reg_410 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_reg_415 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln46_7_fu_242_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln46_7_reg_422 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_37_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_37_reg_428 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_46_fu_102_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_fu_90_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_82_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_72_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln46_fu_122_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_132_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_45_fu_94_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_54_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_15_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_10_fu_206_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_25_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_198_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_12_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_7_fu_188_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln46_7_fu_238_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_43_fu_248_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_50_fu_210_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_264_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_61_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_7_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_17_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_23_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_fu_304_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln46_24_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_23_fu_310_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_24_fu_318_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln46_7_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_26_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_25_fu_346_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln46_27_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_26_fu_352_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_27_fu_360_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal res_0_0_fu_325_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal res_1_0_fu_367_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln46_7_reg_422 <= add_ln46_7_fu_242_p2;
                add_ln46_reg_398 <= add_ln46_fu_126_p2;
                empty_37_reg_428 <= empty_37_fu_284_p2;
                empty_reg_404 <= empty_fu_168_p2;
                icmp_ln45_7_reg_410 <= icmp_ln45_7_fu_174_p2;
                icmp_ln45_reg_386 <= icmp_ln45_fu_58_p2;
                tmp_48_reg_415 <= data_1_val(15 downto 15);
                tmp_reg_391 <= data_0_val(15 downto 15);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln46_7_fu_242_p2 <= std_logic_vector(unsigned(trunc_ln46_7_fu_188_p4) + unsigned(zext_ln46_7_fu_238_p1));
    add_ln46_fu_126_p2 <= std_logic_vector(unsigned(trunc_ln_fu_72_p4) + unsigned(zext_ln46_fu_122_p1));
    and_ln46_12_fu_232_p2 <= (tmp_49_fu_198_p3 and or_ln46_25_fu_226_p2);
    and_ln46_15_fu_162_p2 <= (tmp_47_fu_148_p3 or not_tmp_54_fu_156_p2);
    and_ln46_17_fu_278_p2 <= (tmp_52_fu_264_p3 or not_tmp_61_fu_272_p2);
    and_ln46_fu_116_p2 <= (tmp_44_fu_82_p3 and or_ln46_fu_110_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= res_0_0_fu_325_p3;
    ap_return_1 <= res_1_0_fu_367_p3;
    empty_37_fu_284_p2 <= (icmp_ln46_7_fu_258_p2 and and_ln46_17_fu_278_p2);
    empty_fu_168_p2 <= (icmp_ln46_fu_142_p2 and and_ln46_15_fu_162_p2);
    icmp_ln45_7_fu_174_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_58_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln46_7_fu_258_p2 <= "1" when (tmp_43_fu_248_p4 = ap_const_lv6_0) else "0";
    icmp_ln46_fu_142_p2 <= "1" when (tmp_s_fu_132_p4 = ap_const_lv6_0) else "0";
    not_tmp_54_fu_156_p2 <= (tmp_45_fu_94_p3 xor ap_const_lv1_1);
    not_tmp_61_fu_272_p2 <= (tmp_50_fu_210_p3 xor ap_const_lv1_1);
    or_ln46_23_fu_290_p2 <= (tmp_reg_391 or empty_reg_404);
    or_ln46_24_fu_299_p2 <= (xor_ln46_fu_294_p2 or tmp_reg_391);
    or_ln46_25_fu_226_p2 <= (trunc_ln46_10_fu_206_p1 or tmp_51_fu_218_p3);
    or_ln46_26_fu_332_p2 <= (tmp_48_reg_415 or empty_37_reg_428);
    or_ln46_27_fu_341_p2 <= (xor_ln46_7_fu_336_p2 or tmp_48_reg_415);
    or_ln46_fu_110_p2 <= (trunc_ln46_fu_90_p1 or tmp_46_fu_102_p3);
    res_0_0_fu_325_p3 <= 
        select_ln46_24_fu_318_p3 when (icmp_ln45_reg_386(0) = '1') else 
        ap_const_lv8_0;
    res_1_0_fu_367_p3 <= 
        select_ln46_27_fu_360_p3 when (icmp_ln45_7_reg_410(0) = '1') else 
        ap_const_lv8_0;
    select_ln46_23_fu_310_p3 <= 
        select_ln46_fu_304_p3 when (or_ln46_23_fu_290_p2(0) = '1') else 
        ap_const_lv8_FF;
    select_ln46_24_fu_318_p3 <= 
        select_ln46_23_fu_310_p3 when (or_ln46_24_fu_299_p2(0) = '1') else 
        add_ln46_reg_398;
    select_ln46_25_fu_346_p3 <= 
        ap_const_lv8_0 when (tmp_48_reg_415(0) = '1') else 
        add_ln46_7_reg_422;
    select_ln46_26_fu_352_p3 <= 
        select_ln46_25_fu_346_p3 when (or_ln46_26_fu_332_p2(0) = '1') else 
        ap_const_lv8_FF;
    select_ln46_27_fu_360_p3 <= 
        select_ln46_26_fu_352_p3 when (or_ln46_27_fu_341_p2(0) = '1') else 
        add_ln46_7_reg_422;
    select_ln46_fu_304_p3 <= 
        ap_const_lv8_0 when (tmp_reg_391(0) = '1') else 
        add_ln46_reg_398;
    tmp_43_fu_248_p4 <= data_1_val(15 downto 10);
    tmp_44_fu_82_p3 <= data_0_val(1 downto 1);
    tmp_45_fu_94_p3 <= data_0_val(9 downto 9);
    tmp_46_fu_102_p3 <= data_0_val(2 downto 2);
    tmp_47_fu_148_p3 <= add_ln46_fu_126_p2(7 downto 7);
    tmp_49_fu_198_p3 <= data_1_val(1 downto 1);
    tmp_50_fu_210_p3 <= data_1_val(9 downto 9);
    tmp_51_fu_218_p3 <= data_1_val(2 downto 2);
    tmp_52_fu_264_p3 <= add_ln46_7_fu_242_p2(7 downto 7);
    tmp_s_fu_132_p4 <= data_0_val(15 downto 10);
    trunc_ln46_10_fu_206_p1 <= data_1_val(1 - 1 downto 0);
    trunc_ln46_7_fu_188_p4 <= data_1_val(9 downto 2);
    trunc_ln46_fu_90_p1 <= data_0_val(1 - 1 downto 0);
    trunc_ln_fu_72_p4 <= data_0_val(9 downto 2);
    xor_ln46_7_fu_336_p2 <= (empty_37_reg_428 xor ap_const_lv1_1);
    xor_ln46_fu_294_p2 <= (empty_reg_404 xor ap_const_lv1_1);
    zext_ln46_7_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln46_12_fu_232_p2),8));
    zext_ln46_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln46_fu_116_p2),8));
end behav;
