// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config14_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln45_fu_90_p2;
reg   [0:0] icmp_ln45_reg_1074;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_1079;
wire   [7:0] add_ln46_fu_158_p2;
reg   [7:0] add_ln46_reg_1086;
wire   [0:0] empty_fu_200_p2;
reg   [0:0] empty_reg_1092;
wire   [0:0] icmp_ln45_7_fu_206_p2;
reg   [0:0] icmp_ln45_7_reg_1098;
reg   [0:0] tmp_48_reg_1103;
wire   [7:0] add_ln46_7_fu_274_p2;
reg   [7:0] add_ln46_7_reg_1110;
wire   [0:0] empty_39_fu_316_p2;
reg   [0:0] empty_39_reg_1116;
wire   [0:0] icmp_ln45_8_fu_322_p2;
reg   [0:0] icmp_ln45_8_reg_1122;
reg   [0:0] tmp_53_reg_1127;
wire   [7:0] add_ln46_8_fu_390_p2;
reg   [7:0] add_ln46_8_reg_1134;
wire   [0:0] empty_40_fu_432_p2;
reg   [0:0] empty_40_reg_1140;
wire   [0:0] icmp_ln45_9_fu_438_p2;
reg   [0:0] icmp_ln45_9_reg_1146;
reg   [0:0] tmp_59_reg_1151;
wire   [7:0] add_ln46_9_fu_506_p2;
reg   [7:0] add_ln46_9_reg_1158;
wire   [0:0] empty_41_fu_548_p2;
reg   [0:0] empty_41_reg_1164;
wire   [0:0] icmp_ln45_10_fu_554_p2;
reg   [0:0] icmp_ln45_10_reg_1170;
reg   [0:0] tmp_65_reg_1175;
wire   [7:0] add_ln46_10_fu_622_p2;
reg   [7:0] add_ln46_10_reg_1182;
wire   [0:0] empty_42_fu_664_p2;
reg   [0:0] empty_42_reg_1188;
wire   [0:0] icmp_ln45_11_fu_670_p2;
reg   [0:0] icmp_ln45_11_reg_1194;
reg   [0:0] tmp_71_reg_1199;
wire   [7:0] add_ln46_11_fu_738_p2;
reg   [7:0] add_ln46_11_reg_1206;
wire   [0:0] empty_43_fu_780_p2;
reg   [0:0] empty_43_reg_1212;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_46_fu_134_p3;
wire   [0:0] trunc_ln46_fu_122_p1;
wire   [0:0] or_ln46_fu_142_p2;
wire   [0:0] tmp_44_fu_114_p3;
wire   [0:0] and_ln46_fu_148_p2;
wire   [7:0] trunc_ln_fu_104_p4;
wire   [7:0] zext_ln46_fu_154_p1;
wire   [5:0] tmp_s_fu_164_p4;
wire   [0:0] tmp_45_fu_126_p3;
wire   [0:0] tmp_47_fu_180_p3;
wire   [0:0] not_tmp_54_fu_188_p2;
wire   [0:0] icmp_ln46_fu_174_p2;
wire   [0:0] and_ln46_15_fu_194_p2;
wire   [0:0] tmp_51_fu_250_p3;
wire   [0:0] trunc_ln46_10_fu_238_p1;
wire   [0:0] or_ln46_25_fu_258_p2;
wire   [0:0] tmp_49_fu_230_p3;
wire   [0:0] and_ln46_12_fu_264_p2;
wire   [7:0] trunc_ln46_7_fu_220_p4;
wire   [7:0] zext_ln46_7_fu_270_p1;
wire   [5:0] tmp_43_fu_280_p4;
wire   [0:0] tmp_50_fu_242_p3;
wire   [0:0] tmp_52_fu_296_p3;
wire   [0:0] not_tmp_61_fu_304_p2;
wire   [0:0] icmp_ln46_7_fu_290_p2;
wire   [0:0] and_ln46_17_fu_310_p2;
wire   [0:0] tmp_56_fu_366_p3;
wire   [0:0] trunc_ln46_11_fu_354_p1;
wire   [0:0] or_ln46_28_fu_374_p2;
wire   [0:0] tmp_54_fu_346_p3;
wire   [0:0] and_ln46_13_fu_380_p2;
wire   [7:0] trunc_ln46_8_fu_336_p4;
wire   [7:0] zext_ln46_8_fu_386_p1;
wire   [5:0] tmp_57_fu_396_p4;
wire   [0:0] tmp_55_fu_358_p3;
wire   [0:0] tmp_58_fu_412_p3;
wire   [0:0] not_tmp_68_fu_420_p2;
wire   [0:0] icmp_ln46_8_fu_406_p2;
wire   [0:0] and_ln46_19_fu_426_p2;
wire   [0:0] tmp_62_fu_482_p3;
wire   [0:0] trunc_ln46_12_fu_470_p1;
wire   [0:0] or_ln46_31_fu_490_p2;
wire   [0:0] tmp_60_fu_462_p3;
wire   [0:0] and_ln46_14_fu_496_p2;
wire   [7:0] trunc_ln46_9_fu_452_p4;
wire   [7:0] zext_ln46_9_fu_502_p1;
wire   [5:0] tmp_63_fu_512_p4;
wire   [0:0] tmp_61_fu_474_p3;
wire   [0:0] tmp_64_fu_528_p3;
wire   [0:0] not_tmp_75_fu_536_p2;
wire   [0:0] icmp_ln46_9_fu_522_p2;
wire   [0:0] and_ln46_21_fu_542_p2;
wire   [0:0] tmp_68_fu_598_p3;
wire   [0:0] trunc_ln46_13_fu_586_p1;
wire   [0:0] or_ln46_34_fu_606_p2;
wire   [0:0] tmp_66_fu_578_p3;
wire   [0:0] and_ln46_16_fu_612_p2;
wire   [7:0] trunc_ln46_s_fu_568_p4;
wire   [7:0] zext_ln46_10_fu_618_p1;
wire   [5:0] tmp_69_fu_628_p4;
wire   [0:0] tmp_67_fu_590_p3;
wire   [0:0] tmp_70_fu_644_p3;
wire   [0:0] not_tmp_82_fu_652_p2;
wire   [0:0] icmp_ln46_10_fu_638_p2;
wire   [0:0] and_ln46_23_fu_658_p2;
wire   [0:0] tmp_74_fu_714_p3;
wire   [0:0] trunc_ln46_14_fu_702_p1;
wire   [0:0] or_ln46_37_fu_722_p2;
wire   [0:0] tmp_72_fu_694_p3;
wire   [0:0] and_ln46_18_fu_728_p2;
wire   [7:0] trunc_ln46_1_fu_684_p4;
wire   [7:0] zext_ln46_11_fu_734_p1;
wire   [5:0] tmp_75_fu_744_p4;
wire   [0:0] tmp_73_fu_706_p3;
wire   [0:0] tmp_76_fu_760_p3;
wire   [0:0] not_tmp_89_fu_768_p2;
wire   [0:0] icmp_ln46_11_fu_754_p2;
wire   [0:0] and_ln46_25_fu_774_p2;
wire   [0:0] xor_ln46_fu_790_p2;
wire   [0:0] or_ln46_23_fu_786_p2;
wire   [7:0] select_ln46_fu_800_p3;
wire   [0:0] or_ln46_24_fu_795_p2;
wire   [7:0] select_ln46_23_fu_806_p3;
wire   [7:0] select_ln46_24_fu_814_p3;
wire   [0:0] xor_ln46_7_fu_832_p2;
wire   [0:0] or_ln46_26_fu_828_p2;
wire   [7:0] select_ln46_25_fu_842_p3;
wire   [0:0] or_ln46_27_fu_837_p2;
wire   [7:0] select_ln46_26_fu_848_p3;
wire   [7:0] select_ln46_27_fu_856_p3;
wire   [0:0] xor_ln46_8_fu_874_p2;
wire   [0:0] or_ln46_29_fu_870_p2;
wire   [7:0] select_ln46_28_fu_884_p3;
wire   [0:0] or_ln46_30_fu_879_p2;
wire   [7:0] select_ln46_29_fu_890_p3;
wire   [7:0] select_ln46_30_fu_898_p3;
wire   [0:0] xor_ln46_9_fu_916_p2;
wire   [0:0] or_ln46_32_fu_912_p2;
wire   [7:0] select_ln46_31_fu_926_p3;
wire   [0:0] or_ln46_33_fu_921_p2;
wire   [7:0] select_ln46_32_fu_932_p3;
wire   [7:0] select_ln46_33_fu_940_p3;
wire   [0:0] xor_ln46_10_fu_958_p2;
wire   [0:0] or_ln46_35_fu_954_p2;
wire   [7:0] select_ln46_34_fu_968_p3;
wire   [0:0] or_ln46_36_fu_963_p2;
wire   [7:0] select_ln46_35_fu_974_p3;
wire   [7:0] select_ln46_36_fu_982_p3;
wire   [0:0] xor_ln46_11_fu_1000_p2;
wire   [0:0] or_ln46_38_fu_996_p2;
wire   [7:0] select_ln46_37_fu_1010_p3;
wire   [0:0] or_ln46_39_fu_1005_p2;
wire   [7:0] select_ln46_38_fu_1016_p3;
wire   [7:0] select_ln46_39_fu_1024_p3;
wire   [7:0] res_0_0_fu_821_p3;
wire   [7:0] res_1_0_fu_863_p3;
wire   [7:0] res_2_0_fu_905_p3;
wire   [7:0] res_3_0_fu_947_p3;
wire   [7:0] res_4_0_fu_989_p3;
wire   [7:0] res_5_0_fu_1031_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln46_10_reg_1182 <= add_ln46_10_fu_622_p2;
        add_ln46_11_reg_1206 <= add_ln46_11_fu_738_p2;
        add_ln46_7_reg_1110 <= add_ln46_7_fu_274_p2;
        add_ln46_8_reg_1134 <= add_ln46_8_fu_390_p2;
        add_ln46_9_reg_1158 <= add_ln46_9_fu_506_p2;
        add_ln46_reg_1086 <= add_ln46_fu_158_p2;
        empty_39_reg_1116 <= empty_39_fu_316_p2;
        empty_40_reg_1140 <= empty_40_fu_432_p2;
        empty_41_reg_1164 <= empty_41_fu_548_p2;
        empty_42_reg_1188 <= empty_42_fu_664_p2;
        empty_43_reg_1212 <= empty_43_fu_780_p2;
        empty_reg_1092 <= empty_fu_200_p2;
        icmp_ln45_10_reg_1170 <= icmp_ln45_10_fu_554_p2;
        icmp_ln45_11_reg_1194 <= icmp_ln45_11_fu_670_p2;
        icmp_ln45_7_reg_1098 <= icmp_ln45_7_fu_206_p2;
        icmp_ln45_8_reg_1122 <= icmp_ln45_8_fu_322_p2;
        icmp_ln45_9_reg_1146 <= icmp_ln45_9_fu_438_p2;
        icmp_ln45_reg_1074 <= icmp_ln45_fu_90_p2;
        tmp_48_reg_1103 <= data_1_val[32'd15];
        tmp_53_reg_1127 <= data_2_val[32'd15];
        tmp_59_reg_1151 <= data_3_val[32'd15];
        tmp_65_reg_1175 <= data_4_val[32'd15];
        tmp_71_reg_1199 <= data_5_val[32'd15];
        tmp_reg_1079 <= data_0_val[32'd15];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_10_fu_622_p2 = (trunc_ln46_s_fu_568_p4 + zext_ln46_10_fu_618_p1);

assign add_ln46_11_fu_738_p2 = (trunc_ln46_1_fu_684_p4 + zext_ln46_11_fu_734_p1);

assign add_ln46_7_fu_274_p2 = (trunc_ln46_7_fu_220_p4 + zext_ln46_7_fu_270_p1);

assign add_ln46_8_fu_390_p2 = (trunc_ln46_8_fu_336_p4 + zext_ln46_8_fu_386_p1);

assign add_ln46_9_fu_506_p2 = (trunc_ln46_9_fu_452_p4 + zext_ln46_9_fu_502_p1);

assign add_ln46_fu_158_p2 = (trunc_ln_fu_104_p4 + zext_ln46_fu_154_p1);

assign and_ln46_12_fu_264_p2 = (tmp_49_fu_230_p3 & or_ln46_25_fu_258_p2);

assign and_ln46_13_fu_380_p2 = (tmp_54_fu_346_p3 & or_ln46_28_fu_374_p2);

assign and_ln46_14_fu_496_p2 = (tmp_60_fu_462_p3 & or_ln46_31_fu_490_p2);

assign and_ln46_15_fu_194_p2 = (tmp_47_fu_180_p3 | not_tmp_54_fu_188_p2);

assign and_ln46_16_fu_612_p2 = (tmp_66_fu_578_p3 & or_ln46_34_fu_606_p2);

assign and_ln46_17_fu_310_p2 = (tmp_52_fu_296_p3 | not_tmp_61_fu_304_p2);

assign and_ln46_18_fu_728_p2 = (tmp_72_fu_694_p3 & or_ln46_37_fu_722_p2);

assign and_ln46_19_fu_426_p2 = (tmp_58_fu_412_p3 | not_tmp_68_fu_420_p2);

assign and_ln46_21_fu_542_p2 = (tmp_64_fu_528_p3 | not_tmp_75_fu_536_p2);

assign and_ln46_23_fu_658_p2 = (tmp_70_fu_644_p3 | not_tmp_82_fu_652_p2);

assign and_ln46_25_fu_774_p2 = (tmp_76_fu_760_p3 | not_tmp_89_fu_768_p2);

assign and_ln46_fu_148_p2 = (tmp_44_fu_114_p3 & or_ln46_fu_142_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = res_0_0_fu_821_p3;

assign ap_return_1 = res_1_0_fu_863_p3;

assign ap_return_2 = res_2_0_fu_905_p3;

assign ap_return_3 = res_3_0_fu_947_p3;

assign ap_return_4 = res_4_0_fu_989_p3;

assign ap_return_5 = res_5_0_fu_1031_p3;

assign empty_39_fu_316_p2 = (icmp_ln46_7_fu_290_p2 & and_ln46_17_fu_310_p2);

assign empty_40_fu_432_p2 = (icmp_ln46_8_fu_406_p2 & and_ln46_19_fu_426_p2);

assign empty_41_fu_548_p2 = (icmp_ln46_9_fu_522_p2 & and_ln46_21_fu_542_p2);

assign empty_42_fu_664_p2 = (icmp_ln46_10_fu_638_p2 & and_ln46_23_fu_658_p2);

assign empty_43_fu_780_p2 = (icmp_ln46_11_fu_754_p2 & and_ln46_25_fu_774_p2);

assign empty_fu_200_p2 = (icmp_ln46_fu_174_p2 & and_ln46_15_fu_194_p2);

assign icmp_ln45_10_fu_554_p2 = (($signed(data_4_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_670_p2 = (($signed(data_5_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_206_p2 = (($signed(data_1_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_322_p2 = (($signed(data_2_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_438_p2 = (($signed(data_3_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_90_p2 = (($signed(data_0_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_10_fu_638_p2 = ((tmp_69_fu_628_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_11_fu_754_p2 = ((tmp_75_fu_744_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_7_fu_290_p2 = ((tmp_43_fu_280_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_8_fu_406_p2 = ((tmp_57_fu_396_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_9_fu_522_p2 = ((tmp_63_fu_512_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_174_p2 = ((tmp_s_fu_164_p4 == 6'd0) ? 1'b1 : 1'b0);

assign not_tmp_54_fu_188_p2 = (tmp_45_fu_126_p3 ^ 1'd1);

assign not_tmp_61_fu_304_p2 = (tmp_50_fu_242_p3 ^ 1'd1);

assign not_tmp_68_fu_420_p2 = (tmp_55_fu_358_p3 ^ 1'd1);

assign not_tmp_75_fu_536_p2 = (tmp_61_fu_474_p3 ^ 1'd1);

assign not_tmp_82_fu_652_p2 = (tmp_67_fu_590_p3 ^ 1'd1);

assign not_tmp_89_fu_768_p2 = (tmp_73_fu_706_p3 ^ 1'd1);

assign or_ln46_23_fu_786_p2 = (tmp_reg_1079 | empty_reg_1092);

assign or_ln46_24_fu_795_p2 = (xor_ln46_fu_790_p2 | tmp_reg_1079);

assign or_ln46_25_fu_258_p2 = (trunc_ln46_10_fu_238_p1 | tmp_51_fu_250_p3);

assign or_ln46_26_fu_828_p2 = (tmp_48_reg_1103 | empty_39_reg_1116);

assign or_ln46_27_fu_837_p2 = (xor_ln46_7_fu_832_p2 | tmp_48_reg_1103);

assign or_ln46_28_fu_374_p2 = (trunc_ln46_11_fu_354_p1 | tmp_56_fu_366_p3);

assign or_ln46_29_fu_870_p2 = (tmp_53_reg_1127 | empty_40_reg_1140);

assign or_ln46_30_fu_879_p2 = (xor_ln46_8_fu_874_p2 | tmp_53_reg_1127);

assign or_ln46_31_fu_490_p2 = (trunc_ln46_12_fu_470_p1 | tmp_62_fu_482_p3);

assign or_ln46_32_fu_912_p2 = (tmp_59_reg_1151 | empty_41_reg_1164);

assign or_ln46_33_fu_921_p2 = (xor_ln46_9_fu_916_p2 | tmp_59_reg_1151);

assign or_ln46_34_fu_606_p2 = (trunc_ln46_13_fu_586_p1 | tmp_68_fu_598_p3);

assign or_ln46_35_fu_954_p2 = (tmp_65_reg_1175 | empty_42_reg_1188);

assign or_ln46_36_fu_963_p2 = (xor_ln46_10_fu_958_p2 | tmp_65_reg_1175);

assign or_ln46_37_fu_722_p2 = (trunc_ln46_14_fu_702_p1 | tmp_74_fu_714_p3);

assign or_ln46_38_fu_996_p2 = (tmp_71_reg_1199 | empty_43_reg_1212);

assign or_ln46_39_fu_1005_p2 = (xor_ln46_11_fu_1000_p2 | tmp_71_reg_1199);

assign or_ln46_fu_142_p2 = (trunc_ln46_fu_122_p1 | tmp_46_fu_134_p3);

assign res_0_0_fu_821_p3 = ((icmp_ln45_reg_1074[0:0] == 1'b1) ? select_ln46_24_fu_814_p3 : 8'd0);

assign res_1_0_fu_863_p3 = ((icmp_ln45_7_reg_1098[0:0] == 1'b1) ? select_ln46_27_fu_856_p3 : 8'd0);

assign res_2_0_fu_905_p3 = ((icmp_ln45_8_reg_1122[0:0] == 1'b1) ? select_ln46_30_fu_898_p3 : 8'd0);

assign res_3_0_fu_947_p3 = ((icmp_ln45_9_reg_1146[0:0] == 1'b1) ? select_ln46_33_fu_940_p3 : 8'd0);

assign res_4_0_fu_989_p3 = ((icmp_ln45_10_reg_1170[0:0] == 1'b1) ? select_ln46_36_fu_982_p3 : 8'd0);

assign res_5_0_fu_1031_p3 = ((icmp_ln45_11_reg_1194[0:0] == 1'b1) ? select_ln46_39_fu_1024_p3 : 8'd0);

assign select_ln46_23_fu_806_p3 = ((or_ln46_23_fu_786_p2[0:0] == 1'b1) ? select_ln46_fu_800_p3 : 8'd255);

assign select_ln46_24_fu_814_p3 = ((or_ln46_24_fu_795_p2[0:0] == 1'b1) ? select_ln46_23_fu_806_p3 : add_ln46_reg_1086);

assign select_ln46_25_fu_842_p3 = ((tmp_48_reg_1103[0:0] == 1'b1) ? 8'd0 : add_ln46_7_reg_1110);

assign select_ln46_26_fu_848_p3 = ((or_ln46_26_fu_828_p2[0:0] == 1'b1) ? select_ln46_25_fu_842_p3 : 8'd255);

assign select_ln46_27_fu_856_p3 = ((or_ln46_27_fu_837_p2[0:0] == 1'b1) ? select_ln46_26_fu_848_p3 : add_ln46_7_reg_1110);

assign select_ln46_28_fu_884_p3 = ((tmp_53_reg_1127[0:0] == 1'b1) ? 8'd0 : add_ln46_8_reg_1134);

assign select_ln46_29_fu_890_p3 = ((or_ln46_29_fu_870_p2[0:0] == 1'b1) ? select_ln46_28_fu_884_p3 : 8'd255);

assign select_ln46_30_fu_898_p3 = ((or_ln46_30_fu_879_p2[0:0] == 1'b1) ? select_ln46_29_fu_890_p3 : add_ln46_8_reg_1134);

assign select_ln46_31_fu_926_p3 = ((tmp_59_reg_1151[0:0] == 1'b1) ? 8'd0 : add_ln46_9_reg_1158);

assign select_ln46_32_fu_932_p3 = ((or_ln46_32_fu_912_p2[0:0] == 1'b1) ? select_ln46_31_fu_926_p3 : 8'd255);

assign select_ln46_33_fu_940_p3 = ((or_ln46_33_fu_921_p2[0:0] == 1'b1) ? select_ln46_32_fu_932_p3 : add_ln46_9_reg_1158);

assign select_ln46_34_fu_968_p3 = ((tmp_65_reg_1175[0:0] == 1'b1) ? 8'd0 : add_ln46_10_reg_1182);

assign select_ln46_35_fu_974_p3 = ((or_ln46_35_fu_954_p2[0:0] == 1'b1) ? select_ln46_34_fu_968_p3 : 8'd255);

assign select_ln46_36_fu_982_p3 = ((or_ln46_36_fu_963_p2[0:0] == 1'b1) ? select_ln46_35_fu_974_p3 : add_ln46_10_reg_1182);

assign select_ln46_37_fu_1010_p3 = ((tmp_71_reg_1199[0:0] == 1'b1) ? 8'd0 : add_ln46_11_reg_1206);

assign select_ln46_38_fu_1016_p3 = ((or_ln46_38_fu_996_p2[0:0] == 1'b1) ? select_ln46_37_fu_1010_p3 : 8'd255);

assign select_ln46_39_fu_1024_p3 = ((or_ln46_39_fu_1005_p2[0:0] == 1'b1) ? select_ln46_38_fu_1016_p3 : add_ln46_11_reg_1206);

assign select_ln46_fu_800_p3 = ((tmp_reg_1079[0:0] == 1'b1) ? 8'd0 : add_ln46_reg_1086);

assign tmp_43_fu_280_p4 = {{data_1_val[15:10]}};

assign tmp_44_fu_114_p3 = data_0_val[32'd1];

assign tmp_45_fu_126_p3 = data_0_val[32'd9];

assign tmp_46_fu_134_p3 = data_0_val[32'd2];

assign tmp_47_fu_180_p3 = add_ln46_fu_158_p2[32'd7];

assign tmp_49_fu_230_p3 = data_1_val[32'd1];

assign tmp_50_fu_242_p3 = data_1_val[32'd9];

assign tmp_51_fu_250_p3 = data_1_val[32'd2];

assign tmp_52_fu_296_p3 = add_ln46_7_fu_274_p2[32'd7];

assign tmp_54_fu_346_p3 = data_2_val[32'd1];

assign tmp_55_fu_358_p3 = data_2_val[32'd9];

assign tmp_56_fu_366_p3 = data_2_val[32'd2];

assign tmp_57_fu_396_p4 = {{data_2_val[15:10]}};

assign tmp_58_fu_412_p3 = add_ln46_8_fu_390_p2[32'd7];

assign tmp_60_fu_462_p3 = data_3_val[32'd1];

assign tmp_61_fu_474_p3 = data_3_val[32'd9];

assign tmp_62_fu_482_p3 = data_3_val[32'd2];

assign tmp_63_fu_512_p4 = {{data_3_val[15:10]}};

assign tmp_64_fu_528_p3 = add_ln46_9_fu_506_p2[32'd7];

assign tmp_66_fu_578_p3 = data_4_val[32'd1];

assign tmp_67_fu_590_p3 = data_4_val[32'd9];

assign tmp_68_fu_598_p3 = data_4_val[32'd2];

assign tmp_69_fu_628_p4 = {{data_4_val[15:10]}};

assign tmp_70_fu_644_p3 = add_ln46_10_fu_622_p2[32'd7];

assign tmp_72_fu_694_p3 = data_5_val[32'd1];

assign tmp_73_fu_706_p3 = data_5_val[32'd9];

assign tmp_74_fu_714_p3 = data_5_val[32'd2];

assign tmp_75_fu_744_p4 = {{data_5_val[15:10]}};

assign tmp_76_fu_760_p3 = add_ln46_11_fu_738_p2[32'd7];

assign tmp_s_fu_164_p4 = {{data_0_val[15:10]}};

assign trunc_ln46_10_fu_238_p1 = data_1_val[0:0];

assign trunc_ln46_11_fu_354_p1 = data_2_val[0:0];

assign trunc_ln46_12_fu_470_p1 = data_3_val[0:0];

assign trunc_ln46_13_fu_586_p1 = data_4_val[0:0];

assign trunc_ln46_14_fu_702_p1 = data_5_val[0:0];

assign trunc_ln46_1_fu_684_p4 = {{data_5_val[9:2]}};

assign trunc_ln46_7_fu_220_p4 = {{data_1_val[9:2]}};

assign trunc_ln46_8_fu_336_p4 = {{data_2_val[9:2]}};

assign trunc_ln46_9_fu_452_p4 = {{data_3_val[9:2]}};

assign trunc_ln46_fu_122_p1 = data_0_val[0:0];

assign trunc_ln46_s_fu_568_p4 = {{data_4_val[9:2]}};

assign trunc_ln_fu_104_p4 = {{data_0_val[9:2]}};

assign xor_ln46_10_fu_958_p2 = (empty_42_reg_1188 ^ 1'd1);

assign xor_ln46_11_fu_1000_p2 = (empty_43_reg_1212 ^ 1'd1);

assign xor_ln46_7_fu_832_p2 = (empty_39_reg_1116 ^ 1'd1);

assign xor_ln46_8_fu_874_p2 = (empty_40_reg_1140 ^ 1'd1);

assign xor_ln46_9_fu_916_p2 = (empty_41_reg_1164 ^ 1'd1);

assign xor_ln46_fu_790_p2 = (empty_reg_1092 ^ 1'd1);

assign zext_ln46_10_fu_618_p1 = and_ln46_16_fu_612_p2;

assign zext_ln46_11_fu_734_p1 = and_ln46_18_fu_728_p2;

assign zext_ln46_7_fu_270_p1 = and_ln46_12_fu_264_p2;

assign zext_ln46_8_fu_386_p1 = and_ln46_13_fu_380_p2;

assign zext_ln46_9_fu_502_p1 = and_ln46_14_fu_496_p2;

assign zext_ln46_fu_154_p1 = and_ln46_fu_148_p2;

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config14_s
