// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config22_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [7:0] data_0_val;
input  [7:0] data_1_val;
input  [7:0] data_2_val;
input  [7:0] data_3_val;
output  [12:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg   [8:0] tmp_reg_273;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] tmp_2_reg_278;
reg   [9:0] tmp_3_reg_283;
reg   [10:0] trunc_ln_reg_288;
wire   [10:0] add_ln58_fu_243_p2;
reg   [10:0] add_ln58_reg_293;
wire   [11:0] add_ln58_2_fu_255_p2;
reg   [11:0] add_ln58_2_reg_298;
wire   [7:0] mul_ln73_fu_82_p0;
wire   [6:0] mul_ln73_fu_82_p1;
wire    ap_block_pp0_stage0;
wire   [7:0] mul_ln73_1_fu_85_p0;
wire   [7:0] mul_ln73_1_fu_85_p1;
wire   [13:0] mul_ln73_fu_82_p2;
wire   [14:0] mul_ln73_1_fu_85_p2;
wire   [13:0] tmp_127_fu_163_p3;
wire   [9:0] tmp_128_fu_175_p3;
wire   [14:0] zext_ln73_fu_171_p1;
wire   [14:0] zext_ln73_1_fu_183_p1;
wire   [14:0] add_ln73_fu_187_p2;
wire   [14:0] tmp_129_fu_203_p3;
wire   [15:0] zext_ln73_2_fu_211_p1;
wire   [15:0] sub_ln73_fu_215_p2;
wire   [10:0] p_cast_fu_231_p1;
wire   [10:0] p_cast1_fu_234_p1;
wire  signed [11:0] sext_ln58_fu_240_p1;
wire   [11:0] add_ln58_1_fu_249_p2;
wire   [11:0] p_cast2_fu_237_p1;
wire  signed [12:0] sext_ln58_1_fu_264_p1;
wire   [12:0] zext_ln58_fu_261_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [14:0] mul_ln73_1_fu_85_p00;
wire   [13:0] mul_ln73_fu_82_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

myproject_mul_8ns_7ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mul_8ns_7ns_14_1_1_U288(
    .din0(mul_ln73_fu_82_p0),
    .din1(mul_ln73_fu_82_p1),
    .dout(mul_ln73_fu_82_p2)
);

myproject_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U289(
    .din0(mul_ln73_1_fu_85_p0),
    .din1(mul_ln73_1_fu_85_p1),
    .dout(mul_ln73_1_fu_85_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_2_reg_298 <= add_ln58_2_fu_255_p2;
        add_ln58_reg_293 <= add_ln58_fu_243_p2;
        tmp_2_reg_278 <= {{mul_ln73_1_fu_85_p2[14:5]}};
        tmp_3_reg_283 <= {{add_ln73_fu_187_p2[14:5]}};
        tmp_reg_273 <= {{mul_ln73_fu_82_p2[13:5]}};
        trunc_ln_reg_288 <= {{sub_ln73_fu_215_p2[15:5]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_1_fu_249_p2 = ($signed(sext_ln58_fu_240_p1) + $signed(12'd4040));

assign add_ln58_2_fu_255_p2 = (add_ln58_1_fu_249_p2 + p_cast2_fu_237_p1);

assign add_ln58_fu_243_p2 = (p_cast_fu_231_p1 + p_cast1_fu_234_p1);

assign add_ln73_fu_187_p2 = (zext_ln73_fu_171_p1 + zext_ln73_1_fu_183_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ($signed(sext_ln58_1_fu_264_p1) + $signed(zext_ln58_fu_261_p1));

assign mul_ln73_1_fu_85_p0 = mul_ln73_1_fu_85_p00;

assign mul_ln73_1_fu_85_p00 = data_1_val;

assign mul_ln73_1_fu_85_p1 = 15'd105;

assign mul_ln73_fu_82_p0 = mul_ln73_fu_82_p00;

assign mul_ln73_fu_82_p00 = data_0_val;

assign mul_ln73_fu_82_p1 = 14'd55;

assign p_cast1_fu_234_p1 = tmp_2_reg_278;

assign p_cast2_fu_237_p1 = tmp_3_reg_283;

assign p_cast_fu_231_p1 = tmp_reg_273;

assign sext_ln58_1_fu_264_p1 = $signed(add_ln58_2_reg_298);

assign sext_ln58_fu_240_p1 = $signed(trunc_ln_reg_288);

assign sub_ln73_fu_215_p2 = (16'd0 - zext_ln73_2_fu_211_p1);

assign tmp_127_fu_163_p3 = {{data_2_val}, {6'd0}};

assign tmp_128_fu_175_p3 = {{data_2_val}, {2'd0}};

assign tmp_129_fu_203_p3 = {{data_3_val}, {7'd0}};

assign zext_ln58_fu_261_p1 = add_ln58_reg_293;

assign zext_ln73_1_fu_183_p1 = tmp_128_fu_175_p3;

assign zext_ln73_2_fu_211_p1 = tmp_129_fu_203_p3;

assign zext_ln73_fu_171_p1 = tmp_127_fu_163_p3;

endmodule //myproject_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config22_s
