// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config16_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;

reg  signed [15:0] data_1_val_read_reg_1112;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] data_0_val_read_reg_1121;
reg   [14:0] trunc_ln42_s_reg_1127;
reg   [15:0] trunc_ln42_6_reg_1132;
reg   [15:0] trunc_ln42_7_reg_1137;
reg   [15:0] trunc_ln42_8_reg_1142;
reg   [15:0] trunc_ln42_9_reg_1147;
reg   [14:0] trunc_ln42_13_reg_1152;
reg   [15:0] trunc_ln42_11_reg_1157;
reg   [14:0] trunc_ln42_14_reg_1162;
reg   [13:0] trunc_ln42_17_reg_1167;
reg   [13:0] trunc_ln42_18_reg_1172;
reg   [15:0] trunc_ln42_15_reg_1177;
reg   [15:0] trunc_ln42_15_reg_1177_pp0_iter1_reg;
reg   [15:0] trunc_ln42_16_reg_1182;
reg   [14:0] trunc_ln42_30_reg_1187;
reg   [13:0] trunc_ln42_31_reg_1192;
reg   [15:0] trunc_ln42_19_reg_1197;
reg   [15:0] trunc_ln42_20_reg_1202;
reg   [15:0] trunc_ln42_21_reg_1208;
reg   [15:0] trunc_ln42_22_reg_1213;
reg   [15:0] trunc_ln42_23_reg_1219;
reg   [15:0] trunc_ln42_24_reg_1224;
reg   [15:0] trunc_ln42_25_reg_1229;
reg   [15:0] trunc_ln42_26_reg_1234;
wire   [15:0] trunc_ln42_27_fu_712_p4;
reg   [15:0] trunc_ln42_27_reg_1239;
wire   [14:0] add_ln58_257_fu_732_p2;
reg   [14:0] add_ln58_257_reg_1244;
wire   [14:0] add_ln58_266_fu_748_p2;
reg   [14:0] add_ln58_266_reg_1249;
wire   [15:0] add_ln58_285_fu_764_p2;
reg   [15:0] add_ln58_285_reg_1254;
wire   [15:0] add_ln58_fu_932_p2;
reg   [15:0] add_ln58_reg_1259;
wire   [15:0] add_ln58_253_fu_942_p2;
reg   [15:0] add_ln58_253_reg_1264;
wire   [15:0] add_ln58_258_fu_956_p2;
reg   [15:0] add_ln58_258_reg_1269;
wire   [15:0] add_ln58_260_fu_962_p2;
reg   [15:0] add_ln58_260_reg_1274;
wire   [15:0] add_ln58_262_fu_972_p2;
reg   [15:0] add_ln58_262_reg_1279;
wire   [15:0] add_ln58_267_fu_984_p2;
reg   [15:0] add_ln58_267_reg_1284;
wire   [15:0] add_ln58_269_fu_990_p2;
reg   [15:0] add_ln58_269_reg_1289;
reg   [15:0] add_ln58_269_reg_1289_pp0_iter2_reg;
wire   [15:0] add_ln58_271_fu_1001_p2;
reg   [15:0] add_ln58_271_reg_1294;
reg   [15:0] add_ln58_271_reg_1294_pp0_iter2_reg;
wire   [15:0] add_ln58_273_fu_1006_p2;
reg   [15:0] add_ln58_273_reg_1299;
wire   [15:0] add_ln58_276_fu_1016_p2;
reg   [15:0] add_ln58_276_reg_1304;
wire   [15:0] add_ln58_279_fu_1021_p2;
reg   [15:0] add_ln58_279_reg_1309;
wire   [15:0] add_ln58_281_fu_1031_p2;
reg   [15:0] add_ln58_281_reg_1314;
wire   [15:0] add_ln58_286_fu_1041_p2;
reg   [15:0] add_ln58_286_reg_1319;
wire   [15:0] add_ln58_259_fu_1050_p2;
reg   [15:0] add_ln58_259_reg_1324;
wire   [15:0] add_ln58_268_fu_1059_p2;
reg   [15:0] add_ln58_268_reg_1329;
wire   [15:0] add_ln58_277_fu_1068_p2;
reg   [15:0] add_ln58_277_reg_1334;
wire   [15:0] add_ln58_287_fu_1077_p2;
reg   [15:0] add_ln58_287_reg_1339;
wire  signed [15:0] trunc_ln42_s_fu_144_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] trunc_ln_fu_154_p1;
wire   [12:0] trunc_ln_fu_154_p4;
wire  signed [15:0] trunc_ln42_10_fu_168_p1;
wire   [12:0] trunc_ln42_10_fu_168_p4;
wire  signed [15:0] sext_ln42_83_fu_182_p0;
wire  signed [15:0] tmp_153_fu_186_p1;
wire   [17:0] tmp_153_fu_186_p3;
wire  signed [18:0] sext_ln73_82_fu_194_p1;
wire  signed [18:0] sext_ln42_83_fu_182_p1;
wire   [18:0] sub_ln73_79_fu_198_p2;
wire   [18:0] add_ln42_fu_214_p2;
wire  signed [15:0] trunc_ln42_12_fu_230_p1;
wire   [12:0] trunc_ln42_12_fu_230_p4;
wire  signed [15:0] sext_ln42_84_fu_244_p0;
wire  signed [15:0] p_shl30_fu_248_p1;
wire  signed [18:0] sext_ln42_84_fu_244_p1;
wire   [18:0] p_shl30_fu_248_p3;
wire   [18:0] sub_ln42_55_fu_256_p2;
wire  signed [15:0] tmp_154_fu_272_p1;
wire   [17:0] tmp_154_fu_272_p3;
wire  signed [18:0] sext_ln73_83_fu_280_p1;
wire   [18:0] sub_ln73_80_fu_284_p2;
wire  signed [15:0] sext_ln42_85_fu_300_p0;
wire  signed [15:0] sext_ln42_86_fu_304_p0;
wire  signed [15:0] trunc_ln42_13_fu_308_p1;
wire  signed [15:0] p_shl29_fu_318_p1;
wire  signed [18:0] sext_ln42_85_fu_300_p1;
wire   [18:0] p_shl29_fu_318_p3;
wire   [18:0] sub_ln42_56_fu_326_p2;
wire  signed [15:0] tmp_155_fu_342_p1;
wire   [16:0] tmp_155_fu_342_p3;
wire  signed [17:0] sext_ln73_84_fu_350_p1;
wire   [17:0] sub_ln73_81_fu_354_p2;
wire  signed [16:0] sext_ln42_86_fu_304_p1;
wire   [16:0] sub_ln73_24_fu_370_p2;
wire  signed [15:0] sext_ln42_90_fu_386_p0;
wire  signed [15:0] sext_ln73_60_fu_390_p0;
wire  signed [16:0] sext_ln73_60_fu_390_p1;
wire   [16:0] sub_ln73_25_fu_394_p2;
wire  signed [15:0] trunc_ln42_28_fu_410_p1;
wire   [12:0] trunc_ln42_28_fu_410_p4;
wire  signed [15:0] tmp_156_fu_424_p1;
wire   [17:0] tmp_156_fu_424_p3;
wire  signed [18:0] sext_ln73_85_fu_432_p1;
wire  signed [18:0] sext_ln42_90_fu_386_p1;
wire   [18:0] sub_ln73_82_fu_436_p2;
wire   [18:0] add_ln42_4_fu_452_p2;
wire  signed [15:0] trunc_ln42_29_fu_468_p1;
wire   [12:0] trunc_ln42_29_fu_468_p4;
wire  signed [15:0] sext_ln73_63_fu_482_p0;
wire  signed [15:0] tmp_157_fu_486_p1;
wire   [16:0] tmp_157_fu_486_p3;
wire  signed [17:0] sext_ln73_86_fu_494_p1;
wire   [17:0] sub_ln73_83_fu_498_p2;
wire  signed [16:0] sext_ln73_63_fu_482_p1;
wire   [16:0] sub_ln73_26_fu_514_p2;
wire  signed [15:0] sext_ln73_65_fu_530_p0;
wire  signed [15:0] p_shl21_fu_534_p1;
wire   [18:0] p_shl21_fu_534_p3;
wire   [18:0] sub_ln42_57_fu_542_p2;
wire  signed [18:0] sext_ln73_65_fu_530_p1;
wire   [18:0] sub_ln42_58_fu_558_p2;
wire  signed [15:0] tmp_158_fu_574_p1;
wire   [16:0] tmp_158_fu_574_p3;
wire  signed [18:0] sext_ln42_94_fu_582_p1;
wire   [18:0] sub_ln42_59_fu_586_p2;
wire  signed [15:0] sext_ln73_66_fu_602_p0;
wire  signed [15:0] p_shl17_fu_606_p1;
wire   [18:0] p_shl17_fu_606_p3;
wire  signed [18:0] sext_ln73_66_fu_602_p1;
wire   [18:0] sub_ln42_60_fu_614_p2;
wire   [18:0] sub_ln42_61_fu_630_p2;
wire   [18:0] sub_ln42_62_fu_646_p2;
wire  signed [15:0] sext_ln73_67_fu_662_p0;
wire  signed [15:0] p_shl12_fu_666_p1;
wire  signed [18:0] sext_ln73_67_fu_662_p1;
wire   [18:0] p_shl12_fu_666_p3;
wire   [18:0] sub_ln42_63_fu_674_p2;
wire   [18:0] sub_ln42_64_fu_690_p2;
wire   [18:0] sub_ln42_65_fu_706_p2;
wire  signed [13:0] sext_ln73_62_fu_478_p1;
wire   [13:0] add_ln58_256_fu_722_p2;
wire  signed [14:0] sext_ln58_fu_728_p1;
wire  signed [14:0] sext_ln73_59_fu_240_p1;
wire  signed [13:0] sext_ln73_61_fu_420_p1;
wire   [13:0] add_ln58_265_fu_738_p2;
wire  signed [14:0] sext_ln58_46_fu_744_p1;
wire  signed [14:0] sext_ln73_58_fu_178_p1;
wire  signed [13:0] sext_ln70_fu_164_p1;
wire   [13:0] add_ln58_284_fu_754_p2;
wire  signed [15:0] sext_ln58_48_fu_760_p1;
wire  signed [16:0] sext_ln42_78_fu_770_p1;
wire   [16:0] sub_ln73_fu_776_p2;
wire   [13:0] trunc_ln42_1_fu_782_p4;
wire   [16:0] tmp_fu_796_p3;
wire  signed [17:0] sext_ln73_80_fu_803_p1;
wire   [17:0] sub_ln73_77_fu_807_p2;
wire   [14:0] trunc_ln42_2_fu_813_p4;
wire   [16:0] tmp_151_fu_840_p3;
wire   [18:0] p_shl_fu_833_p3;
wire  signed [18:0] sext_ln42_87_fu_847_p1;
wire   [18:0] sub_ln42_fu_851_p2;
wire   [17:0] tmp_152_fu_867_p3;
wire  signed [18:0] sext_ln42_81_fu_827_p1;
wire  signed [18:0] sext_ln73_81_fu_874_p1;
wire   [18:0] sub_ln73_78_fu_878_p2;
wire  signed [16:0] sext_ln73_fu_830_p1;
wire   [16:0] sub_ln73_23_fu_894_p2;
wire   [13:0] trunc_ln42_5_fu_900_p4;
wire   [15:0] trunc_ln42_3_fu_857_p4;
wire  signed [15:0] sext_ln42_91_fu_923_p1;
wire   [15:0] add_ln58_252_fu_938_p2;
wire  signed [15:0] sext_ln42_fu_773_p1;
wire  signed [15:0] sext_ln42_13_fu_914_p1;
wire  signed [15:0] sext_ln58_45_fu_953_p1;
wire   [15:0] add_ln58_255_fu_947_p2;
wire  signed [15:0] sext_ln42_79_fu_792_p1;
wire   [15:0] add_ln58_261_fu_968_p2;
wire  signed [15:0] sext_ln58_47_fu_981_p1;
wire   [15:0] add_ln58_264_fu_977_p2;
wire  signed [15:0] sext_ln42_80_fu_823_p1;
wire   [15:0] trunc_ln42_4_fu_884_p4;
wire  signed [15:0] sext_ln42_88_fu_917_p1;
wire   [15:0] add_ln58_270_fu_996_p2;
wire  signed [15:0] sext_ln42_92_fu_926_p1;
wire   [15:0] add_ln58_275_fu_1011_p2;
wire  signed [15:0] sext_ln42_82_fu_910_p1;
wire  signed [15:0] sext_ln42_93_fu_929_p1;
wire   [15:0] add_ln58_280_fu_1026_p2;
wire  signed [15:0] sext_ln42_89_fu_920_p1;
wire   [15:0] add_ln58_283_fu_1037_p2;
wire   [15:0] add_ln58_254_fu_1046_p2;
wire   [15:0] add_ln58_263_fu_1055_p2;
wire   [15:0] add_ln58_274_fu_1064_p2;
wire   [15:0] add_ln58_282_fu_1073_p2;
wire   [15:0] add_ln58_272_fu_1082_p2;
wire   [15:0] add_ln58_278_fu_1086_p2;
reg    ap_ce_reg;
reg   [15:0] data_0_val_int_reg;
reg   [15:0] data_1_val_int_reg;
reg   [15:0] data_2_val_int_reg;
reg   [15:0] data_3_val_int_reg;
reg   [15:0] data_4_val_int_reg;
reg   [15:0] data_5_val_int_reg;
reg   [15:0] data_6_val_int_reg;
reg   [15:0] data_7_val_int_reg;
reg   [15:0] data_8_val_int_reg;
reg   [15:0] data_9_val_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln58_253_reg_1264 <= add_ln58_253_fu_942_p2;
        add_ln58_257_reg_1244 <= add_ln58_257_fu_732_p2;
        add_ln58_258_reg_1269 <= add_ln58_258_fu_956_p2;
        add_ln58_259_reg_1324 <= add_ln58_259_fu_1050_p2;
        add_ln58_260_reg_1274 <= add_ln58_260_fu_962_p2;
        add_ln58_262_reg_1279 <= add_ln58_262_fu_972_p2;
        add_ln58_266_reg_1249 <= add_ln58_266_fu_748_p2;
        add_ln58_267_reg_1284 <= add_ln58_267_fu_984_p2;
        add_ln58_268_reg_1329 <= add_ln58_268_fu_1059_p2;
        add_ln58_269_reg_1289 <= add_ln58_269_fu_990_p2;
        add_ln58_269_reg_1289_pp0_iter2_reg <= add_ln58_269_reg_1289;
        add_ln58_271_reg_1294 <= add_ln58_271_fu_1001_p2;
        add_ln58_271_reg_1294_pp0_iter2_reg <= add_ln58_271_reg_1294;
        add_ln58_273_reg_1299 <= add_ln58_273_fu_1006_p2;
        add_ln58_276_reg_1304 <= add_ln58_276_fu_1016_p2;
        add_ln58_277_reg_1334 <= add_ln58_277_fu_1068_p2;
        add_ln58_279_reg_1309 <= add_ln58_279_fu_1021_p2;
        add_ln58_281_reg_1314 <= add_ln58_281_fu_1031_p2;
        add_ln58_285_reg_1254 <= add_ln58_285_fu_764_p2;
        add_ln58_286_reg_1319 <= add_ln58_286_fu_1041_p2;
        add_ln58_287_reg_1339 <= add_ln58_287_fu_1077_p2;
        add_ln58_reg_1259 <= add_ln58_fu_932_p2;
        data_0_val_read_reg_1121 <= data_0_val_int_reg;
        data_1_val_read_reg_1112 <= data_1_val_int_reg;
        trunc_ln42_11_reg_1157 <= {{sub_ln42_56_fu_326_p2[18:3]}};
        trunc_ln42_13_reg_1152 <= {{trunc_ln42_13_fu_308_p1[15:1]}};
        trunc_ln42_14_reg_1162 <= {{sub_ln73_81_fu_354_p2[17:3]}};
        trunc_ln42_15_reg_1177 <= {{sub_ln73_82_fu_436_p2[18:3]}};
        trunc_ln42_15_reg_1177_pp0_iter1_reg <= trunc_ln42_15_reg_1177;
        trunc_ln42_16_reg_1182 <= {{add_ln42_4_fu_452_p2[18:3]}};
        trunc_ln42_17_reg_1167 <= {{sub_ln73_24_fu_370_p2[16:3]}};
        trunc_ln42_18_reg_1172 <= {{sub_ln73_25_fu_394_p2[16:3]}};
        trunc_ln42_19_reg_1197 <= {{sub_ln42_57_fu_542_p2[18:3]}};
        trunc_ln42_20_reg_1202 <= {{sub_ln42_58_fu_558_p2[18:3]}};
        trunc_ln42_21_reg_1208 <= {{sub_ln42_59_fu_586_p2[18:3]}};
        trunc_ln42_22_reg_1213 <= {{sub_ln42_60_fu_614_p2[18:3]}};
        trunc_ln42_23_reg_1219 <= {{sub_ln42_61_fu_630_p2[18:3]}};
        trunc_ln42_24_reg_1224 <= {{sub_ln42_62_fu_646_p2[18:3]}};
        trunc_ln42_25_reg_1229 <= {{sub_ln42_63_fu_674_p2[18:3]}};
        trunc_ln42_26_reg_1234 <= {{sub_ln42_64_fu_690_p2[18:3]}};
        trunc_ln42_27_reg_1239 <= {{sub_ln42_65_fu_706_p2[18:3]}};
        trunc_ln42_30_reg_1187 <= {{sub_ln73_83_fu_498_p2[17:3]}};
        trunc_ln42_31_reg_1192 <= {{sub_ln73_26_fu_514_p2[16:3]}};
        trunc_ln42_6_reg_1132 <= {{sub_ln73_79_fu_198_p2[18:3]}};
        trunc_ln42_7_reg_1137 <= {{add_ln42_fu_214_p2[18:3]}};
        trunc_ln42_8_reg_1142 <= {{sub_ln42_55_fu_256_p2[18:3]}};
        trunc_ln42_9_reg_1147 <= {{sub_ln73_80_fu_284_p2[18:3]}};
        trunc_ln42_s_reg_1127 <= {{trunc_ln42_s_fu_144_p1[15:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln58_259_reg_1324;
        ap_return_1_int_reg <= add_ln58_268_reg_1329;
        ap_return_2_int_reg <= add_ln58_278_fu_1086_p2;
        ap_return_3_int_reg <= add_ln58_287_reg_1339;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_val_int_reg <= data_0_val;
        data_1_val_int_reg <= data_1_val;
        data_2_val_int_reg <= data_2_val;
        data_3_val_int_reg <= data_3_val;
        data_4_val_int_reg <= data_4_val;
        data_5_val_int_reg <= data_5_val;
        data_6_val_int_reg <= data_6_val;
        data_7_val_int_reg <= data_7_val;
        data_8_val_int_reg <= data_8_val;
        data_9_val_int_reg <= data_9_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln58_259_reg_1324;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln58_268_reg_1329;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln58_278_fu_1086_p2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln58_287_reg_1339;
    end else begin
        ap_return_3 = 'bx;
    end
end

assign add_ln42_4_fu_452_p2 = ($signed(sext_ln73_85_fu_432_p1) + $signed(sext_ln42_90_fu_386_p1));

assign add_ln42_fu_214_p2 = ($signed(sext_ln73_82_fu_194_p1) + $signed(sext_ln42_83_fu_182_p1));

assign add_ln58_252_fu_938_p2 = (trunc_ln42_22_reg_1213 + trunc_ln42_25_reg_1229);

assign add_ln58_253_fu_942_p2 = (add_ln58_252_fu_938_p2 + trunc_ln42_19_reg_1197);

assign add_ln58_254_fu_1046_p2 = (add_ln58_253_reg_1264 + add_ln58_reg_1259);

assign add_ln58_255_fu_947_p2 = ($signed(sext_ln42_fu_773_p1) + $signed(sext_ln42_13_fu_914_p1));

assign add_ln58_256_fu_722_p2 = ($signed(sext_ln73_62_fu_478_p1) + $signed(14'd16256));

assign add_ln58_257_fu_732_p2 = ($signed(sext_ln58_fu_728_p1) + $signed(sext_ln73_59_fu_240_p1));

assign add_ln58_258_fu_956_p2 = ($signed(sext_ln58_45_fu_953_p1) + $signed(add_ln58_255_fu_947_p2));

assign add_ln58_259_fu_1050_p2 = (add_ln58_258_reg_1269 + add_ln58_254_fu_1046_p2);

assign add_ln58_260_fu_962_p2 = ($signed(sext_ln42_79_fu_792_p1) + $signed(trunc_ln42_3_fu_857_p4));

assign add_ln58_261_fu_968_p2 = (trunc_ln42_11_reg_1157 + trunc_ln42_20_reg_1202);

assign add_ln58_262_fu_972_p2 = (add_ln58_261_fu_968_p2 + trunc_ln42_8_reg_1142);

assign add_ln58_263_fu_1055_p2 = (add_ln58_262_reg_1279 + add_ln58_260_reg_1274);

assign add_ln58_264_fu_977_p2 = (trunc_ln42_22_reg_1213 + trunc_ln42_26_reg_1234);

assign add_ln58_265_fu_738_p2 = ($signed(sext_ln73_61_fu_420_p1) + $signed(14'd16128));

assign add_ln58_266_fu_748_p2 = ($signed(sext_ln58_46_fu_744_p1) + $signed(sext_ln73_58_fu_178_p1));

assign add_ln58_267_fu_984_p2 = ($signed(sext_ln58_47_fu_981_p1) + $signed(add_ln58_264_fu_977_p2));

assign add_ln58_268_fu_1059_p2 = (add_ln58_267_reg_1284 + add_ln58_263_fu_1055_p2);

assign add_ln58_269_fu_990_p2 = ($signed(sext_ln42_80_fu_823_p1) + $signed(trunc_ln42_4_fu_884_p4));

assign add_ln58_270_fu_996_p2 = ($signed(trunc_ln42_9_reg_1147) + $signed(sext_ln42_88_fu_917_p1));

assign add_ln58_271_fu_1001_p2 = (add_ln58_270_fu_996_p2 + trunc_ln42_6_reg_1132);

assign add_ln58_272_fu_1082_p2 = (add_ln58_271_reg_1294_pp0_iter2_reg + add_ln58_269_reg_1289_pp0_iter2_reg);

assign add_ln58_273_fu_1006_p2 = ($signed(sext_ln42_92_fu_926_p1) + $signed(trunc_ln42_20_reg_1202));

assign add_ln58_274_fu_1064_p2 = (add_ln58_273_reg_1299 + trunc_ln42_15_reg_1177_pp0_iter1_reg);

assign add_ln58_275_fu_1011_p2 = (trunc_ln42_27_reg_1239 + 16'd512);

assign add_ln58_276_fu_1016_p2 = (add_ln58_275_fu_1011_p2 + trunc_ln42_23_reg_1219);

assign add_ln58_277_fu_1068_p2 = (add_ln58_276_reg_1304 + add_ln58_274_fu_1064_p2);

assign add_ln58_278_fu_1086_p2 = (add_ln58_277_reg_1334 + add_ln58_272_fu_1082_p2);

assign add_ln58_279_fu_1021_p2 = ($signed(sext_ln42_82_fu_910_p1) + $signed(trunc_ln42_7_reg_1137));

assign add_ln58_280_fu_1026_p2 = ($signed(trunc_ln42_16_reg_1182) + $signed(sext_ln42_93_fu_929_p1));

assign add_ln58_281_fu_1031_p2 = ($signed(add_ln58_280_fu_1026_p2) + $signed(sext_ln42_89_fu_920_p1));

assign add_ln58_282_fu_1073_p2 = (add_ln58_281_reg_1314 + add_ln58_279_reg_1309);

assign add_ln58_283_fu_1037_p2 = (trunc_ln42_21_reg_1208 + trunc_ln42_24_reg_1224);

assign add_ln58_284_fu_754_p2 = ($signed(sext_ln70_fu_164_p1) + $signed(14'd128));

assign add_ln58_285_fu_764_p2 = ($signed(sext_ln58_48_fu_760_p1) + $signed(trunc_ln42_27_fu_712_p4));

assign add_ln58_286_fu_1041_p2 = (add_ln58_285_reg_1254 + add_ln58_283_fu_1037_p2);

assign add_ln58_287_fu_1077_p2 = (add_ln58_286_reg_1319 + add_ln58_282_fu_1073_p2);

assign add_ln58_fu_932_p2 = ($signed(trunc_ln42_3_fu_857_p4) + $signed(sext_ln42_91_fu_923_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign p_shl12_fu_666_p1 = data_9_val_int_reg;

assign p_shl12_fu_666_p3 = {{p_shl12_fu_666_p1}, {3'd0}};

assign p_shl17_fu_606_p1 = data_8_val_int_reg;

assign p_shl17_fu_606_p3 = {{p_shl17_fu_606_p1}, {3'd0}};

assign p_shl21_fu_534_p1 = data_7_val_int_reg;

assign p_shl21_fu_534_p3 = {{p_shl21_fu_534_p1}, {3'd0}};

assign p_shl29_fu_318_p1 = data_4_val_int_reg;

assign p_shl29_fu_318_p3 = {{p_shl29_fu_318_p1}, {3'd0}};

assign p_shl30_fu_248_p1 = data_3_val_int_reg;

assign p_shl30_fu_248_p3 = {{p_shl30_fu_248_p1}, {3'd0}};

assign p_shl_fu_833_p3 = {{data_1_val_read_reg_1112}, {3'd0}};

assign sext_ln42_13_fu_914_p1 = $signed(trunc_ln42_13_reg_1152);

assign sext_ln42_78_fu_770_p1 = data_0_val_read_reg_1121;

assign sext_ln42_79_fu_792_p1 = $signed(trunc_ln42_1_fu_782_p4);

assign sext_ln42_80_fu_823_p1 = $signed(trunc_ln42_2_fu_813_p4);

assign sext_ln42_81_fu_827_p1 = data_1_val_read_reg_1112;

assign sext_ln42_82_fu_910_p1 = $signed(trunc_ln42_5_fu_900_p4);

assign sext_ln42_83_fu_182_p0 = data_2_val_int_reg;

assign sext_ln42_83_fu_182_p1 = sext_ln42_83_fu_182_p0;

assign sext_ln42_84_fu_244_p0 = data_3_val_int_reg;

assign sext_ln42_84_fu_244_p1 = sext_ln42_84_fu_244_p0;

assign sext_ln42_85_fu_300_p0 = data_4_val_int_reg;

assign sext_ln42_85_fu_300_p1 = sext_ln42_85_fu_300_p0;

assign sext_ln42_86_fu_304_p0 = data_4_val_int_reg;

assign sext_ln42_86_fu_304_p1 = sext_ln42_86_fu_304_p0;

assign sext_ln42_87_fu_847_p1 = $signed(tmp_151_fu_840_p3);

assign sext_ln42_88_fu_917_p1 = $signed(trunc_ln42_14_reg_1162);

assign sext_ln42_89_fu_920_p1 = $signed(trunc_ln42_17_reg_1167);

assign sext_ln42_90_fu_386_p0 = data_5_val_int_reg;

assign sext_ln42_90_fu_386_p1 = sext_ln42_90_fu_386_p0;

assign sext_ln42_91_fu_923_p1 = $signed(trunc_ln42_18_reg_1172);

assign sext_ln42_92_fu_926_p1 = $signed(trunc_ln42_30_reg_1187);

assign sext_ln42_93_fu_929_p1 = $signed(trunc_ln42_31_reg_1192);

assign sext_ln42_94_fu_582_p1 = $signed(tmp_158_fu_574_p3);

assign sext_ln42_fu_773_p1 = $signed(trunc_ln42_s_reg_1127);

assign sext_ln58_45_fu_953_p1 = $signed(add_ln58_257_reg_1244);

assign sext_ln58_46_fu_744_p1 = $signed(add_ln58_265_fu_738_p2);

assign sext_ln58_47_fu_981_p1 = $signed(add_ln58_266_reg_1249);

assign sext_ln58_48_fu_760_p1 = $signed(add_ln58_284_fu_754_p2);

assign sext_ln58_fu_728_p1 = $signed(add_ln58_256_fu_722_p2);

assign sext_ln70_fu_164_p1 = $signed(trunc_ln_fu_154_p4);

assign sext_ln73_58_fu_178_p1 = $signed(trunc_ln42_10_fu_168_p4);

assign sext_ln73_59_fu_240_p1 = $signed(trunc_ln42_12_fu_230_p4);

assign sext_ln73_60_fu_390_p0 = data_5_val_int_reg;

assign sext_ln73_60_fu_390_p1 = sext_ln73_60_fu_390_p0;

assign sext_ln73_61_fu_420_p1 = $signed(trunc_ln42_28_fu_410_p4);

assign sext_ln73_62_fu_478_p1 = $signed(trunc_ln42_29_fu_468_p4);

assign sext_ln73_63_fu_482_p0 = data_6_val_int_reg;

assign sext_ln73_63_fu_482_p1 = sext_ln73_63_fu_482_p0;

assign sext_ln73_65_fu_530_p0 = data_7_val_int_reg;

assign sext_ln73_65_fu_530_p1 = sext_ln73_65_fu_530_p0;

assign sext_ln73_66_fu_602_p0 = data_8_val_int_reg;

assign sext_ln73_66_fu_602_p1 = sext_ln73_66_fu_602_p0;

assign sext_ln73_67_fu_662_p0 = data_9_val_int_reg;

assign sext_ln73_67_fu_662_p1 = sext_ln73_67_fu_662_p0;

assign sext_ln73_80_fu_803_p1 = $signed(tmp_fu_796_p3);

assign sext_ln73_81_fu_874_p1 = $signed(tmp_152_fu_867_p3);

assign sext_ln73_82_fu_194_p1 = $signed(tmp_153_fu_186_p3);

assign sext_ln73_83_fu_280_p1 = $signed(tmp_154_fu_272_p3);

assign sext_ln73_84_fu_350_p1 = $signed(tmp_155_fu_342_p3);

assign sext_ln73_85_fu_432_p1 = $signed(tmp_156_fu_424_p3);

assign sext_ln73_86_fu_494_p1 = $signed(tmp_157_fu_486_p3);

assign sext_ln73_fu_830_p1 = data_1_val_read_reg_1112;

assign sub_ln42_55_fu_256_p2 = ($signed(sext_ln42_84_fu_244_p1) - $signed(p_shl30_fu_248_p3));

assign sub_ln42_56_fu_326_p2 = ($signed(sext_ln42_85_fu_300_p1) - $signed(p_shl29_fu_318_p3));

assign sub_ln42_57_fu_542_p2 = (19'd0 - p_shl21_fu_534_p3);

assign sub_ln42_58_fu_558_p2 = ($signed(p_shl21_fu_534_p3) - $signed(sext_ln73_65_fu_530_p1));

assign sub_ln42_59_fu_586_p2 = ($signed(p_shl21_fu_534_p3) - $signed(sext_ln42_94_fu_582_p1));

assign sub_ln42_60_fu_614_p2 = ($signed(p_shl17_fu_606_p3) - $signed(sext_ln73_66_fu_602_p1));

assign sub_ln42_61_fu_630_p2 = ($signed(sext_ln73_66_fu_602_p1) - $signed(p_shl17_fu_606_p3));

assign sub_ln42_62_fu_646_p2 = (19'd0 - p_shl17_fu_606_p3);

assign sub_ln42_63_fu_674_p2 = ($signed(sext_ln73_67_fu_662_p1) - $signed(p_shl12_fu_666_p3));

assign sub_ln42_64_fu_690_p2 = (19'd0 - p_shl12_fu_666_p3);

assign sub_ln42_65_fu_706_p2 = ($signed(p_shl12_fu_666_p3) - $signed(sext_ln73_67_fu_662_p1));

assign sub_ln42_fu_851_p2 = ($signed(p_shl_fu_833_p3) - $signed(sext_ln42_87_fu_847_p1));

assign sub_ln73_23_fu_894_p2 = ($signed(17'd0) - $signed(sext_ln73_fu_830_p1));

assign sub_ln73_24_fu_370_p2 = ($signed(17'd0) - $signed(sext_ln42_86_fu_304_p1));

assign sub_ln73_25_fu_394_p2 = ($signed(17'd0) - $signed(sext_ln73_60_fu_390_p1));

assign sub_ln73_26_fu_514_p2 = ($signed(17'd0) - $signed(sext_ln73_63_fu_482_p1));

assign sub_ln73_77_fu_807_p2 = ($signed(18'd0) - $signed(sext_ln73_80_fu_803_p1));

assign sub_ln73_78_fu_878_p2 = ($signed(sext_ln42_81_fu_827_p1) - $signed(sext_ln73_81_fu_874_p1));

assign sub_ln73_79_fu_198_p2 = ($signed(sext_ln73_82_fu_194_p1) - $signed(sext_ln42_83_fu_182_p1));

assign sub_ln73_80_fu_284_p2 = ($signed(sext_ln42_84_fu_244_p1) - $signed(sext_ln73_83_fu_280_p1));

assign sub_ln73_81_fu_354_p2 = ($signed(18'd0) - $signed(sext_ln73_84_fu_350_p1));

assign sub_ln73_82_fu_436_p2 = ($signed(sext_ln73_85_fu_432_p1) - $signed(sext_ln42_90_fu_386_p1));

assign sub_ln73_83_fu_498_p2 = ($signed(18'd0) - $signed(sext_ln73_86_fu_494_p1));

assign sub_ln73_fu_776_p2 = ($signed(17'd0) - $signed(sext_ln42_78_fu_770_p1));

assign tmp_151_fu_840_p3 = {{data_1_val_read_reg_1112}, {1'd0}};

assign tmp_152_fu_867_p3 = {{data_1_val_read_reg_1112}, {2'd0}};

assign tmp_153_fu_186_p1 = data_2_val_int_reg;

assign tmp_153_fu_186_p3 = {{tmp_153_fu_186_p1}, {2'd0}};

assign tmp_154_fu_272_p1 = data_3_val_int_reg;

assign tmp_154_fu_272_p3 = {{tmp_154_fu_272_p1}, {2'd0}};

assign tmp_155_fu_342_p1 = data_4_val_int_reg;

assign tmp_155_fu_342_p3 = {{tmp_155_fu_342_p1}, {1'd0}};

assign tmp_156_fu_424_p1 = data_5_val_int_reg;

assign tmp_156_fu_424_p3 = {{tmp_156_fu_424_p1}, {2'd0}};

assign tmp_157_fu_486_p1 = data_6_val_int_reg;

assign tmp_157_fu_486_p3 = {{tmp_157_fu_486_p1}, {1'd0}};

assign tmp_158_fu_574_p1 = data_7_val_int_reg;

assign tmp_158_fu_574_p3 = {{tmp_158_fu_574_p1}, {1'd0}};

assign tmp_fu_796_p3 = {{data_0_val_read_reg_1121}, {1'd0}};

assign trunc_ln42_10_fu_168_p1 = data_2_val_int_reg;

assign trunc_ln42_10_fu_168_p4 = {{trunc_ln42_10_fu_168_p1[15:3]}};

assign trunc_ln42_12_fu_230_p1 = data_3_val_int_reg;

assign trunc_ln42_12_fu_230_p4 = {{trunc_ln42_12_fu_230_p1[15:3]}};

assign trunc_ln42_13_fu_308_p1 = data_4_val_int_reg;

assign trunc_ln42_1_fu_782_p4 = {{sub_ln73_fu_776_p2[16:3]}};

assign trunc_ln42_27_fu_712_p4 = {{sub_ln42_65_fu_706_p2[18:3]}};

assign trunc_ln42_28_fu_410_p1 = data_5_val_int_reg;

assign trunc_ln42_28_fu_410_p4 = {{trunc_ln42_28_fu_410_p1[15:3]}};

assign trunc_ln42_29_fu_468_p1 = data_6_val_int_reg;

assign trunc_ln42_29_fu_468_p4 = {{trunc_ln42_29_fu_468_p1[15:3]}};

assign trunc_ln42_2_fu_813_p4 = {{sub_ln73_77_fu_807_p2[17:3]}};

assign trunc_ln42_3_fu_857_p4 = {{sub_ln42_fu_851_p2[18:3]}};

assign trunc_ln42_4_fu_884_p4 = {{sub_ln73_78_fu_878_p2[18:3]}};

assign trunc_ln42_5_fu_900_p4 = {{sub_ln73_23_fu_894_p2[16:3]}};

assign trunc_ln42_s_fu_144_p1 = data_0_val_int_reg;

assign trunc_ln_fu_154_p1 = data_0_val_int_reg;

assign trunc_ln_fu_154_p4 = {{trunc_ln_fu_154_p1[15:3]}};

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config16_s
