Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    add_channel:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    cluster:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    concat_all:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    concat_scalars_1:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    concat_scalars_2:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    conv2d:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      ReuseFactor: 64
      Strategy: Resource
      Trace: false
    conv2d_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      ReuseFactor: 64
      Strategy: Resource
      Trace: false
    conv2d_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 64
      Strategy: Resource
      Trace: false
    dense_scalars:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    dense_scalars_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    dense_scalars_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    flatten_vol:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    merged_dense1:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    merged_dense1_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    merged_dense1_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    merged_dense2:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    merged_dense2_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    merged_dense2_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    nModule:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    output:
      Precision:
        result: fixed<8,1,RND_CONV,SAT>
        shift: fixed<16,6>
        slope: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    output_dense:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    output_dense_linear:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    pool2d_1:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    x_local:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
    y_local:
      Precision:
        result: fixed<16,6>
      ReuseFactor: 8
      Strategy: Resource
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model '../model3_4bit__pareto_roc_selected/hls_quick_trial_008/keras_model.h5'
OutputDir: ../model3_4bit__pareto_roc_selected/hls_quick_trial_008
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: Af5BFbEA
Version: 1.0.0
