// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [7:0] data_0_val;
input  [7:0] data_1_val;
input  [7:0] data_2_val;
input  [7:0] data_3_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg   [9:0] lshr_ln42_4_reg_661;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] trunc_ln42_3_reg_666;
reg   [9:0] trunc_ln42_6_reg_671;
wire   [10:0] add_ln58_fu_486_p2;
reg   [10:0] add_ln58_reg_676;
wire   [11:0] add_ln58_4_fu_492_p2;
reg   [11:0] add_ln58_4_reg_681;
wire   [11:0] add_ln58_6_fu_498_p2;
reg   [11:0] add_ln58_6_reg_686;
wire   [11:0] add_ln58_8_fu_504_p2;
reg   [11:0] add_ln58_8_reg_691;
reg   [11:0] add_ln58_8_reg_691_pp0_iter1_reg;
wire   [11:0] add_ln58_12_fu_510_p2;
reg   [11:0] add_ln58_12_reg_696;
wire   [11:0] add_ln58_13_fu_552_p2;
reg   [11:0] add_ln58_13_reg_701;
wire   [12:0] add_ln58_5_fu_573_p2;
reg   [12:0] add_ln58_5_reg_706;
wire   [12:0] add_ln58_7_fu_582_p2;
reg   [12:0] add_ln58_7_reg_711;
wire   [10:0] add_ln58_10_fu_594_p2;
reg   [10:0] add_ln58_10_reg_716;
wire   [12:0] add_ln58_14_fu_606_p2;
reg   [12:0] add_ln58_14_reg_721;
wire    ap_block_pp0_stage0;
wire   [8:0] tmp_fu_98_p3;
wire   [9:0] zext_ln73_2_fu_106_p1;
wire   [9:0] sub_ln73_5_fu_110_p2;
wire   [8:0] trunc_ln_fu_116_p4;
wire   [10:0] p_shl1_fu_130_p3;
wire   [10:0] zext_ln73_fu_94_p1;
wire   [10:0] sub_ln73_6_fu_138_p2;
wire   [9:0] lshr_ln_fu_144_p4;
wire   [11:0] zext_ln73_4_fu_158_p1;
wire   [11:0] sub_ln73_7_fu_162_p2;
wire   [10:0] trunc_ln42_2_fu_168_p4;
wire   [10:0] p_shl2_fu_186_p3;
wire   [10:0] zext_ln73_5_fu_182_p1;
wire   [10:0] sub_ln73_8_fu_194_p2;
wire   [9:0] lshr_ln42_2_fu_200_p4;
wire   [8:0] tmp_98_fu_214_p3;
wire   [9:0] zext_ln73_6_fu_222_p1;
wire   [9:0] sub_ln73_9_fu_226_p2;
wire   [8:0] trunc_ln42_s_fu_232_p4;
wire   [11:0] zext_ln73_7_fu_246_p1;
wire   [11:0] sub_ln73_10_fu_250_p2;
wire   [10:0] trunc_ln42_4_fu_256_p4;
wire   [9:0] tmp_99_fu_270_p3;
wire   [10:0] zext_ln73_13_fu_278_p1;
wire   [10:0] sub_ln73_11_fu_282_p2;
wire   [9:0] trunc_ln42_1_fu_288_p4;
wire   [9:0] tmp_100_fu_310_p3;
wire   [10:0] zext_ln73_14_fu_318_p1;
wire   [10:0] zext_ln73_9_fu_306_p1;
wire   [10:0] add_ln73_fu_322_p2;
wire   [9:0] lshr_ln42_3_fu_328_p4;
wire   [10:0] p_shl3_fu_342_p3;
wire   [10:0] sub_ln73_12_fu_350_p2;
wire   [8:0] zext_ln73_8_fu_302_p1;
wire   [8:0] sub_ln73_fu_366_p2;
wire   [10:0] sub_ln73_13_fu_382_p2;
wire   [9:0] trunc_ln42_5_fu_388_p4;
wire   [10:0] p_shl4_fu_406_p3;
wire   [10:0] zext_ln73_11_fu_402_p1;
wire   [10:0] sub_ln73_14_fu_414_p2;
wire   [9:0] lshr_ln42_5_fu_420_p4;
wire   [11:0] zext_ln73_15_fu_434_p1;
wire   [11:0] sub_ln73_15_fu_438_p2;
wire   [10:0] trunc_ln42_8_fu_444_p4;
wire   [9:0] tmp_101_fu_458_p3;
wire   [10:0] zext_ln73_16_fu_466_p1;
wire   [10:0] sub_ln73_16_fu_470_p2;
wire   [10:0] zext_ln42_fu_210_p1;
wire   [10:0] zext_ln42_2_fu_338_p1;
wire   [11:0] zext_ln73_12_fu_430_p1;
wire  signed [11:0] sext_ln73_fu_126_p1;
wire  signed [11:0] sext_ln73_1_fu_242_p1;
wire  signed [11:0] sext_ln73_4_fu_454_p1;
wire   [11:0] zext_ln73_3_fu_154_p1;
wire  signed [11:0] sext_ln73_2_fu_266_p1;
wire  signed [11:0] sext_ln70_fu_178_p1;
wire  signed [11:0] sext_ln70_1_fu_298_p1;
wire   [0:0] bit_sel_fu_516_p3;
wire   [0:0] xor_ln58_fu_524_p2;
wire   [8:0] part_sel_fu_530_p4;
wire   [9:0] add_ln58_s_fu_540_p3;
wire   [11:0] zext_ln58_1_fu_548_p1;
wire  signed [11:0] sext_ln70_2_fu_398_p1;
wire  signed [12:0] sext_ln58_1_fu_570_p1;
wire   [12:0] zext_ln58_fu_567_p1;
wire  signed [12:0] sext_ln58_3_fu_579_p1;
wire   [12:0] zext_ln73_10_fu_558_p1;
wire  signed [10:0] sext_ln58_fu_564_p1;
wire   [10:0] add_ln58_9_fu_588_p2;
wire  signed [10:0] sext_ln73_3_fu_561_p1;
wire  signed [12:0] sext_ln58_9_fu_603_p1;
wire  signed [12:0] sext_ln58_8_fu_600_p1;
wire  signed [12:0] sext_ln58_6_fu_621_p1;
wire  signed [12:0] sext_ln58_5_fu_618_p1;
wire   [12:0] add_ln58_11_fu_624_p2;
wire  signed [15:0] sext_ln58_2_fu_612_p1;
wire  signed [15:0] sext_ln58_4_fu_615_p1;
wire  signed [15:0] sext_ln58_7_fu_630_p1;
wire  signed [15:0] sext_ln68_fu_634_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_10_reg_716 <= add_ln58_10_fu_594_p2;
        add_ln58_12_reg_696 <= add_ln58_12_fu_510_p2;
        add_ln58_13_reg_701 <= add_ln58_13_fu_552_p2;
        add_ln58_14_reg_721 <= add_ln58_14_fu_606_p2;
        add_ln58_4_reg_681 <= add_ln58_4_fu_492_p2;
        add_ln58_5_reg_706 <= add_ln58_5_fu_573_p2;
        add_ln58_6_reg_686 <= add_ln58_6_fu_498_p2;
        add_ln58_7_reg_711 <= add_ln58_7_fu_582_p2;
        add_ln58_8_reg_691 <= add_ln58_8_fu_504_p2;
        add_ln58_8_reg_691_pp0_iter1_reg <= add_ln58_8_reg_691;
        add_ln58_reg_676 <= add_ln58_fu_486_p2;
        lshr_ln42_4_reg_661 <= {{sub_ln73_12_fu_350_p2[10:1]}};
        trunc_ln42_3_reg_666 <= {{sub_ln73_fu_366_p2[8:1]}};
        trunc_ln42_6_reg_671 <= {{sub_ln73_16_fu_470_p2[10:1]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_10_fu_594_p2 = ($signed(add_ln58_9_fu_588_p2) + $signed(sext_ln73_3_fu_561_p1));

assign add_ln58_11_fu_624_p2 = ($signed(sext_ln58_6_fu_621_p1) + $signed(sext_ln58_5_fu_618_p1));

assign add_ln58_12_fu_510_p2 = ($signed(sext_ln70_fu_178_p1) + $signed(sext_ln70_1_fu_298_p1));

assign add_ln58_13_fu_552_p2 = ($signed(zext_ln58_1_fu_548_p1) + $signed(sext_ln70_2_fu_398_p1));

assign add_ln58_14_fu_606_p2 = ($signed(sext_ln58_9_fu_603_p1) + $signed(sext_ln58_8_fu_600_p1));

assign add_ln58_4_fu_492_p2 = ($signed(zext_ln73_12_fu_430_p1) + $signed(sext_ln73_fu_126_p1));

assign add_ln58_5_fu_573_p2 = ($signed(sext_ln58_1_fu_570_p1) + $signed(zext_ln58_fu_567_p1));

assign add_ln58_6_fu_498_p2 = ($signed(sext_ln73_1_fu_242_p1) + $signed(sext_ln73_4_fu_454_p1));

assign add_ln58_7_fu_582_p2 = ($signed(sext_ln58_3_fu_579_p1) + $signed(zext_ln73_10_fu_558_p1));

assign add_ln58_8_fu_504_p2 = ($signed(zext_ln73_3_fu_154_p1) + $signed(sext_ln73_2_fu_266_p1));

assign add_ln58_9_fu_588_p2 = ($signed(sext_ln58_fu_564_p1) + $signed(11'd1664));

assign add_ln58_fu_486_p2 = (zext_ln42_fu_210_p1 + zext_ln42_2_fu_338_p1);

assign add_ln58_s_fu_540_p3 = {{xor_ln58_fu_524_p2}, {part_sel_fu_530_p4}};

assign add_ln73_fu_322_p2 = (zext_ln73_14_fu_318_p1 + zext_ln73_9_fu_306_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = sext_ln58_2_fu_612_p1;

assign ap_return_1 = sext_ln58_4_fu_615_p1;

assign ap_return_2 = sext_ln58_7_fu_630_p1;

assign ap_return_3 = sext_ln68_fu_634_p1;

assign bit_sel_fu_516_p3 = sub_ln73_16_fu_470_p2[32'd10];

assign lshr_ln42_2_fu_200_p4 = {{sub_ln73_8_fu_194_p2[10:1]}};

assign lshr_ln42_3_fu_328_p4 = {{add_ln73_fu_322_p2[10:1]}};

assign lshr_ln42_5_fu_420_p4 = {{sub_ln73_14_fu_414_p2[10:1]}};

assign lshr_ln_fu_144_p4 = {{sub_ln73_6_fu_138_p2[10:1]}};

assign p_shl1_fu_130_p3 = {{data_0_val}, {3'd0}};

assign p_shl2_fu_186_p3 = {{data_1_val}, {3'd0}};

assign p_shl3_fu_342_p3 = {{data_2_val}, {3'd0}};

assign p_shl4_fu_406_p3 = {{data_3_val}, {3'd0}};

assign part_sel_fu_530_p4 = {{sub_ln73_16_fu_470_p2[9:1]}};

assign sext_ln58_1_fu_570_p1 = $signed(add_ln58_4_reg_681);

assign sext_ln58_2_fu_612_p1 = $signed(add_ln58_5_reg_706);

assign sext_ln58_3_fu_579_p1 = $signed(add_ln58_6_reg_686);

assign sext_ln58_4_fu_615_p1 = $signed(add_ln58_7_reg_711);

assign sext_ln58_5_fu_618_p1 = $signed(add_ln58_8_reg_691_pp0_iter1_reg);

assign sext_ln58_6_fu_621_p1 = $signed(add_ln58_10_reg_716);

assign sext_ln58_7_fu_630_p1 = $signed(add_ln58_11_fu_624_p2);

assign sext_ln58_8_fu_600_p1 = $signed(add_ln58_12_reg_696);

assign sext_ln58_9_fu_603_p1 = $signed(add_ln58_13_reg_701);

assign sext_ln58_fu_564_p1 = $signed(trunc_ln42_6_reg_671);

assign sext_ln68_fu_634_p1 = $signed(add_ln58_14_reg_721);

assign sext_ln70_1_fu_298_p1 = $signed(trunc_ln42_1_fu_288_p4);

assign sext_ln70_2_fu_398_p1 = $signed(trunc_ln42_5_fu_388_p4);

assign sext_ln70_fu_178_p1 = $signed(trunc_ln42_2_fu_168_p4);

assign sext_ln73_1_fu_242_p1 = $signed(trunc_ln42_s_fu_232_p4);

assign sext_ln73_2_fu_266_p1 = $signed(trunc_ln42_4_fu_256_p4);

assign sext_ln73_3_fu_561_p1 = $signed(trunc_ln42_3_reg_666);

assign sext_ln73_4_fu_454_p1 = $signed(trunc_ln42_8_fu_444_p4);

assign sext_ln73_fu_126_p1 = $signed(trunc_ln_fu_116_p4);

assign sub_ln73_10_fu_250_p2 = (12'd0 - zext_ln73_7_fu_246_p1);

assign sub_ln73_11_fu_282_p2 = (zext_ln73_5_fu_182_p1 - zext_ln73_13_fu_278_p1);

assign sub_ln73_12_fu_350_p2 = (p_shl3_fu_342_p3 - zext_ln73_9_fu_306_p1);

assign sub_ln73_13_fu_382_p2 = (zext_ln73_9_fu_306_p1 - zext_ln73_14_fu_318_p1);

assign sub_ln73_14_fu_414_p2 = (p_shl4_fu_406_p3 - zext_ln73_11_fu_402_p1);

assign sub_ln73_15_fu_438_p2 = (12'd0 - zext_ln73_15_fu_434_p1);

assign sub_ln73_16_fu_470_p2 = (zext_ln73_11_fu_402_p1 - zext_ln73_16_fu_466_p1);

assign sub_ln73_5_fu_110_p2 = (10'd0 - zext_ln73_2_fu_106_p1);

assign sub_ln73_6_fu_138_p2 = (p_shl1_fu_130_p3 - zext_ln73_fu_94_p1);

assign sub_ln73_7_fu_162_p2 = (12'd0 - zext_ln73_4_fu_158_p1);

assign sub_ln73_8_fu_194_p2 = (p_shl2_fu_186_p3 - zext_ln73_5_fu_182_p1);

assign sub_ln73_9_fu_226_p2 = (10'd0 - zext_ln73_6_fu_222_p1);

assign sub_ln73_fu_366_p2 = (9'd0 - zext_ln73_8_fu_302_p1);

assign tmp_100_fu_310_p3 = {{data_2_val}, {2'd0}};

assign tmp_101_fu_458_p3 = {{data_3_val}, {2'd0}};

assign tmp_98_fu_214_p3 = {{data_1_val}, {1'd0}};

assign tmp_99_fu_270_p3 = {{data_1_val}, {2'd0}};

assign tmp_fu_98_p3 = {{data_0_val}, {1'd0}};

assign trunc_ln42_1_fu_288_p4 = {{sub_ln73_11_fu_282_p2[10:1]}};

assign trunc_ln42_2_fu_168_p4 = {{sub_ln73_7_fu_162_p2[11:1]}};

assign trunc_ln42_4_fu_256_p4 = {{sub_ln73_10_fu_250_p2[11:1]}};

assign trunc_ln42_5_fu_388_p4 = {{sub_ln73_13_fu_382_p2[10:1]}};

assign trunc_ln42_8_fu_444_p4 = {{sub_ln73_15_fu_438_p2[11:1]}};

assign trunc_ln42_s_fu_232_p4 = {{sub_ln73_9_fu_226_p2[9:1]}};

assign trunc_ln_fu_116_p4 = {{sub_ln73_5_fu_110_p2[9:1]}};

assign xor_ln58_fu_524_p2 = (bit_sel_fu_516_p3 ^ 1'd1);

assign zext_ln42_2_fu_338_p1 = lshr_ln42_3_fu_328_p4;

assign zext_ln42_fu_210_p1 = lshr_ln42_2_fu_200_p4;

assign zext_ln58_1_fu_548_p1 = add_ln58_s_fu_540_p3;

assign zext_ln58_fu_567_p1 = add_ln58_reg_676;

assign zext_ln73_10_fu_558_p1 = lshr_ln42_4_reg_661;

assign zext_ln73_11_fu_402_p1 = data_3_val;

assign zext_ln73_12_fu_430_p1 = lshr_ln42_5_fu_420_p4;

assign zext_ln73_13_fu_278_p1 = tmp_99_fu_270_p3;

assign zext_ln73_14_fu_318_p1 = tmp_100_fu_310_p3;

assign zext_ln73_15_fu_434_p1 = p_shl4_fu_406_p3;

assign zext_ln73_16_fu_466_p1 = tmp_101_fu_458_p3;

assign zext_ln73_2_fu_106_p1 = tmp_fu_98_p3;

assign zext_ln73_3_fu_154_p1 = lshr_ln_fu_144_p4;

assign zext_ln73_4_fu_158_p1 = p_shl1_fu_130_p3;

assign zext_ln73_5_fu_182_p1 = data_1_val;

assign zext_ln73_6_fu_222_p1 = tmp_98_fu_214_p3;

assign zext_ln73_7_fu_246_p1 = p_shl2_fu_186_p3;

assign zext_ln73_8_fu_302_p1 = data_2_val;

assign zext_ln73_9_fu_306_p1 = data_2_val;

assign zext_ln73_fu_94_p1 = data_0_val;

endmodule //myproject_dense_latency_ap_ufixed_8_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s
