-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config11_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv21_1A : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000011010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv16_60 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100000";
    constant ap_const_lv16_2A0 : STD_LOGIC_VECTOR (15 downto 0) := "0000001010100000";
    constant ap_const_lv16_300 : STD_LOGIC_VECTOR (15 downto 0) := "0000001100000000";
    constant ap_const_lv16_FFE0 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111100000";
    constant ap_const_lv16_A0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010100000";
    constant ap_const_lv16_20 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal data_1_val_read_reg_443 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data_0_val_read_reg_452 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_181_fu_143_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln42_181_reg_460 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln_reg_466 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_54_reg_471 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_55_reg_478 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_56_reg_483 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_57_reg_489 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_reg_494 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_58_reg_499 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_59_reg_504 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_90_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln42_181_fu_143_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_151_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln73_285_fu_158_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln42_fu_148_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln73_fu_162_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_shl_fu_178_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln42_fu_185_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_292_fu_201_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln73_286_fu_208_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln73_162_fu_212_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_90_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_293_fu_241_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_294_fu_252_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln73_287_fu_248_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln73_288_fu_259_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln73_163_fu_263_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_295_fu_279_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln73_289_fu_286_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln73_fu_228_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sub_ln73_164_fu_290_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sub_ln73_165_fu_306_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_296_fu_321_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln73_290_fu_328_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln73_166_fu_332_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln58_fu_351_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_349_fu_361_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_182_fu_348_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_351_fu_371_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_354_fu_387_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_356_fu_397_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_348_fu_356_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_350_fu_366_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_352_fu_377_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_353_fu_382_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_355_fu_392_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_357_fu_402_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_90_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_16s_6ns_21_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;



begin
    mul_16s_6ns_21_2_1_U184 : component myproject_mul_16s_6ns_21_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 6,
        dout_WIDTH => 21)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => data_1_val,
        din1 => grp_fu_90_p1,
        ce => grp_fu_90_ce,
        dout => grp_fu_90_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_0_val_read_reg_452 <= data_0_val;
                data_1_val_read_reg_443 <= data_1_val;
                sext_ln42_181_reg_460 <= sext_ln42_181_fu_143_p1;
                trunc_ln42_54_reg_471 <= sub_ln42_fu_185_p2(20 downto 5);
                trunc_ln42_55_reg_478 <= sub_ln73_162_fu_212_p2(20 downto 5);
                trunc_ln42_56_reg_483 <= grp_fu_90_p2(20 downto 5);
                trunc_ln42_57_reg_489 <= sub_ln73_163_fu_263_p2(20 downto 5);
                trunc_ln42_58_reg_499 <= sub_ln73_165_fu_306_p2(20 downto 5);
                trunc_ln42_59_reg_504 <= sub_ln73_166_fu_332_p2(20 downto 5);
                trunc_ln42_s_reg_494 <= sub_ln73_164_fu_290_p2(19 downto 5);
                trunc_ln_reg_466 <= sub_ln73_fu_162_p2(20 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_348_fu_356_p2 <= std_logic_vector(unsigned(add_ln58_fu_351_p2) + unsigned(trunc_ln_reg_466));
    add_ln58_349_fu_361_p2 <= std_logic_vector(unsigned(trunc_ln42_57_reg_489) + unsigned(ap_const_lv16_2A0));
    add_ln58_350_fu_366_p2 <= std_logic_vector(unsigned(add_ln58_349_fu_361_p2) + unsigned(trunc_ln42_54_reg_471));
    add_ln58_351_fu_371_p2 <= std_logic_vector(signed(sext_ln42_182_fu_348_p1) + signed(ap_const_lv16_300));
    add_ln58_352_fu_377_p2 <= std_logic_vector(unsigned(add_ln58_351_fu_371_p2) + unsigned(trunc_ln42_54_reg_471));
    add_ln58_353_fu_382_p2 <= std_logic_vector(unsigned(trunc_ln42_58_reg_499) + unsigned(ap_const_lv16_FFE0));
    add_ln58_354_fu_387_p2 <= std_logic_vector(unsigned(trunc_ln42_59_reg_504) + unsigned(ap_const_lv16_A0));
    add_ln58_355_fu_392_p2 <= std_logic_vector(unsigned(add_ln58_354_fu_387_p2) + unsigned(trunc_ln42_54_reg_471));
    add_ln58_356_fu_397_p2 <= std_logic_vector(unsigned(trunc_ln42_56_reg_483) + unsigned(ap_const_lv16_20));
    add_ln58_357_fu_402_p2 <= std_logic_vector(unsigned(add_ln58_356_fu_397_p2) + unsigned(trunc_ln42_55_reg_478));
    add_ln58_fu_351_p2 <= std_logic_vector(unsigned(trunc_ln42_56_reg_483) + unsigned(ap_const_lv16_60));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln58_348_fu_356_p2;
    ap_return_1 <= add_ln58_350_fu_366_p2;
    ap_return_2 <= add_ln58_352_fu_377_p2;
    ap_return_3 <= add_ln58_353_fu_382_p2;
    ap_return_4 <= add_ln58_355_fu_392_p2;
    ap_return_5 <= add_ln58_357_fu_402_p2;

    grp_fu_90_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_90_ce <= ap_const_logic_1;
        else 
            grp_fu_90_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_90_p1 <= ap_const_lv21_1A(6 - 1 downto 0);
    p_shl_fu_178_p3 <= (data_0_val_read_reg_452 & ap_const_lv5_0);
    sext_ln42_181_fu_143_p0 <= data_1_val;
        sext_ln42_181_fu_143_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln42_181_fu_143_p0),21));

        sext_ln42_182_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_s_reg_494),16));

        sext_ln42_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_0_val_read_reg_452),21));

        sext_ln73_285_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_151_p3),21));

        sext_ln73_286_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_292_fu_201_p3),21));

        sext_ln73_287_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_293_fu_241_p3),21));

        sext_ln73_288_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_294_fu_252_p3),21));

        sext_ln73_289_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_295_fu_279_p3),20));

        sext_ln73_290_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_296_fu_321_p3),21));

        sext_ln73_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val_read_reg_443),20));

    sub_ln42_fu_185_p2 <= std_logic_vector(unsigned(ap_const_lv21_0) - unsigned(p_shl_fu_178_p3));
    sub_ln73_162_fu_212_p2 <= std_logic_vector(signed(sext_ln73_285_fu_158_p1) - signed(sext_ln73_286_fu_208_p1));
    sub_ln73_163_fu_263_p2 <= std_logic_vector(signed(sext_ln73_287_fu_248_p1) - signed(sext_ln73_288_fu_259_p1));
    sub_ln73_164_fu_290_p2 <= std_logic_vector(signed(sext_ln73_289_fu_286_p1) - signed(sext_ln73_fu_228_p1));
    sub_ln73_165_fu_306_p2 <= std_logic_vector(signed(sext_ln42_181_reg_460) - signed(sext_ln73_287_fu_248_p1));
    sub_ln73_166_fu_332_p2 <= std_logic_vector(signed(sext_ln73_290_fu_328_p1) - signed(sext_ln73_287_fu_248_p1));
    sub_ln73_fu_162_p2 <= std_logic_vector(signed(sext_ln73_285_fu_158_p1) - signed(sext_ln42_fu_148_p1));
    tmp_292_fu_201_p3 <= (data_0_val_read_reg_452 & ap_const_lv1_0);
    tmp_293_fu_241_p3 <= (data_1_val_read_reg_443 & ap_const_lv4_0);
    tmp_294_fu_252_p3 <= (data_1_val_read_reg_443 & ap_const_lv2_0);
    tmp_295_fu_279_p3 <= (data_1_val_read_reg_443 & ap_const_lv3_0);
    tmp_296_fu_321_p3 <= (data_1_val_read_reg_443 & ap_const_lv1_0);
    tmp_fu_151_p3 <= (data_0_val_read_reg_452 & ap_const_lv4_0);
end behav;
