// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[7:0] ap_return_3;
reg[7:0] ap_return_4;
reg[7:0] ap_return_5;
reg[7:0] ap_return_6;
reg[7:0] ap_return_7;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg   [15:0] p_read724_reg_1410;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] p_read623_reg_1416;
reg   [15:0] p_read522_reg_1422;
reg   [15:0] p_read421_reg_1428;
reg   [15:0] p_read320_reg_1434;
reg   [15:0] p_read219_reg_1440;
reg   [15:0] p_read118_reg_1446;
reg   [15:0] p_read17_reg_1452;
reg   [0:0] tmp_reg_1458;
wire   [7:0] add_ln46_fu_160_p2;
reg   [7:0] add_ln46_reg_1465;
wire   [0:0] icmp_ln46_fu_176_p2;
reg   [0:0] icmp_ln46_reg_1472;
reg   [0:0] tmp_3644_reg_1477;
wire   [7:0] add_ln46_766_fu_236_p2;
reg   [7:0] add_ln46_766_reg_1484;
wire   [0:0] icmp_ln46_286_fu_252_p2;
reg   [0:0] icmp_ln46_286_reg_1491;
reg   [0:0] tmp_3649_reg_1496;
wire   [7:0] add_ln46_767_fu_312_p2;
reg   [7:0] add_ln46_767_reg_1503;
wire   [0:0] icmp_ln46_287_fu_328_p2;
reg   [0:0] icmp_ln46_287_reg_1510;
reg   [0:0] tmp_3655_reg_1515;
wire   [7:0] add_ln46_768_fu_388_p2;
reg   [7:0] add_ln46_768_reg_1522;
wire   [0:0] icmp_ln46_288_fu_404_p2;
reg   [0:0] icmp_ln46_288_reg_1529;
reg   [0:0] tmp_3661_reg_1534;
wire   [7:0] add_ln46_769_fu_464_p2;
reg   [7:0] add_ln46_769_reg_1541;
wire   [0:0] icmp_ln46_289_fu_480_p2;
reg   [0:0] icmp_ln46_289_reg_1548;
reg   [0:0] tmp_3667_reg_1553;
wire   [7:0] add_ln46_770_fu_540_p2;
reg   [7:0] add_ln46_770_reg_1560;
wire   [0:0] icmp_ln46_290_fu_556_p2;
reg   [0:0] icmp_ln46_290_reg_1567;
reg   [0:0] tmp_3673_reg_1572;
wire   [7:0] add_ln46_771_fu_616_p2;
reg   [7:0] add_ln46_771_reg_1579;
wire   [0:0] icmp_ln46_291_fu_632_p2;
reg   [0:0] icmp_ln46_291_reg_1586;
reg   [0:0] tmp_3679_reg_1591;
wire   [7:0] add_ln46_772_fu_692_p2;
reg   [7:0] add_ln46_772_reg_1598;
wire   [0:0] icmp_ln46_292_fu_708_p2;
reg   [0:0] icmp_ln46_292_reg_1605;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_3642_fu_136_p3;
wire   [0:0] trunc_ln46_fu_132_p1;
wire   [0:0] or_ln46_fu_144_p2;
wire   [0:0] tmp_3640_fu_124_p3;
wire   [0:0] and_ln46_fu_150_p2;
wire   [7:0] trunc_ln_fu_114_p4;
wire   [7:0] zext_ln46_fu_156_p1;
wire   [5:0] tmp_s_fu_166_p4;
wire   [0:0] tmp_3647_fu_212_p3;
wire   [0:0] trunc_ln46_1004_fu_208_p1;
wire   [0:0] or_ln46_1344_fu_220_p2;
wire   [0:0] tmp_3645_fu_200_p3;
wire   [0:0] and_ln46_865_fu_226_p2;
wire   [7:0] trunc_ln46_s_fu_190_p4;
wire   [7:0] zext_ln46_1138_fu_232_p1;
wire   [5:0] tmp_3639_fu_242_p4;
wire   [0:0] tmp_3652_fu_288_p3;
wire   [0:0] trunc_ln46_1005_fu_284_p1;
wire   [0:0] or_ln46_1347_fu_296_p2;
wire   [0:0] tmp_3650_fu_276_p3;
wire   [0:0] and_ln46_866_fu_302_p2;
wire   [7:0] trunc_ln46_283_fu_266_p4;
wire   [7:0] zext_ln46_1139_fu_308_p1;
wire   [5:0] tmp_3653_fu_318_p4;
wire   [0:0] tmp_3658_fu_364_p3;
wire   [0:0] trunc_ln46_1006_fu_360_p1;
wire   [0:0] or_ln46_1350_fu_372_p2;
wire   [0:0] tmp_3656_fu_352_p3;
wire   [0:0] and_ln46_867_fu_378_p2;
wire   [7:0] trunc_ln46_284_fu_342_p4;
wire   [7:0] zext_ln46_1140_fu_384_p1;
wire   [5:0] tmp_3659_fu_394_p4;
wire   [0:0] tmp_3664_fu_440_p3;
wire   [0:0] trunc_ln46_1007_fu_436_p1;
wire   [0:0] or_ln46_1353_fu_448_p2;
wire   [0:0] tmp_3662_fu_428_p3;
wire   [0:0] and_ln46_868_fu_454_p2;
wire   [7:0] trunc_ln46_285_fu_418_p4;
wire   [7:0] zext_ln46_1141_fu_460_p1;
wire   [5:0] tmp_3665_fu_470_p4;
wire   [0:0] tmp_3670_fu_516_p3;
wire   [0:0] trunc_ln46_1008_fu_512_p1;
wire   [0:0] or_ln46_1356_fu_524_p2;
wire   [0:0] tmp_3668_fu_504_p3;
wire   [0:0] and_ln46_869_fu_530_p2;
wire   [7:0] trunc_ln46_286_fu_494_p4;
wire   [7:0] zext_ln46_1142_fu_536_p1;
wire   [5:0] tmp_3671_fu_546_p4;
wire   [0:0] tmp_3676_fu_592_p3;
wire   [0:0] trunc_ln46_1009_fu_588_p1;
wire   [0:0] or_ln46_1359_fu_600_p2;
wire   [0:0] tmp_3674_fu_580_p3;
wire   [0:0] and_ln46_870_fu_606_p2;
wire   [7:0] trunc_ln46_287_fu_570_p4;
wire   [7:0] zext_ln46_1143_fu_612_p1;
wire   [5:0] tmp_3677_fu_622_p4;
wire   [0:0] tmp_3682_fu_668_p3;
wire   [0:0] trunc_ln46_1010_fu_664_p1;
wire   [0:0] or_ln46_1362_fu_676_p2;
wire   [0:0] tmp_3680_fu_656_p3;
wire   [0:0] and_ln46_871_fu_682_p2;
wire   [7:0] trunc_ln46_288_fu_646_p4;
wire   [7:0] zext_ln46_1144_fu_688_p1;
wire   [5:0] tmp_3683_fu_698_p4;
wire   [0:0] tmp_3641_fu_719_p3;
wire   [0:0] tmp_3643_fu_726_p3;
wire   [0:0] not_tmp_7052_fu_733_p2;
wire   [0:0] and_ln46_2254_fu_739_p2;
wire   [0:0] empty_fu_745_p2;
wire   [0:0] xor_ln46_fu_755_p2;
wire   [0:0] or_ln46_1342_fu_750_p2;
wire   [7:0] select_ln46_fu_766_p3;
wire   [0:0] or_ln46_1343_fu_761_p2;
wire   [7:0] select_ln46_1342_fu_772_p3;
wire   [0:0] icmp_ln45_fu_714_p2;
wire   [7:0] select_ln46_1343_fu_780_p3;
wire   [0:0] tmp_3646_fu_800_p3;
wire   [0:0] tmp_3648_fu_807_p3;
wire   [0:0] not_tmp_7059_fu_814_p2;
wire   [0:0] and_ln46_2256_fu_820_p2;
wire   [0:0] empty_304_fu_826_p2;
wire   [0:0] xor_ln46_286_fu_836_p2;
wire   [0:0] or_ln46_1345_fu_831_p2;
wire   [7:0] select_ln46_1344_fu_847_p3;
wire   [0:0] or_ln46_1346_fu_842_p2;
wire   [7:0] select_ln46_1345_fu_853_p3;
wire   [0:0] icmp_ln45_766_fu_795_p2;
wire   [7:0] select_ln46_1346_fu_861_p3;
wire   [0:0] tmp_3651_fu_881_p3;
wire   [0:0] tmp_3654_fu_888_p3;
wire   [0:0] not_tmp_7066_fu_895_p2;
wire   [0:0] and_ln46_2258_fu_901_p2;
wire   [0:0] empty_305_fu_907_p2;
wire   [0:0] xor_ln46_287_fu_917_p2;
wire   [0:0] or_ln46_1348_fu_912_p2;
wire   [7:0] select_ln46_1347_fu_928_p3;
wire   [0:0] or_ln46_1349_fu_923_p2;
wire   [7:0] select_ln46_1348_fu_934_p3;
wire   [0:0] icmp_ln45_767_fu_876_p2;
wire   [7:0] select_ln46_1349_fu_942_p3;
wire   [0:0] tmp_3657_fu_962_p3;
wire   [0:0] tmp_3660_fu_969_p3;
wire   [0:0] not_tmp_7073_fu_976_p2;
wire   [0:0] and_ln46_2260_fu_982_p2;
wire   [0:0] empty_306_fu_988_p2;
wire   [0:0] xor_ln46_288_fu_998_p2;
wire   [0:0] or_ln46_1351_fu_993_p2;
wire   [7:0] select_ln46_1350_fu_1009_p3;
wire   [0:0] or_ln46_1352_fu_1004_p2;
wire   [7:0] select_ln46_1351_fu_1015_p3;
wire   [0:0] icmp_ln45_768_fu_957_p2;
wire   [7:0] select_ln46_1352_fu_1023_p3;
wire   [0:0] tmp_3663_fu_1043_p3;
wire   [0:0] tmp_3666_fu_1050_p3;
wire   [0:0] not_tmp_7080_fu_1057_p2;
wire   [0:0] and_ln46_2262_fu_1063_p2;
wire   [0:0] empty_307_fu_1069_p2;
wire   [0:0] xor_ln46_289_fu_1079_p2;
wire   [0:0] or_ln46_1354_fu_1074_p2;
wire   [7:0] select_ln46_1353_fu_1090_p3;
wire   [0:0] or_ln46_1355_fu_1085_p2;
wire   [7:0] select_ln46_1354_fu_1096_p3;
wire   [0:0] icmp_ln45_769_fu_1038_p2;
wire   [7:0] select_ln46_1355_fu_1104_p3;
wire   [0:0] tmp_3669_fu_1124_p3;
wire   [0:0] tmp_3672_fu_1131_p3;
wire   [0:0] not_tmp_7087_fu_1138_p2;
wire   [0:0] and_ln46_2264_fu_1144_p2;
wire   [0:0] empty_308_fu_1150_p2;
wire   [0:0] xor_ln46_290_fu_1160_p2;
wire   [0:0] or_ln46_1357_fu_1155_p2;
wire   [7:0] select_ln46_1356_fu_1171_p3;
wire   [0:0] or_ln46_1358_fu_1166_p2;
wire   [7:0] select_ln46_1357_fu_1177_p3;
wire   [0:0] icmp_ln45_770_fu_1119_p2;
wire   [7:0] select_ln46_1358_fu_1185_p3;
wire   [0:0] tmp_3675_fu_1205_p3;
wire   [0:0] tmp_3678_fu_1212_p3;
wire   [0:0] not_tmp_7094_fu_1219_p2;
wire   [0:0] and_ln46_2266_fu_1225_p2;
wire   [0:0] empty_309_fu_1231_p2;
wire   [0:0] xor_ln46_291_fu_1241_p2;
wire   [0:0] or_ln46_1360_fu_1236_p2;
wire   [7:0] select_ln46_1359_fu_1252_p3;
wire   [0:0] or_ln46_1361_fu_1247_p2;
wire   [7:0] select_ln46_1360_fu_1258_p3;
wire   [0:0] icmp_ln45_771_fu_1200_p2;
wire   [7:0] select_ln46_1361_fu_1266_p3;
wire   [0:0] tmp_3681_fu_1286_p3;
wire   [0:0] tmp_3684_fu_1293_p3;
wire   [0:0] not_tmp_7101_fu_1300_p2;
wire   [0:0] and_ln46_2268_fu_1306_p2;
wire   [0:0] empty_310_fu_1312_p2;
wire   [0:0] xor_ln46_292_fu_1322_p2;
wire   [0:0] or_ln46_1363_fu_1317_p2;
wire   [7:0] select_ln46_1362_fu_1333_p3;
wire   [0:0] or_ln46_1364_fu_1328_p2;
wire   [7:0] select_ln46_1363_fu_1339_p3;
wire   [0:0] icmp_ln45_772_fu_1281_p2;
wire   [7:0] select_ln46_1364_fu_1347_p3;
wire   [7:0] res_0_0_fu_787_p3;
wire   [7:0] res_1_0_fu_868_p3;
wire   [7:0] res_2_0_fu_949_p3;
wire   [7:0] res_3_0_fu_1030_p3;
wire   [7:0] res_4_0_fu_1111_p3;
wire   [7:0] res_5_0_fu_1192_p3;
wire   [7:0] res_6_0_fu_1273_p3;
wire   [7:0] res_7_0_fu_1354_p3;
reg   [7:0] ap_return_0_preg;
reg   [7:0] ap_return_1_preg;
reg   [7:0] ap_return_2_preg;
reg   [7:0] ap_return_3_preg;
reg   [7:0] ap_return_4_preg;
reg   [7:0] ap_return_5_preg;
reg   [7:0] ap_return_6_preg;
reg   [7:0] ap_return_7_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_return_0_preg = 8'd0;
#0 ap_return_1_preg = 8'd0;
#0 ap_return_2_preg = 8'd0;
#0 ap_return_3_preg = 8'd0;
#0 ap_return_4_preg = 8'd0;
#0 ap_return_5_preg = 8'd0;
#0 ap_return_6_preg = 8'd0;
#0 ap_return_7_preg = 8'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_0_preg <= res_0_0_fu_787_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_1_preg <= res_1_0_fu_868_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_2_preg <= res_2_0_fu_949_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_3_preg <= res_3_0_fu_1030_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_4_preg <= res_4_0_fu_1111_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_5_preg <= res_5_0_fu_1192_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_6_preg <= res_6_0_fu_1273_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_7_preg <= res_7_0_fu_1354_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln46_766_reg_1484 <= add_ln46_766_fu_236_p2;
        add_ln46_767_reg_1503 <= add_ln46_767_fu_312_p2;
        add_ln46_768_reg_1522 <= add_ln46_768_fu_388_p2;
        add_ln46_769_reg_1541 <= add_ln46_769_fu_464_p2;
        add_ln46_770_reg_1560 <= add_ln46_770_fu_540_p2;
        add_ln46_771_reg_1579 <= add_ln46_771_fu_616_p2;
        add_ln46_772_reg_1598 <= add_ln46_772_fu_692_p2;
        add_ln46_reg_1465 <= add_ln46_fu_160_p2;
        icmp_ln46_286_reg_1491 <= icmp_ln46_286_fu_252_p2;
        icmp_ln46_287_reg_1510 <= icmp_ln46_287_fu_328_p2;
        icmp_ln46_288_reg_1529 <= icmp_ln46_288_fu_404_p2;
        icmp_ln46_289_reg_1548 <= icmp_ln46_289_fu_480_p2;
        icmp_ln46_290_reg_1567 <= icmp_ln46_290_fu_556_p2;
        icmp_ln46_291_reg_1586 <= icmp_ln46_291_fu_632_p2;
        icmp_ln46_292_reg_1605 <= icmp_ln46_292_fu_708_p2;
        icmp_ln46_reg_1472 <= icmp_ln46_fu_176_p2;
        p_read118_reg_1446 <= p_read1;
        p_read17_reg_1452 <= p_read;
        p_read219_reg_1440 <= p_read2;
        p_read320_reg_1434 <= p_read3;
        p_read421_reg_1428 <= p_read4;
        p_read522_reg_1422 <= p_read5;
        p_read623_reg_1416 <= p_read6;
        p_read724_reg_1410 <= p_read7;
        tmp_3644_reg_1477 <= p_read1[32'd15];
        tmp_3649_reg_1496 <= p_read2[32'd15];
        tmp_3655_reg_1515 <= p_read3[32'd15];
        tmp_3661_reg_1534 <= p_read4[32'd15];
        tmp_3667_reg_1553 <= p_read5[32'd15];
        tmp_3673_reg_1572 <= p_read6[32'd15];
        tmp_3679_reg_1591 <= p_read7[32'd15];
        tmp_reg_1458 <= p_read[32'd15];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_0 = res_0_0_fu_787_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_1 = res_1_0_fu_868_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_2 = res_2_0_fu_949_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_3 = res_3_0_fu_1030_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_4 = res_4_0_fu_1111_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_5 = res_5_0_fu_1192_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_6 = res_6_0_fu_1273_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_7 = res_7_0_fu_1354_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_766_fu_236_p2 = (trunc_ln46_s_fu_190_p4 + zext_ln46_1138_fu_232_p1);

assign add_ln46_767_fu_312_p2 = (trunc_ln46_283_fu_266_p4 + zext_ln46_1139_fu_308_p1);

assign add_ln46_768_fu_388_p2 = (trunc_ln46_284_fu_342_p4 + zext_ln46_1140_fu_384_p1);

assign add_ln46_769_fu_464_p2 = (trunc_ln46_285_fu_418_p4 + zext_ln46_1141_fu_460_p1);

assign add_ln46_770_fu_540_p2 = (trunc_ln46_286_fu_494_p4 + zext_ln46_1142_fu_536_p1);

assign add_ln46_771_fu_616_p2 = (trunc_ln46_287_fu_570_p4 + zext_ln46_1143_fu_612_p1);

assign add_ln46_772_fu_692_p2 = (trunc_ln46_288_fu_646_p4 + zext_ln46_1144_fu_688_p1);

assign add_ln46_fu_160_p2 = (trunc_ln_fu_114_p4 + zext_ln46_fu_156_p1);

assign and_ln46_2254_fu_739_p2 = (tmp_3643_fu_726_p3 | not_tmp_7052_fu_733_p2);

assign and_ln46_2256_fu_820_p2 = (tmp_3648_fu_807_p3 | not_tmp_7059_fu_814_p2);

assign and_ln46_2258_fu_901_p2 = (tmp_3654_fu_888_p3 | not_tmp_7066_fu_895_p2);

assign and_ln46_2260_fu_982_p2 = (tmp_3660_fu_969_p3 | not_tmp_7073_fu_976_p2);

assign and_ln46_2262_fu_1063_p2 = (tmp_3666_fu_1050_p3 | not_tmp_7080_fu_1057_p2);

assign and_ln46_2264_fu_1144_p2 = (tmp_3672_fu_1131_p3 | not_tmp_7087_fu_1138_p2);

assign and_ln46_2266_fu_1225_p2 = (tmp_3678_fu_1212_p3 | not_tmp_7094_fu_1219_p2);

assign and_ln46_2268_fu_1306_p2 = (tmp_3684_fu_1293_p3 | not_tmp_7101_fu_1300_p2);

assign and_ln46_865_fu_226_p2 = (tmp_3645_fu_200_p3 & or_ln46_1344_fu_220_p2);

assign and_ln46_866_fu_302_p2 = (tmp_3650_fu_276_p3 & or_ln46_1347_fu_296_p2);

assign and_ln46_867_fu_378_p2 = (tmp_3656_fu_352_p3 & or_ln46_1350_fu_372_p2);

assign and_ln46_868_fu_454_p2 = (tmp_3662_fu_428_p3 & or_ln46_1353_fu_448_p2);

assign and_ln46_869_fu_530_p2 = (tmp_3668_fu_504_p3 & or_ln46_1356_fu_524_p2);

assign and_ln46_870_fu_606_p2 = (tmp_3674_fu_580_p3 & or_ln46_1359_fu_600_p2);

assign and_ln46_871_fu_682_p2 = (tmp_3680_fu_656_p3 & or_ln46_1362_fu_676_p2);

assign and_ln46_fu_150_p2 = (tmp_3640_fu_124_p3 & or_ln46_fu_144_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign empty_304_fu_826_p2 = (icmp_ln46_286_reg_1491 & and_ln46_2256_fu_820_p2);

assign empty_305_fu_907_p2 = (icmp_ln46_287_reg_1510 & and_ln46_2258_fu_901_p2);

assign empty_306_fu_988_p2 = (icmp_ln46_288_reg_1529 & and_ln46_2260_fu_982_p2);

assign empty_307_fu_1069_p2 = (icmp_ln46_289_reg_1548 & and_ln46_2262_fu_1063_p2);

assign empty_308_fu_1150_p2 = (icmp_ln46_290_reg_1567 & and_ln46_2264_fu_1144_p2);

assign empty_309_fu_1231_p2 = (icmp_ln46_291_reg_1586 & and_ln46_2266_fu_1225_p2);

assign empty_310_fu_1312_p2 = (icmp_ln46_292_reg_1605 & and_ln46_2268_fu_1306_p2);

assign empty_fu_745_p2 = (icmp_ln46_reg_1472 & and_ln46_2254_fu_739_p2);

assign icmp_ln45_766_fu_795_p2 = (($signed(p_read118_reg_1446) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_767_fu_876_p2 = (($signed(p_read219_reg_1440) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_768_fu_957_p2 = (($signed(p_read320_reg_1434) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_769_fu_1038_p2 = (($signed(p_read421_reg_1428) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_770_fu_1119_p2 = (($signed(p_read522_reg_1422) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_771_fu_1200_p2 = (($signed(p_read623_reg_1416) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_772_fu_1281_p2 = (($signed(p_read724_reg_1410) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_714_p2 = (($signed(p_read17_reg_1452) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_286_fu_252_p2 = ((tmp_3639_fu_242_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_287_fu_328_p2 = ((tmp_3653_fu_318_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_288_fu_404_p2 = ((tmp_3659_fu_394_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_289_fu_480_p2 = ((tmp_3665_fu_470_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_290_fu_556_p2 = ((tmp_3671_fu_546_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_291_fu_632_p2 = ((tmp_3677_fu_622_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_292_fu_708_p2 = ((tmp_3683_fu_698_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_176_p2 = ((tmp_s_fu_166_p4 == 6'd0) ? 1'b1 : 1'b0);

assign not_tmp_7052_fu_733_p2 = (tmp_3641_fu_719_p3 ^ 1'd1);

assign not_tmp_7059_fu_814_p2 = (tmp_3646_fu_800_p3 ^ 1'd1);

assign not_tmp_7066_fu_895_p2 = (tmp_3651_fu_881_p3 ^ 1'd1);

assign not_tmp_7073_fu_976_p2 = (tmp_3657_fu_962_p3 ^ 1'd1);

assign not_tmp_7080_fu_1057_p2 = (tmp_3663_fu_1043_p3 ^ 1'd1);

assign not_tmp_7087_fu_1138_p2 = (tmp_3669_fu_1124_p3 ^ 1'd1);

assign not_tmp_7094_fu_1219_p2 = (tmp_3675_fu_1205_p3 ^ 1'd1);

assign not_tmp_7101_fu_1300_p2 = (tmp_3681_fu_1286_p3 ^ 1'd1);

assign or_ln46_1342_fu_750_p2 = (tmp_reg_1458 | empty_fu_745_p2);

assign or_ln46_1343_fu_761_p2 = (xor_ln46_fu_755_p2 | tmp_reg_1458);

assign or_ln46_1344_fu_220_p2 = (trunc_ln46_1004_fu_208_p1 | tmp_3647_fu_212_p3);

assign or_ln46_1345_fu_831_p2 = (tmp_3644_reg_1477 | empty_304_fu_826_p2);

assign or_ln46_1346_fu_842_p2 = (xor_ln46_286_fu_836_p2 | tmp_3644_reg_1477);

assign or_ln46_1347_fu_296_p2 = (trunc_ln46_1005_fu_284_p1 | tmp_3652_fu_288_p3);

assign or_ln46_1348_fu_912_p2 = (tmp_3649_reg_1496 | empty_305_fu_907_p2);

assign or_ln46_1349_fu_923_p2 = (xor_ln46_287_fu_917_p2 | tmp_3649_reg_1496);

assign or_ln46_1350_fu_372_p2 = (trunc_ln46_1006_fu_360_p1 | tmp_3658_fu_364_p3);

assign or_ln46_1351_fu_993_p2 = (tmp_3655_reg_1515 | empty_306_fu_988_p2);

assign or_ln46_1352_fu_1004_p2 = (xor_ln46_288_fu_998_p2 | tmp_3655_reg_1515);

assign or_ln46_1353_fu_448_p2 = (trunc_ln46_1007_fu_436_p1 | tmp_3664_fu_440_p3);

assign or_ln46_1354_fu_1074_p2 = (tmp_3661_reg_1534 | empty_307_fu_1069_p2);

assign or_ln46_1355_fu_1085_p2 = (xor_ln46_289_fu_1079_p2 | tmp_3661_reg_1534);

assign or_ln46_1356_fu_524_p2 = (trunc_ln46_1008_fu_512_p1 | tmp_3670_fu_516_p3);

assign or_ln46_1357_fu_1155_p2 = (tmp_3667_reg_1553 | empty_308_fu_1150_p2);

assign or_ln46_1358_fu_1166_p2 = (xor_ln46_290_fu_1160_p2 | tmp_3667_reg_1553);

assign or_ln46_1359_fu_600_p2 = (trunc_ln46_1009_fu_588_p1 | tmp_3676_fu_592_p3);

assign or_ln46_1360_fu_1236_p2 = (tmp_3673_reg_1572 | empty_309_fu_1231_p2);

assign or_ln46_1361_fu_1247_p2 = (xor_ln46_291_fu_1241_p2 | tmp_3673_reg_1572);

assign or_ln46_1362_fu_676_p2 = (trunc_ln46_1010_fu_664_p1 | tmp_3682_fu_668_p3);

assign or_ln46_1363_fu_1317_p2 = (tmp_3679_reg_1591 | empty_310_fu_1312_p2);

assign or_ln46_1364_fu_1328_p2 = (xor_ln46_292_fu_1322_p2 | tmp_3679_reg_1591);

assign or_ln46_fu_144_p2 = (trunc_ln46_fu_132_p1 | tmp_3642_fu_136_p3);

assign res_0_0_fu_787_p3 = ((icmp_ln45_fu_714_p2[0:0] == 1'b1) ? select_ln46_1343_fu_780_p3 : 8'd0);

assign res_1_0_fu_868_p3 = ((icmp_ln45_766_fu_795_p2[0:0] == 1'b1) ? select_ln46_1346_fu_861_p3 : 8'd0);

assign res_2_0_fu_949_p3 = ((icmp_ln45_767_fu_876_p2[0:0] == 1'b1) ? select_ln46_1349_fu_942_p3 : 8'd0);

assign res_3_0_fu_1030_p3 = ((icmp_ln45_768_fu_957_p2[0:0] == 1'b1) ? select_ln46_1352_fu_1023_p3 : 8'd0);

assign res_4_0_fu_1111_p3 = ((icmp_ln45_769_fu_1038_p2[0:0] == 1'b1) ? select_ln46_1355_fu_1104_p3 : 8'd0);

assign res_5_0_fu_1192_p3 = ((icmp_ln45_770_fu_1119_p2[0:0] == 1'b1) ? select_ln46_1358_fu_1185_p3 : 8'd0);

assign res_6_0_fu_1273_p3 = ((icmp_ln45_771_fu_1200_p2[0:0] == 1'b1) ? select_ln46_1361_fu_1266_p3 : 8'd0);

assign res_7_0_fu_1354_p3 = ((icmp_ln45_772_fu_1281_p2[0:0] == 1'b1) ? select_ln46_1364_fu_1347_p3 : 8'd0);

assign select_ln46_1342_fu_772_p3 = ((or_ln46_1342_fu_750_p2[0:0] == 1'b1) ? select_ln46_fu_766_p3 : 8'd255);

assign select_ln46_1343_fu_780_p3 = ((or_ln46_1343_fu_761_p2[0:0] == 1'b1) ? select_ln46_1342_fu_772_p3 : add_ln46_reg_1465);

assign select_ln46_1344_fu_847_p3 = ((tmp_3644_reg_1477[0:0] == 1'b1) ? 8'd0 : add_ln46_766_reg_1484);

assign select_ln46_1345_fu_853_p3 = ((or_ln46_1345_fu_831_p2[0:0] == 1'b1) ? select_ln46_1344_fu_847_p3 : 8'd255);

assign select_ln46_1346_fu_861_p3 = ((or_ln46_1346_fu_842_p2[0:0] == 1'b1) ? select_ln46_1345_fu_853_p3 : add_ln46_766_reg_1484);

assign select_ln46_1347_fu_928_p3 = ((tmp_3649_reg_1496[0:0] == 1'b1) ? 8'd0 : add_ln46_767_reg_1503);

assign select_ln46_1348_fu_934_p3 = ((or_ln46_1348_fu_912_p2[0:0] == 1'b1) ? select_ln46_1347_fu_928_p3 : 8'd255);

assign select_ln46_1349_fu_942_p3 = ((or_ln46_1349_fu_923_p2[0:0] == 1'b1) ? select_ln46_1348_fu_934_p3 : add_ln46_767_reg_1503);

assign select_ln46_1350_fu_1009_p3 = ((tmp_3655_reg_1515[0:0] == 1'b1) ? 8'd0 : add_ln46_768_reg_1522);

assign select_ln46_1351_fu_1015_p3 = ((or_ln46_1351_fu_993_p2[0:0] == 1'b1) ? select_ln46_1350_fu_1009_p3 : 8'd255);

assign select_ln46_1352_fu_1023_p3 = ((or_ln46_1352_fu_1004_p2[0:0] == 1'b1) ? select_ln46_1351_fu_1015_p3 : add_ln46_768_reg_1522);

assign select_ln46_1353_fu_1090_p3 = ((tmp_3661_reg_1534[0:0] == 1'b1) ? 8'd0 : add_ln46_769_reg_1541);

assign select_ln46_1354_fu_1096_p3 = ((or_ln46_1354_fu_1074_p2[0:0] == 1'b1) ? select_ln46_1353_fu_1090_p3 : 8'd255);

assign select_ln46_1355_fu_1104_p3 = ((or_ln46_1355_fu_1085_p2[0:0] == 1'b1) ? select_ln46_1354_fu_1096_p3 : add_ln46_769_reg_1541);

assign select_ln46_1356_fu_1171_p3 = ((tmp_3667_reg_1553[0:0] == 1'b1) ? 8'd0 : add_ln46_770_reg_1560);

assign select_ln46_1357_fu_1177_p3 = ((or_ln46_1357_fu_1155_p2[0:0] == 1'b1) ? select_ln46_1356_fu_1171_p3 : 8'd255);

assign select_ln46_1358_fu_1185_p3 = ((or_ln46_1358_fu_1166_p2[0:0] == 1'b1) ? select_ln46_1357_fu_1177_p3 : add_ln46_770_reg_1560);

assign select_ln46_1359_fu_1252_p3 = ((tmp_3673_reg_1572[0:0] == 1'b1) ? 8'd0 : add_ln46_771_reg_1579);

assign select_ln46_1360_fu_1258_p3 = ((or_ln46_1360_fu_1236_p2[0:0] == 1'b1) ? select_ln46_1359_fu_1252_p3 : 8'd255);

assign select_ln46_1361_fu_1266_p3 = ((or_ln46_1361_fu_1247_p2[0:0] == 1'b1) ? select_ln46_1360_fu_1258_p3 : add_ln46_771_reg_1579);

assign select_ln46_1362_fu_1333_p3 = ((tmp_3679_reg_1591[0:0] == 1'b1) ? 8'd0 : add_ln46_772_reg_1598);

assign select_ln46_1363_fu_1339_p3 = ((or_ln46_1363_fu_1317_p2[0:0] == 1'b1) ? select_ln46_1362_fu_1333_p3 : 8'd255);

assign select_ln46_1364_fu_1347_p3 = ((or_ln46_1364_fu_1328_p2[0:0] == 1'b1) ? select_ln46_1363_fu_1339_p3 : add_ln46_772_reg_1598);

assign select_ln46_fu_766_p3 = ((tmp_reg_1458[0:0] == 1'b1) ? 8'd0 : add_ln46_reg_1465);

assign tmp_3639_fu_242_p4 = {{p_read1[15:10]}};

assign tmp_3640_fu_124_p3 = p_read[32'd1];

assign tmp_3641_fu_719_p3 = p_read17_reg_1452[32'd9];

assign tmp_3642_fu_136_p3 = p_read[32'd2];

assign tmp_3643_fu_726_p3 = add_ln46_reg_1465[32'd7];

assign tmp_3645_fu_200_p3 = p_read1[32'd1];

assign tmp_3646_fu_800_p3 = p_read118_reg_1446[32'd9];

assign tmp_3647_fu_212_p3 = p_read1[32'd2];

assign tmp_3648_fu_807_p3 = add_ln46_766_reg_1484[32'd7];

assign tmp_3650_fu_276_p3 = p_read2[32'd1];

assign tmp_3651_fu_881_p3 = p_read219_reg_1440[32'd9];

assign tmp_3652_fu_288_p3 = p_read2[32'd2];

assign tmp_3653_fu_318_p4 = {{p_read2[15:10]}};

assign tmp_3654_fu_888_p3 = add_ln46_767_reg_1503[32'd7];

assign tmp_3656_fu_352_p3 = p_read3[32'd1];

assign tmp_3657_fu_962_p3 = p_read320_reg_1434[32'd9];

assign tmp_3658_fu_364_p3 = p_read3[32'd2];

assign tmp_3659_fu_394_p4 = {{p_read3[15:10]}};

assign tmp_3660_fu_969_p3 = add_ln46_768_reg_1522[32'd7];

assign tmp_3662_fu_428_p3 = p_read4[32'd1];

assign tmp_3663_fu_1043_p3 = p_read421_reg_1428[32'd9];

assign tmp_3664_fu_440_p3 = p_read4[32'd2];

assign tmp_3665_fu_470_p4 = {{p_read4[15:10]}};

assign tmp_3666_fu_1050_p3 = add_ln46_769_reg_1541[32'd7];

assign tmp_3668_fu_504_p3 = p_read5[32'd1];

assign tmp_3669_fu_1124_p3 = p_read522_reg_1422[32'd9];

assign tmp_3670_fu_516_p3 = p_read5[32'd2];

assign tmp_3671_fu_546_p4 = {{p_read5[15:10]}};

assign tmp_3672_fu_1131_p3 = add_ln46_770_reg_1560[32'd7];

assign tmp_3674_fu_580_p3 = p_read6[32'd1];

assign tmp_3675_fu_1205_p3 = p_read623_reg_1416[32'd9];

assign tmp_3676_fu_592_p3 = p_read6[32'd2];

assign tmp_3677_fu_622_p4 = {{p_read6[15:10]}};

assign tmp_3678_fu_1212_p3 = add_ln46_771_reg_1579[32'd7];

assign tmp_3680_fu_656_p3 = p_read7[32'd1];

assign tmp_3681_fu_1286_p3 = p_read724_reg_1410[32'd9];

assign tmp_3682_fu_668_p3 = p_read7[32'd2];

assign tmp_3683_fu_698_p4 = {{p_read7[15:10]}};

assign tmp_3684_fu_1293_p3 = add_ln46_772_reg_1598[32'd7];

assign tmp_s_fu_166_p4 = {{p_read[15:10]}};

assign trunc_ln46_1004_fu_208_p1 = p_read1[0:0];

assign trunc_ln46_1005_fu_284_p1 = p_read2[0:0];

assign trunc_ln46_1006_fu_360_p1 = p_read3[0:0];

assign trunc_ln46_1007_fu_436_p1 = p_read4[0:0];

assign trunc_ln46_1008_fu_512_p1 = p_read5[0:0];

assign trunc_ln46_1009_fu_588_p1 = p_read6[0:0];

assign trunc_ln46_1010_fu_664_p1 = p_read7[0:0];

assign trunc_ln46_283_fu_266_p4 = {{p_read2[9:2]}};

assign trunc_ln46_284_fu_342_p4 = {{p_read3[9:2]}};

assign trunc_ln46_285_fu_418_p4 = {{p_read4[9:2]}};

assign trunc_ln46_286_fu_494_p4 = {{p_read5[9:2]}};

assign trunc_ln46_287_fu_570_p4 = {{p_read6[9:2]}};

assign trunc_ln46_288_fu_646_p4 = {{p_read7[9:2]}};

assign trunc_ln46_fu_132_p1 = p_read[0:0];

assign trunc_ln46_s_fu_190_p4 = {{p_read1[9:2]}};

assign trunc_ln_fu_114_p4 = {{p_read[9:2]}};

assign xor_ln46_286_fu_836_p2 = (empty_304_fu_826_p2 ^ 1'd1);

assign xor_ln46_287_fu_917_p2 = (empty_305_fu_907_p2 ^ 1'd1);

assign xor_ln46_288_fu_998_p2 = (empty_306_fu_988_p2 ^ 1'd1);

assign xor_ln46_289_fu_1079_p2 = (empty_307_fu_1069_p2 ^ 1'd1);

assign xor_ln46_290_fu_1160_p2 = (empty_308_fu_1150_p2 ^ 1'd1);

assign xor_ln46_291_fu_1241_p2 = (empty_309_fu_1231_p2 ^ 1'd1);

assign xor_ln46_292_fu_1322_p2 = (empty_310_fu_1312_p2 ^ 1'd1);

assign xor_ln46_fu_755_p2 = (empty_fu_745_p2 ^ 1'd1);

assign zext_ln46_1138_fu_232_p1 = and_ln46_865_fu_226_p2;

assign zext_ln46_1139_fu_308_p1 = and_ln46_866_fu_302_p2;

assign zext_ln46_1140_fu_384_p1 = and_ln46_867_fu_378_p2;

assign zext_ln46_1141_fu_460_p1 = and_ln46_868_fu_454_p2;

assign zext_ln46_1142_fu_536_p1 = and_ln46_869_fu_530_p2;

assign zext_ln46_1143_fu_612_p1 = and_ln46_870_fu_606_p2;

assign zext_ln46_1144_fu_688_p1 = and_ln46_871_fu_682_p2;

assign zext_ln46_fu_156_p1 = and_ln46_fu_150_p2;

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_8_0_4_0_0_relu_config15_s
